// Code generated by MockGen. DO NOT EDIT.
// Source: privacy-social-backend/internal/repository (interfaces: Store)
//
// Generated by this command:
//
//	mockgen -package mockdb -destination internal/repository/mock/store.go privacy-social-backend/internal/repository Store
//

// Package mockdb is a generated GoMock package.
package mockdb

import (
	context "context"
	sql "database/sql"
	db "privacy-social-backend/internal/repository/db"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// AddGroupMember mocks base method.
func (m *MockStore) AddGroupMember(ctx context.Context, arg db.AddGroupMemberParams) (db.GroupMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddGroupMember", ctx, arg)
	ret0, _ := ret[0].(db.GroupMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddGroupMember indicates an expected call of AddGroupMember.
func (mr *MockStoreMockRecorder) AddGroupMember(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddGroupMember", reflect.TypeOf((*MockStore)(nil).AddGroupMember), ctx, arg)
}

// ArchiveStory mocks base method.
func (m *MockStore) ArchiveStory(ctx context.Context, arg db.ArchiveStoryParams) (db.ArchivedStory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ArchiveStory", ctx, arg)
	ret0, _ := ret[0].(db.ArchivedStory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ArchiveStory indicates an expected call of ArchiveStory.
func (mr *MockStoreMockRecorder) ArchiveStory(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArchiveStory", reflect.TypeOf((*MockStore)(nil).ArchiveStory), ctx, arg)
}

// BanUser mocks base method.
func (m *MockStore) BanUser(ctx context.Context, arg db.BanUserParams) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BanUser", ctx, arg)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BanUser indicates an expected call of BanUser.
func (mr *MockStoreMockRecorder) BanUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BanUser", reflect.TypeOf((*MockStore)(nil).BanUser), ctx, arg)
}

// BlockUser mocks base method.
func (m *MockStore) BlockUser(ctx context.Context, arg db.BlockUserParams) (db.BlockedUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlockUser", ctx, arg)
	ret0, _ := ret[0].(db.BlockedUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BlockUser indicates an expected call of BlockUser.
func (mr *MockStoreMockRecorder) BlockUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlockUser", reflect.TypeOf((*MockStore)(nil).BlockUser), ctx, arg)
}

// BoostUser mocks base method.
func (m *MockStore) BoostUser(ctx context.Context, arg db.BoostUserParams) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BoostUser", ctx, arg)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BoostUser indicates an expected call of BoostUser.
func (mr *MockStoreMockRecorder) BoostUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BoostUser", reflect.TypeOf((*MockStore)(nil).BoostUser), ctx, arg)
}

// CheckGroupMembership mocks base method.
func (m *MockStore) CheckGroupMembership(ctx context.Context, arg db.CheckGroupMembershipParams) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckGroupMembership", ctx, arg)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckGroupMembership indicates an expected call of CheckGroupMembership.
func (mr *MockStoreMockRecorder) CheckGroupMembership(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckGroupMembership", reflect.TypeOf((*MockStore)(nil).CheckGroupMembership), ctx, arg)
}

// ClearPasswordResetToken mocks base method.
func (m *MockStore) ClearPasswordResetToken(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearPasswordResetToken", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearPasswordResetToken indicates an expected call of ClearPasswordResetToken.
func (mr *MockStoreMockRecorder) ClearPasswordResetToken(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearPasswordResetToken", reflect.TypeOf((*MockStore)(nil).ClearPasswordResetToken), ctx, id)
}

// CountArchivedStories mocks base method.
func (m *MockStore) CountArchivedStories(ctx context.Context, userID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountArchivedStories", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountArchivedStories indicates an expected call of CountArchivedStories.
func (mr *MockStoreMockRecorder) CountArchivedStories(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountArchivedStories", reflect.TypeOf((*MockStore)(nil).CountArchivedStories), ctx, userID)
}

// CountConnectionRequestsToday mocks base method.
func (m *MockStore) CountConnectionRequestsToday(ctx context.Context, requesterID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountConnectionRequestsToday", ctx, requesterID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountConnectionRequestsToday indicates an expected call of CountConnectionRequestsToday.
func (mr *MockStoreMockRecorder) CountConnectionRequestsToday(ctx, requesterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountConnectionRequestsToday", reflect.TypeOf((*MockStore)(nil).CountConnectionRequestsToday), ctx, requesterID)
}

// CountCrossingsToday mocks base method.
func (m *MockStore) CountCrossingsToday(ctx context.Context, userID1 uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountCrossingsToday", ctx, userID1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountCrossingsToday indicates an expected call of CountCrossingsToday.
func (mr *MockStoreMockRecorder) CountCrossingsToday(ctx, userID1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountCrossingsToday", reflect.TypeOf((*MockStore)(nil).CountCrossingsToday), ctx, userID1)
}

// CountStoryReactions mocks base method.
func (m *MockStore) CountStoryReactions(ctx context.Context, storyID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountStoryReactions", ctx, storyID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountStoryReactions indicates an expected call of CountStoryReactions.
func (mr *MockStoreMockRecorder) CountStoryReactions(ctx, storyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountStoryReactions", reflect.TypeOf((*MockStore)(nil).CountStoryReactions), ctx, storyID)
}

// CountStoryViews mocks base method.
func (m *MockStore) CountStoryViews(ctx context.Context, storyID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountStoryViews", ctx, storyID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountStoryViews indicates an expected call of CountStoryViews.
func (mr *MockStoreMockRecorder) CountStoryViews(ctx, storyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountStoryViews", reflect.TypeOf((*MockStore)(nil).CountStoryViews), ctx, storyID)
}

// CountUnreadNotifications mocks base method.
func (m *MockStore) CountUnreadNotifications(ctx context.Context, userID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUnreadNotifications", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUnreadNotifications indicates an expected call of CountUnreadNotifications.
func (mr *MockStoreMockRecorder) CountUnreadNotifications(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUnreadNotifications", reflect.TypeOf((*MockStore)(nil).CountUnreadNotifications), ctx, userID)
}

// CountUsers mocks base method.
func (m *MockStore) CountUsers(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUsers", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUsers indicates an expected call of CountUsers.
func (mr *MockStoreMockRecorder) CountUsers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUsers", reflect.TypeOf((*MockStore)(nil).CountUsers), ctx)
}

// CreateConnectionRequest mocks base method.
func (m *MockStore) CreateConnectionRequest(ctx context.Context, arg db.CreateConnectionRequestParams) (db.Connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateConnectionRequest", ctx, arg)
	ret0, _ := ret[0].(db.Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateConnectionRequest indicates an expected call of CreateConnectionRequest.
func (mr *MockStoreMockRecorder) CreateConnectionRequest(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateConnectionRequest", reflect.TypeOf((*MockStore)(nil).CreateConnectionRequest), ctx, arg)
}

// CreateCrossing mocks base method.
func (m *MockStore) CreateCrossing(ctx context.Context, arg db.CreateCrossingParams) (db.Crossing, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCrossing", ctx, arg)
	ret0, _ := ret[0].(db.Crossing)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCrossing indicates an expected call of CreateCrossing.
func (mr *MockStoreMockRecorder) CreateCrossing(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCrossing", reflect.TypeOf((*MockStore)(nil).CreateCrossing), ctx, arg)
}

// CreateGroup mocks base method.
func (m *MockStore) CreateGroup(ctx context.Context, arg db.CreateGroupParams) (db.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGroup", ctx, arg)
	ret0, _ := ret[0].(db.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGroup indicates an expected call of CreateGroup.
func (mr *MockStoreMockRecorder) CreateGroup(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGroup", reflect.TypeOf((*MockStore)(nil).CreateGroup), ctx, arg)
}

// CreateLocation mocks base method.
func (m *MockStore) CreateLocation(ctx context.Context, arg db.CreateLocationParams) (db.Location, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLocation", ctx, arg)
	ret0, _ := ret[0].(db.Location)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLocation indicates an expected call of CreateLocation.
func (mr *MockStoreMockRecorder) CreateLocation(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLocation", reflect.TypeOf((*MockStore)(nil).CreateLocation), ctx, arg)
}

// CreateMessage mocks base method.
func (m *MockStore) CreateMessage(ctx context.Context, arg db.CreateMessageParams) (db.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMessage", ctx, arg)
	ret0, _ := ret[0].(db.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMessage indicates an expected call of CreateMessage.
func (mr *MockStoreMockRecorder) CreateMessage(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMessage", reflect.TypeOf((*MockStore)(nil).CreateMessage), ctx, arg)
}

// CreateMessageReaction mocks base method.
func (m *MockStore) CreateMessageReaction(ctx context.Context, arg db.CreateMessageReactionParams) (db.MessageReaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMessageReaction", ctx, arg)
	ret0, _ := ret[0].(db.MessageReaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMessageReaction indicates an expected call of CreateMessageReaction.
func (mr *MockStoreMockRecorder) CreateMessageReaction(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMessageReaction", reflect.TypeOf((*MockStore)(nil).CreateMessageReaction), ctx, arg)
}

// CreateNotification mocks base method.
func (m *MockStore) CreateNotification(ctx context.Context, arg db.CreateNotificationParams) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateNotification", ctx, arg)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateNotification indicates an expected call of CreateNotification.
func (mr *MockStoreMockRecorder) CreateNotification(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateNotification", reflect.TypeOf((*MockStore)(nil).CreateNotification), ctx, arg)
}

// CreateReport mocks base method.
func (m *MockStore) CreateReport(ctx context.Context, arg db.CreateReportParams) (db.Report, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateReport", ctx, arg)
	ret0, _ := ret[0].(db.Report)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateReport indicates an expected call of CreateReport.
func (mr *MockStoreMockRecorder) CreateReport(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateReport", reflect.TypeOf((*MockStore)(nil).CreateReport), ctx, arg)
}

// CreateSession mocks base method.
func (m *MockStore) CreateSession(ctx context.Context, arg db.CreateSessionParams) (db.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx, arg)
	ret0, _ := ret[0].(db.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockStoreMockRecorder) CreateSession(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockStore)(nil).CreateSession), ctx, arg)
}

// CreateStory mocks base method.
func (m *MockStore) CreateStory(ctx context.Context, arg db.CreateStoryParams) (db.CreateStoryRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStory", ctx, arg)
	ret0, _ := ret[0].(db.CreateStoryRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStory indicates an expected call of CreateStory.
func (mr *MockStoreMockRecorder) CreateStory(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStory", reflect.TypeOf((*MockStore)(nil).CreateStory), ctx, arg)
}

// CreateStoryMention mocks base method.
func (m *MockStore) CreateStoryMention(ctx context.Context, arg db.CreateStoryMentionParams) (db.StoryMention, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStoryMention", ctx, arg)
	ret0, _ := ret[0].(db.StoryMention)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStoryMention indicates an expected call of CreateStoryMention.
func (mr *MockStoreMockRecorder) CreateStoryMention(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStoryMention", reflect.TypeOf((*MockStore)(nil).CreateStoryMention), ctx, arg)
}

// CreateStoryReaction mocks base method.
func (m *MockStore) CreateStoryReaction(ctx context.Context, arg db.CreateStoryReactionParams) (db.StoryReaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStoryReaction", ctx, arg)
	ret0, _ := ret[0].(db.StoryReaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStoryReaction indicates an expected call of CreateStoryReaction.
func (mr *MockStoreMockRecorder) CreateStoryReaction(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStoryReaction", reflect.TypeOf((*MockStore)(nil).CreateStoryReaction), ctx, arg)
}

// CreateStoryView mocks base method.
func (m *MockStore) CreateStoryView(ctx context.Context, arg db.CreateStoryViewParams) (db.StoryView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStoryView", ctx, arg)
	ret0, _ := ret[0].(db.StoryView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStoryView indicates an expected call of CreateStoryView.
func (mr *MockStoreMockRecorder) CreateStoryView(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStoryView", reflect.TypeOf((*MockStore)(nil).CreateStoryView), ctx, arg)
}

// CreateUser mocks base method.
func (m *MockStore) CreateUser(ctx context.Context, arg db.CreateUserParams) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, arg)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockStoreMockRecorder) CreateUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockStore)(nil).CreateUser), ctx, arg)
}

// DeleteAllUserData mocks base method.
func (m *MockStore) DeleteAllUserData(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAllUserData", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAllUserData indicates an expected call of DeleteAllUserData.
func (mr *MockStoreMockRecorder) DeleteAllUserData(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllUserData", reflect.TypeOf((*MockStore)(nil).DeleteAllUserData), ctx, id)
}

// DeleteArchivedStory mocks base method.
func (m *MockStore) DeleteArchivedStory(ctx context.Context, arg db.DeleteArchivedStoryParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteArchivedStory", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteArchivedStory indicates an expected call of DeleteArchivedStory.
func (mr *MockStoreMockRecorder) DeleteArchivedStory(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteArchivedStory", reflect.TypeOf((*MockStore)(nil).DeleteArchivedStory), ctx, arg)
}

// DeleteConnection mocks base method.
func (m *MockStore) DeleteConnection(ctx context.Context, arg db.DeleteConnectionParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteConnection", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteConnection indicates an expected call of DeleteConnection.
func (mr *MockStoreMockRecorder) DeleteConnection(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteConnection", reflect.TypeOf((*MockStore)(nil).DeleteConnection), ctx, arg)
}

// DeleteConversation mocks base method.
func (m *MockStore) DeleteConversation(ctx context.Context, arg db.DeleteConversationParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteConversation", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteConversation indicates an expected call of DeleteConversation.
func (mr *MockStoreMockRecorder) DeleteConversation(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteConversation", reflect.TypeOf((*MockStore)(nil).DeleteConversation), ctx, arg)
}

// DeleteExpiredLocations mocks base method.
func (m *MockStore) DeleteExpiredLocations(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpiredLocations", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExpiredLocations indicates an expected call of DeleteExpiredLocations.
func (mr *MockStoreMockRecorder) DeleteExpiredLocations(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpiredLocations", reflect.TypeOf((*MockStore)(nil).DeleteExpiredLocations), ctx)
}

// DeleteExpiredMessages mocks base method.
func (m *MockStore) DeleteExpiredMessages(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpiredMessages", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExpiredMessages indicates an expected call of DeleteExpiredMessages.
func (mr *MockStoreMockRecorder) DeleteExpiredMessages(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpiredMessages", reflect.TypeOf((*MockStore)(nil).DeleteExpiredMessages), ctx)
}

// DeleteExpiredStories mocks base method.
func (m *MockStore) DeleteExpiredStories(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpiredStories", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExpiredStories indicates an expected call of DeleteExpiredStories.
func (mr *MockStoreMockRecorder) DeleteExpiredStories(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpiredStories", reflect.TypeOf((*MockStore)(nil).DeleteExpiredStories), ctx)
}

// DeleteMessage mocks base method.
func (m *MockStore) DeleteMessage(ctx context.Context, arg db.DeleteMessageParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMessage", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMessage indicates an expected call of DeleteMessage.
func (mr *MockStoreMockRecorder) DeleteMessage(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMessage", reflect.TypeOf((*MockStore)(nil).DeleteMessage), ctx, arg)
}

// DeleteMessageReaction mocks base method.
func (m *MockStore) DeleteMessageReaction(ctx context.Context, arg db.DeleteMessageReactionParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMessageReaction", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMessageReaction indicates an expected call of DeleteMessageReaction.
func (mr *MockStoreMockRecorder) DeleteMessageReaction(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMessageReaction", reflect.TypeOf((*MockStore)(nil).DeleteMessageReaction), ctx, arg)
}

// DeleteOldMessages mocks base method.
func (m *MockStore) DeleteOldMessages(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOldMessages", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOldMessages indicates an expected call of DeleteOldMessages.
func (mr *MockStoreMockRecorder) DeleteOldMessages(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOldMessages", reflect.TypeOf((*MockStore)(nil).DeleteOldMessages), ctx)
}

// DeleteOldNotifications mocks base method.
func (m *MockStore) DeleteOldNotifications(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOldNotifications", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOldNotifications indicates an expected call of DeleteOldNotifications.
func (mr *MockStoreMockRecorder) DeleteOldNotifications(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOldNotifications", reflect.TypeOf((*MockStore)(nil).DeleteOldNotifications), ctx)
}

// DeleteStory mocks base method.
func (m *MockStore) DeleteStory(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteStory", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteStory indicates an expected call of DeleteStory.
func (mr *MockStoreMockRecorder) DeleteStory(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStory", reflect.TypeOf((*MockStore)(nil).DeleteStory), ctx, id)
}

// DeleteStoryMentions mocks base method.
func (m *MockStore) DeleteStoryMentions(ctx context.Context, storyID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteStoryMentions", ctx, storyID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteStoryMentions indicates an expected call of DeleteStoryMentions.
func (mr *MockStoreMockRecorder) DeleteStoryMentions(ctx, storyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStoryMentions", reflect.TypeOf((*MockStore)(nil).DeleteStoryMentions), ctx, storyID)
}

// DeleteStoryReaction mocks base method.
func (m *MockStore) DeleteStoryReaction(ctx context.Context, arg db.DeleteStoryReactionParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteStoryReaction", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteStoryReaction indicates an expected call of DeleteStoryReaction.
func (mr *MockStoreMockRecorder) DeleteStoryReaction(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStoryReaction", reflect.TypeOf((*MockStore)(nil).DeleteStoryReaction), ctx, arg)
}

// DeleteUser mocks base method.
func (m *MockStore) DeleteUser(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockStoreMockRecorder) DeleteUser(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockStore)(nil).DeleteUser), ctx, id)
}

// ExecTx mocks base method.
func (m *MockStore) ExecTx(ctx context.Context, fn func(*db.Queries) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecTx", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecTx indicates an expected call of ExecTx.
func (mr *MockStoreMockRecorder) ExecTx(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecTx", reflect.TypeOf((*MockStore)(nil).ExecTx), ctx, fn)
}

// FindPotentialCrossings mocks base method.
func (m *MockStore) FindPotentialCrossings(ctx context.Context, arg db.FindPotentialCrossingsParams) ([]db.FindPotentialCrossingsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPotentialCrossings", ctx, arg)
	ret0, _ := ret[0].([]db.FindPotentialCrossingsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPotentialCrossings indicates an expected call of FindPotentialCrossings.
func (mr *MockStoreMockRecorder) FindPotentialCrossings(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPotentialCrossings", reflect.TypeOf((*MockStore)(nil).FindPotentialCrossings), ctx, arg)
}

// GetArchivedStories mocks base method.
func (m *MockStore) GetArchivedStories(ctx context.Context, arg db.GetArchivedStoriesParams) ([]db.ArchivedStory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArchivedStories", ctx, arg)
	ret0, _ := ret[0].([]db.ArchivedStory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArchivedStories indicates an expected call of GetArchivedStories.
func (mr *MockStoreMockRecorder) GetArchivedStories(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArchivedStories", reflect.TypeOf((*MockStore)(nil).GetArchivedStories), ctx, arg)
}

// GetArchivedStory mocks base method.
func (m *MockStore) GetArchivedStory(ctx context.Context, arg db.GetArchivedStoryParams) (db.ArchivedStory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArchivedStory", ctx, arg)
	ret0, _ := ret[0].(db.ArchivedStory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetArchivedStory indicates an expected call of GetArchivedStory.
func (mr *MockStoreMockRecorder) GetArchivedStory(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArchivedStory", reflect.TypeOf((*MockStore)(nil).GetArchivedStory), ctx, arg)
}

// GetBlockedUsers mocks base method.
func (m *MockStore) GetBlockedUsers(ctx context.Context, blockerID uuid.UUID) ([]db.GetBlockedUsersRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockedUsers", ctx, blockerID)
	ret0, _ := ret[0].([]db.GetBlockedUsersRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockedUsers indicates an expected call of GetBlockedUsers.
func (mr *MockStoreMockRecorder) GetBlockedUsers(ctx, blockerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockedUsers", reflect.TypeOf((*MockStore)(nil).GetBlockedUsers), ctx, blockerID)
}

// GetConnection mocks base method.
func (m *MockStore) GetConnection(ctx context.Context, arg db.GetConnectionParams) (db.Connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConnection", ctx, arg)
	ret0, _ := ret[0].(db.Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConnection indicates an expected call of GetConnection.
func (mr *MockStoreMockRecorder) GetConnection(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnection", reflect.TypeOf((*MockStore)(nil).GetConnection), ctx, arg)
}

// GetConnectionStories mocks base method.
func (m *MockStore) GetConnectionStories(ctx context.Context, userID uuid.UUID) ([]db.GetConnectionStoriesRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConnectionStories", ctx, userID)
	ret0, _ := ret[0].([]db.GetConnectionStoriesRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConnectionStories indicates an expected call of GetConnectionStories.
func (mr *MockStoreMockRecorder) GetConnectionStories(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnectionStories", reflect.TypeOf((*MockStore)(nil).GetConnectionStories), ctx, userID)
}

// GetConversationList mocks base method.
func (m *MockStore) GetConversationList(ctx context.Context, receiverID uuid.NullUUID) ([]db.GetConversationListRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConversationList", ctx, receiverID)
	ret0, _ := ret[0].([]db.GetConversationListRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConversationList indicates an expected call of GetConversationList.
func (mr *MockStoreMockRecorder) GetConversationList(ctx, receiverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConversationList", reflect.TypeOf((*MockStore)(nil).GetConversationList), ctx, receiverID)
}

// GetConversionStats mocks base method.
func (m *MockStore) GetConversionStats(ctx context.Context) (db.GetConversionStatsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConversionStats", ctx)
	ret0, _ := ret[0].(db.GetConversionStatsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConversionStats indicates an expected call of GetConversionStats.
func (mr *MockStoreMockRecorder) GetConversionStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConversionStats", reflect.TypeOf((*MockStore)(nil).GetConversionStats), ctx)
}

// GetCrossingsForUser mocks base method.
func (m *MockStore) GetCrossingsForUser(ctx context.Context, userID1 uuid.UUID) ([]db.Crossing, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCrossingsForUser", ctx, userID1)
	ret0, _ := ret[0].([]db.Crossing)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCrossingsForUser indicates an expected call of GetCrossingsForUser.
func (mr *MockStoreMockRecorder) GetCrossingsForUser(ctx, userID1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCrossingsForUser", reflect.TypeOf((*MockStore)(nil).GetCrossingsForUser), ctx, userID1)
}

// GetEngagementStats mocks base method.
func (m *MockStore) GetEngagementStats(ctx context.Context) (db.GetEngagementStatsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEngagementStats", ctx)
	ret0, _ := ret[0].(db.GetEngagementStatsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEngagementStats indicates an expected call of GetEngagementStats.
func (mr *MockStoreMockRecorder) GetEngagementStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEngagementStats", reflect.TypeOf((*MockStore)(nil).GetEngagementStats), ctx)
}

// GetGroupByID mocks base method.
func (m *MockStore) GetGroupByID(ctx context.Context, id uuid.UUID) (db.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupByID", ctx, id)
	ret0, _ := ret[0].(db.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupByID indicates an expected call of GetGroupByID.
func (mr *MockStoreMockRecorder) GetGroupByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupByID", reflect.TypeOf((*MockStore)(nil).GetGroupByID), ctx, id)
}

// GetGroupMembers mocks base method.
func (m *MockStore) GetGroupMembers(ctx context.Context, groupID uuid.UUID) ([]db.GetGroupMembersRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupMembers", ctx, groupID)
	ret0, _ := ret[0].([]db.GetGroupMembersRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupMembers indicates an expected call of GetGroupMembers.
func (mr *MockStoreMockRecorder) GetGroupMembers(ctx, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupMembers", reflect.TypeOf((*MockStore)(nil).GetGroupMembers), ctx, groupID)
}

// GetGroupMessages mocks base method.
func (m *MockStore) GetGroupMessages(ctx context.Context, groupID uuid.NullUUID) ([]db.GetGroupMessagesRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupMessages", ctx, groupID)
	ret0, _ := ret[0].([]db.GetGroupMessagesRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupMessages indicates an expected call of GetGroupMessages.
func (mr *MockStoreMockRecorder) GetGroupMessages(ctx, groupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupMessages", reflect.TypeOf((*MockStore)(nil).GetGroupMessages), ctx, groupID)
}

// GetHeatmapData mocks base method.
func (m *MockStore) GetHeatmapData(ctx context.Context) ([]db.GetHeatmapDataRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHeatmapData", ctx)
	ret0, _ := ret[0].([]db.GetHeatmapDataRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHeatmapData indicates an expected call of GetHeatmapData.
func (mr *MockStoreMockRecorder) GetHeatmapData(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHeatmapData", reflect.TypeOf((*MockStore)(nil).GetHeatmapData), ctx)
}

// GetMessage mocks base method.
func (m *MockStore) GetMessage(ctx context.Context, id uuid.UUID) (db.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessage", ctx, id)
	ret0, _ := ret[0].(db.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessage indicates an expected call of GetMessage.
func (mr *MockStoreMockRecorder) GetMessage(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessage", reflect.TypeOf((*MockStore)(nil).GetMessage), ctx, id)
}

// GetMessageReactions mocks base method.
func (m *MockStore) GetMessageReactions(ctx context.Context, messageID uuid.UUID) ([]db.GetMessageReactionsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessageReactions", ctx, messageID)
	ret0, _ := ret[0].([]db.GetMessageReactionsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessageReactions indicates an expected call of GetMessageReactions.
func (mr *MockStoreMockRecorder) GetMessageReactions(ctx, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessageReactions", reflect.TypeOf((*MockStore)(nil).GetMessageReactions), ctx, messageID)
}

// GetMyProfileViews mocks base method.
func (m *MockStore) GetMyProfileViews(ctx context.Context, viewerID uuid.UUID) ([]db.GetMyProfileViewsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMyProfileViews", ctx, viewerID)
	ret0, _ := ret[0].([]db.GetMyProfileViewsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMyProfileViews indicates an expected call of GetMyProfileViews.
func (mr *MockStoreMockRecorder) GetMyProfileViews(ctx, viewerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMyProfileViews", reflect.TypeOf((*MockStore)(nil).GetMyProfileViews), ctx, viewerID)
}

// GetPrivacySettings mocks base method.
func (m *MockStore) GetPrivacySettings(ctx context.Context, userID uuid.UUID) (db.PrivacySetting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrivacySettings", ctx, userID)
	ret0, _ := ret[0].(db.PrivacySetting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPrivacySettings indicates an expected call of GetPrivacySettings.
func (mr *MockStoreMockRecorder) GetPrivacySettings(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrivacySettings", reflect.TypeOf((*MockStore)(nil).GetPrivacySettings), ctx, userID)
}

// GetProfileViewCount mocks base method.
func (m *MockStore) GetProfileViewCount(ctx context.Context, viewedUserID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfileViewCount", ctx, viewedUserID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfileViewCount indicates an expected call of GetProfileViewCount.
func (mr *MockStoreMockRecorder) GetProfileViewCount(ctx, viewedUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfileViewCount", reflect.TypeOf((*MockStore)(nil).GetProfileViewCount), ctx, viewedUserID)
}

// GetRecentProfileVisitors mocks base method.
func (m *MockStore) GetRecentProfileVisitors(ctx context.Context, viewedUserID uuid.UUID) ([]db.GetRecentProfileVisitorsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecentProfileVisitors", ctx, viewedUserID)
	ret0, _ := ret[0].([]db.GetRecentProfileVisitorsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecentProfileVisitors indicates an expected call of GetRecentProfileVisitors.
func (mr *MockStoreMockRecorder) GetRecentProfileVisitors(ctx, viewedUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecentProfileVisitors", reflect.TypeOf((*MockStore)(nil).GetRecentProfileVisitors), ctx, viewedUserID)
}

// GetSession mocks base method.
func (m *MockStore) GetSession(ctx context.Context, id uuid.UUID) (db.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", ctx, id)
	ret0, _ := ret[0].(db.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockStoreMockRecorder) GetSession(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockStore)(nil).GetSession), ctx, id)
}

// GetStoriesInBounds mocks base method.
func (m *MockStore) GetStoriesInBounds(ctx context.Context, arg db.GetStoriesInBoundsParams) ([]db.GetStoriesInBoundsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStoriesInBounds", ctx, arg)
	ret0, _ := ret[0].([]db.GetStoriesInBoundsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStoriesInBounds indicates an expected call of GetStoriesInBounds.
func (mr *MockStoreMockRecorder) GetStoriesInBounds(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStoriesInBounds", reflect.TypeOf((*MockStore)(nil).GetStoriesInBounds), ctx, arg)
}

// GetStoriesWithinRadius mocks base method.
func (m *MockStore) GetStoriesWithinRadius(ctx context.Context, arg db.GetStoriesWithinRadiusParams) ([]db.GetStoriesWithinRadiusRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStoriesWithinRadius", ctx, arg)
	ret0, _ := ret[0].([]db.GetStoriesWithinRadiusRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStoriesWithinRadius indicates an expected call of GetStoriesWithinRadius.
func (mr *MockStoreMockRecorder) GetStoriesWithinRadius(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStoriesWithinRadius", reflect.TypeOf((*MockStore)(nil).GetStoriesWithinRadius), ctx, arg)
}

// GetStoryByID mocks base method.
func (m *MockStore) GetStoryByID(ctx context.Context, id uuid.UUID) (db.GetStoryByIDRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStoryByID", ctx, id)
	ret0, _ := ret[0].(db.GetStoryByIDRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStoryByID indicates an expected call of GetStoryByID.
func (mr *MockStoreMockRecorder) GetStoryByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStoryByID", reflect.TypeOf((*MockStore)(nil).GetStoryByID), ctx, id)
}

// GetStoryMentions mocks base method.
func (m *MockStore) GetStoryMentions(ctx context.Context, storyID uuid.UUID) ([]db.GetStoryMentionsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStoryMentions", ctx, storyID)
	ret0, _ := ret[0].([]db.GetStoryMentionsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStoryMentions indicates an expected call of GetStoryMentions.
func (mr *MockStoreMockRecorder) GetStoryMentions(ctx, storyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStoryMentions", reflect.TypeOf((*MockStore)(nil).GetStoryMentions), ctx, storyID)
}

// GetStoryReactions mocks base method.
func (m *MockStore) GetStoryReactions(ctx context.Context, storyID uuid.UUID) ([]db.GetStoryReactionsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStoryReactions", ctx, storyID)
	ret0, _ := ret[0].([]db.GetStoryReactionsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStoryReactions indicates an expected call of GetStoryReactions.
func (mr *MockStoreMockRecorder) GetStoryReactions(ctx, storyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStoryReactions", reflect.TypeOf((*MockStore)(nil).GetStoryReactions), ctx, storyID)
}

// GetStoryStats mocks base method.
func (m *MockStore) GetStoryStats(ctx context.Context) (db.GetStoryStatsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStoryStats", ctx)
	ret0, _ := ret[0].(db.GetStoryStatsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStoryStats indicates an expected call of GetStoryStats.
func (mr *MockStoreMockRecorder) GetStoryStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStoryStats", reflect.TypeOf((*MockStore)(nil).GetStoryStats), ctx)
}

// GetStoryViewers mocks base method.
func (m *MockStore) GetStoryViewers(ctx context.Context, storyID uuid.UUID) ([]db.GetStoryViewersRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStoryViewers", ctx, storyID)
	ret0, _ := ret[0].([]db.GetStoryViewersRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStoryViewers indicates an expected call of GetStoryViewers.
func (mr *MockStoreMockRecorder) GetStoryViewers(ctx, storyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStoryViewers", reflect.TypeOf((*MockStore)(nil).GetStoryViewers), ctx, storyID)
}

// GetStreakRetentionStats mocks base method.
func (m *MockStore) GetStreakRetentionStats(ctx context.Context) (db.GetStreakRetentionStatsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStreakRetentionStats", ctx)
	ret0, _ := ret[0].(db.GetStreakRetentionStatsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStreakRetentionStats indicates an expected call of GetStreakRetentionStats.
func (mr *MockStoreMockRecorder) GetStreakRetentionStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStreakRetentionStats", reflect.TypeOf((*MockStore)(nil).GetStreakRetentionStats), ctx)
}

// GetSuggestedConnections mocks base method.
func (m *MockStore) GetSuggestedConnections(ctx context.Context, arg db.GetSuggestedConnectionsParams) ([]db.GetSuggestedConnectionsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSuggestedConnections", ctx, arg)
	ret0, _ := ret[0].([]db.GetSuggestedConnectionsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSuggestedConnections indicates an expected call of GetSuggestedConnections.
func (mr *MockStoreMockRecorder) GetSuggestedConnections(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSuggestedConnections", reflect.TypeOf((*MockStore)(nil).GetSuggestedConnections), ctx, arg)
}

// GetSystemStats mocks base method.
func (m *MockStore) GetSystemStats(ctx context.Context) (db.GetSystemStatsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSystemStats", ctx)
	ret0, _ := ret[0].(db.GetSystemStatsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSystemStats indicates an expected call of GetSystemStats.
func (mr *MockStoreMockRecorder) GetSystemStats(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSystemStats", reflect.TypeOf((*MockStore)(nil).GetSystemStats), ctx)
}

// GetUnreadMessageCount mocks base method.
func (m *MockStore) GetUnreadMessageCount(ctx context.Context, receiverID uuid.NullUUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnreadMessageCount", ctx, receiverID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnreadMessageCount indicates an expected call of GetUnreadMessageCount.
func (mr *MockStoreMockRecorder) GetUnreadMessageCount(ctx, receiverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnreadMessageCount", reflect.TypeOf((*MockStore)(nil).GetUnreadMessageCount), ctx, receiverID)
}

// GetUserActivityStatus mocks base method.
func (m *MockStore) GetUserActivityStatus(ctx context.Context, id uuid.UUID) (db.GetUserActivityStatusRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserActivityStatus", ctx, id)
	ret0, _ := ret[0].(db.GetUserActivityStatusRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserActivityStatus indicates an expected call of GetUserActivityStatus.
func (mr *MockStoreMockRecorder) GetUserActivityStatus(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserActivityStatus", reflect.TypeOf((*MockStore)(nil).GetUserActivityStatus), ctx, id)
}

// GetUserByEmail mocks base method.
func (m *MockStore) GetUserByEmail(ctx context.Context, email sql.NullString) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockStoreMockRecorder) GetUserByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockStore)(nil).GetUserByEmail), ctx, email)
}

// GetUserByGoogleID mocks base method.
func (m *MockStore) GetUserByGoogleID(ctx context.Context, googleID sql.NullString) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByGoogleID", ctx, googleID)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByGoogleID indicates an expected call of GetUserByGoogleID.
func (mr *MockStoreMockRecorder) GetUserByGoogleID(ctx, googleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByGoogleID", reflect.TypeOf((*MockStore)(nil).GetUserByGoogleID), ctx, googleID)
}

// GetUserByID mocks base method.
func (m *MockStore) GetUserByID(ctx context.Context, id uuid.UUID) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockStoreMockRecorder) GetUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockStore)(nil).GetUserByID), ctx, id)
}

// GetUserByPhone mocks base method.
func (m *MockStore) GetUserByPhone(ctx context.Context, phone string) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByPhone", ctx, phone)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByPhone indicates an expected call of GetUserByPhone.
func (mr *MockStoreMockRecorder) GetUserByPhone(ctx, phone any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByPhone", reflect.TypeOf((*MockStore)(nil).GetUserByPhone), ctx, phone)
}

// GetUserByResetToken mocks base method.
func (m *MockStore) GetUserByResetToken(ctx context.Context, passwordResetToken sql.NullString) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByResetToken", ctx, passwordResetToken)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByResetToken indicates an expected call of GetUserByResetToken.
func (mr *MockStoreMockRecorder) GetUserByResetToken(ctx, passwordResetToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByResetToken", reflect.TypeOf((*MockStore)(nil).GetUserByResetToken), ctx, passwordResetToken)
}

// GetUserByUsername mocks base method.
func (m *MockStore) GetUserByUsername(ctx context.Context, username string) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByUsername", ctx, username)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByUsername indicates an expected call of GetUserByUsername.
func (mr *MockStoreMockRecorder) GetUserByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByUsername", reflect.TypeOf((*MockStore)(nil).GetUserByUsername), ctx, username)
}

// GetUserEngagementStats mocks base method.
func (m *MockStore) GetUserEngagementStats(ctx context.Context, userID uuid.UUID) (db.GetUserEngagementStatsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserEngagementStats", ctx, userID)
	ret0, _ := ret[0].(db.GetUserEngagementStatsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserEngagementStats indicates an expected call of GetUserEngagementStats.
func (mr *MockStoreMockRecorder) GetUserEngagementStats(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserEngagementStats", reflect.TypeOf((*MockStore)(nil).GetUserEngagementStats), ctx, userID)
}

// GetUserGroups mocks base method.
func (m *MockStore) GetUserGroups(ctx context.Context, userID uuid.UUID) ([]db.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserGroups", ctx, userID)
	ret0, _ := ret[0].([]db.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserGroups indicates an expected call of GetUserGroups.
func (mr *MockStoreMockRecorder) GetUserGroups(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserGroups", reflect.TypeOf((*MockStore)(nil).GetUserGroups), ctx, userID)
}

// GetUserMentions mocks base method.
func (m *MockStore) GetUserMentions(ctx context.Context, arg db.GetUserMentionsParams) ([]db.GetUserMentionsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserMentions", ctx, arg)
	ret0, _ := ret[0].([]db.GetUserMentionsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserMentions indicates an expected call of GetUserMentions.
func (mr *MockStoreMockRecorder) GetUserMentions(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserMentions", reflect.TypeOf((*MockStore)(nil).GetUserMentions), ctx, arg)
}

// GetUserProfile mocks base method.
func (m *MockStore) GetUserProfile(ctx context.Context, id uuid.UUID) (db.GetUserProfileRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserProfile", ctx, id)
	ret0, _ := ret[0].(db.GetUserProfileRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserProfile indicates an expected call of GetUserProfile.
func (mr *MockStoreMockRecorder) GetUserProfile(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserProfile", reflect.TypeOf((*MockStore)(nil).GetUserProfile), ctx, id)
}

// HasValidStory mocks base method.
func (m *MockStore) HasValidStory(ctx context.Context, userID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasValidStory", ctx, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasValidStory indicates an expected call of HasValidStory.
func (mr *MockStoreMockRecorder) HasValidStory(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasValidStory", reflect.TypeOf((*MockStore)(nil).HasValidStory), ctx, userID)
}

// IsUserBlocked mocks base method.
func (m *MockStore) IsUserBlocked(ctx context.Context, arg db.IsUserBlockedParams) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsUserBlocked", ctx, arg)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsUserBlocked indicates an expected call of IsUserBlocked.
func (mr *MockStoreMockRecorder) IsUserBlocked(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsUserBlocked", reflect.TypeOf((*MockStore)(nil).IsUserBlocked), ctx, arg)
}

// ListAllStories mocks base method.
func (m *MockStore) ListAllStories(ctx context.Context, arg db.ListAllStoriesParams) ([]db.ListAllStoriesRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllStories", ctx, arg)
	ret0, _ := ret[0].([]db.ListAllStoriesRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllStories indicates an expected call of ListAllStories.
func (mr *MockStoreMockRecorder) ListAllStories(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllStories", reflect.TypeOf((*MockStore)(nil).ListAllStories), ctx, arg)
}

// ListConnections mocks base method.
func (m *MockStore) ListConnections(ctx context.Context, requesterID uuid.UUID) ([]db.ListConnectionsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListConnections", ctx, requesterID)
	ret0, _ := ret[0].([]db.ListConnectionsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListConnections indicates an expected call of ListConnections.
func (mr *MockStoreMockRecorder) ListConnections(ctx, requesterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListConnections", reflect.TypeOf((*MockStore)(nil).ListConnections), ctx, requesterID)
}

// ListMessages mocks base method.
func (m *MockStore) ListMessages(ctx context.Context, arg db.ListMessagesParams) ([]db.ListMessagesRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMessages", ctx, arg)
	ret0, _ := ret[0].([]db.ListMessagesRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMessages indicates an expected call of ListMessages.
func (mr *MockStoreMockRecorder) ListMessages(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMessages", reflect.TypeOf((*MockStore)(nil).ListMessages), ctx, arg)
}

// ListNotifications mocks base method.
func (m *MockStore) ListNotifications(ctx context.Context, arg db.ListNotificationsParams) ([]db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNotifications", ctx, arg)
	ret0, _ := ret[0].([]db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNotifications indicates an expected call of ListNotifications.
func (mr *MockStoreMockRecorder) ListNotifications(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNotifications", reflect.TypeOf((*MockStore)(nil).ListNotifications), ctx, arg)
}

// ListPendingRequests mocks base method.
func (m *MockStore) ListPendingRequests(ctx context.Context, targetID uuid.UUID) ([]db.ListPendingRequestsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPendingRequests", ctx, targetID)
	ret0, _ := ret[0].([]db.ListPendingRequestsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPendingRequests indicates an expected call of ListPendingRequests.
func (mr *MockStoreMockRecorder) ListPendingRequests(ctx, targetID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPendingRequests", reflect.TypeOf((*MockStore)(nil).ListPendingRequests), ctx, targetID)
}

// ListReports mocks base method.
func (m *MockStore) ListReports(ctx context.Context, arg db.ListReportsParams) ([]db.ListReportsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListReports", ctx, arg)
	ret0, _ := ret[0].([]db.ListReportsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListReports indicates an expected call of ListReports.
func (mr *MockStoreMockRecorder) ListReports(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListReports", reflect.TypeOf((*MockStore)(nil).ListReports), ctx, arg)
}

// ListSentConnectionRequests mocks base method.
func (m *MockStore) ListSentConnectionRequests(ctx context.Context, requesterID uuid.UUID) ([]db.ListSentConnectionRequestsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSentConnectionRequests", ctx, requesterID)
	ret0, _ := ret[0].([]db.ListSentConnectionRequestsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSentConnectionRequests indicates an expected call of ListSentConnectionRequests.
func (mr *MockStoreMockRecorder) ListSentConnectionRequests(ctx, requesterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSentConnectionRequests", reflect.TypeOf((*MockStore)(nil).ListSentConnectionRequests), ctx, requesterID)
}

// ListUsers mocks base method.
func (m *MockStore) ListUsers(ctx context.Context, arg db.ListUsersParams) ([]db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx, arg)
	ret0, _ := ret[0].([]db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockStoreMockRecorder) ListUsers(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockStore)(nil).ListUsers), ctx, arg)
}

// MarkAllNotificationsAsRead mocks base method.
func (m *MockStore) MarkAllNotificationsAsRead(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAllNotificationsAsRead", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAllNotificationsAsRead indicates an expected call of MarkAllNotificationsAsRead.
func (mr *MockStoreMockRecorder) MarkAllNotificationsAsRead(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAllNotificationsAsRead", reflect.TypeOf((*MockStore)(nil).MarkAllNotificationsAsRead), ctx, userID)
}

// MarkConversationRead mocks base method.
func (m *MockStore) MarkConversationRead(ctx context.Context, arg db.MarkConversationReadParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkConversationRead", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkConversationRead indicates an expected call of MarkConversationRead.
func (mr *MockStoreMockRecorder) MarkConversationRead(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkConversationRead", reflect.TypeOf((*MockStore)(nil).MarkConversationRead), ctx, arg)
}

// MarkMessageRead mocks base method.
func (m *MockStore) MarkMessageRead(ctx context.Context, arg db.MarkMessageReadParams) (db.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkMessageRead", ctx, arg)
	ret0, _ := ret[0].(db.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkMessageRead indicates an expected call of MarkMessageRead.
func (mr *MockStoreMockRecorder) MarkMessageRead(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkMessageRead", reflect.TypeOf((*MockStore)(nil).MarkMessageRead), ctx, arg)
}

// MarkNotificationAsRead mocks base method.
func (m *MockStore) MarkNotificationAsRead(ctx context.Context, arg db.MarkNotificationAsReadParams) (db.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkNotificationAsRead", ctx, arg)
	ret0, _ := ret[0].(db.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkNotificationAsRead indicates an expected call of MarkNotificationAsRead.
func (mr *MockStoreMockRecorder) MarkNotificationAsRead(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkNotificationAsRead", reflect.TypeOf((*MockStore)(nil).MarkNotificationAsRead), ctx, arg)
}

// RemoveGroupMember mocks base method.
func (m *MockStore) RemoveGroupMember(ctx context.Context, arg db.RemoveGroupMemberParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveGroupMember", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveGroupMember indicates an expected call of RemoveGroupMember.
func (mr *MockStoreMockRecorder) RemoveGroupMember(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveGroupMember", reflect.TypeOf((*MockStore)(nil).RemoveGroupMember), ctx, arg)
}

// ResolveReport mocks base method.
func (m *MockStore) ResolveReport(ctx context.Context, id uuid.UUID) (db.Report, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveReport", ctx, id)
	ret0, _ := ret[0].(db.Report)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveReport indicates an expected call of ResolveReport.
func (mr *MockStoreMockRecorder) ResolveReport(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveReport", reflect.TypeOf((*MockStore)(nil).ResolveReport), ctx, id)
}

// SaveMessage mocks base method.
func (m *MockStore) SaveMessage(ctx context.Context, id uuid.UUID) (db.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveMessage", ctx, id)
	ret0, _ := ret[0].(db.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveMessage indicates an expected call of SaveMessage.
func (mr *MockStoreMockRecorder) SaveMessage(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveMessage", reflect.TypeOf((*MockStore)(nil).SaveMessage), ctx, id)
}

// SearchUsers mocks base method.
func (m *MockStore) SearchUsers(ctx context.Context, query string) ([]db.SearchUsersRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchUsers", ctx, query)
	ret0, _ := ret[0].([]db.SearchUsersRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchUsers indicates an expected call of SearchUsers.
func (mr *MockStoreMockRecorder) SearchUsers(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchUsers", reflect.TypeOf((*MockStore)(nil).SearchUsers), ctx, query)
}

// SetPasswordResetToken mocks base method.
func (m *MockStore) SetPasswordResetToken(ctx context.Context, arg db.SetPasswordResetTokenParams) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPasswordResetToken", ctx, arg)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetPasswordResetToken indicates an expected call of SetPasswordResetToken.
func (mr *MockStoreMockRecorder) SetPasswordResetToken(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPasswordResetToken", reflect.TypeOf((*MockStore)(nil).SetPasswordResetToken), ctx, arg)
}

// ToggleGhostMode mocks base method.
func (m *MockStore) ToggleGhostMode(ctx context.Context, arg db.ToggleGhostModeParams) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToggleGhostMode", ctx, arg)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ToggleGhostMode indicates an expected call of ToggleGhostMode.
func (mr *MockStoreMockRecorder) ToggleGhostMode(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToggleGhostMode", reflect.TypeOf((*MockStore)(nil).ToggleGhostMode), ctx, arg)
}

// TrackProfileView mocks base method.
func (m *MockStore) TrackProfileView(ctx context.Context, arg db.TrackProfileViewParams) (db.ProfileView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrackProfileView", ctx, arg)
	ret0, _ := ret[0].(db.ProfileView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TrackProfileView indicates an expected call of TrackProfileView.
func (mr *MockStoreMockRecorder) TrackProfileView(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackProfileView", reflect.TypeOf((*MockStore)(nil).TrackProfileView), ctx, arg)
}

// UnblockUser mocks base method.
func (m *MockStore) UnblockUser(ctx context.Context, arg db.UnblockUserParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnblockUser", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnblockUser indicates an expected call of UnblockUser.
func (mr *MockStoreMockRecorder) UnblockUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnblockUser", reflect.TypeOf((*MockStore)(nil).UnblockUser), ctx, arg)
}

// UpdateConnectionStatus mocks base method.
func (m *MockStore) UpdateConnectionStatus(ctx context.Context, arg db.UpdateConnectionStatusParams) (db.Connection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateConnectionStatus", ctx, arg)
	ret0, _ := ret[0].(db.Connection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateConnectionStatus indicates an expected call of UpdateConnectionStatus.
func (mr *MockStoreMockRecorder) UpdateConnectionStatus(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateConnectionStatus", reflect.TypeOf((*MockStore)(nil).UpdateConnectionStatus), ctx, arg)
}

// UpdateMessage mocks base method.
func (m *MockStore) UpdateMessage(ctx context.Context, arg db.UpdateMessageParams) (db.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMessage", ctx, arg)
	ret0, _ := ret[0].(db.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMessage indicates an expected call of UpdateMessage.
func (mr *MockStoreMockRecorder) UpdateMessage(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMessage", reflect.TypeOf((*MockStore)(nil).UpdateMessage), ctx, arg)
}

// UpdateStory mocks base method.
func (m *MockStore) UpdateStory(ctx context.Context, arg db.UpdateStoryParams) (db.UpdateStoryRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStory", ctx, arg)
	ret0, _ := ret[0].(db.UpdateStoryRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStory indicates an expected call of UpdateStory.
func (mr *MockStoreMockRecorder) UpdateStory(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStory", reflect.TypeOf((*MockStore)(nil).UpdateStory), ctx, arg)
}

// UpdateUserActivity mocks base method.
func (m *MockStore) UpdateUserActivity(ctx context.Context, id uuid.UUID) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserActivity", ctx, id)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserActivity indicates an expected call of UpdateUserActivity.
func (mr *MockStoreMockRecorder) UpdateUserActivity(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserActivity", reflect.TypeOf((*MockStore)(nil).UpdateUserActivity), ctx, id)
}

// UpdateUserEmail mocks base method.
func (m *MockStore) UpdateUserEmail(ctx context.Context, arg db.UpdateUserEmailParams) (db.UpdateUserEmailRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserEmail", ctx, arg)
	ret0, _ := ret[0].(db.UpdateUserEmailRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserEmail indicates an expected call of UpdateUserEmail.
func (mr *MockStoreMockRecorder) UpdateUserEmail(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserEmail", reflect.TypeOf((*MockStore)(nil).UpdateUserEmail), ctx, arg)
}

// UpdateUserGoogleID mocks base method.
func (m *MockStore) UpdateUserGoogleID(ctx context.Context, arg db.UpdateUserGoogleIDParams) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserGoogleID", ctx, arg)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserGoogleID indicates an expected call of UpdateUserGoogleID.
func (mr *MockStoreMockRecorder) UpdateUserGoogleID(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserGoogleID", reflect.TypeOf((*MockStore)(nil).UpdateUserGoogleID), ctx, arg)
}

// UpdateUserPassword mocks base method.
func (m *MockStore) UpdateUserPassword(ctx context.Context, arg db.UpdateUserPasswordParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserPassword", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserPassword indicates an expected call of UpdateUserPassword.
func (mr *MockStoreMockRecorder) UpdateUserPassword(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserPassword", reflect.TypeOf((*MockStore)(nil).UpdateUserPassword), ctx, arg)
}

// UpdateUserProfile mocks base method.
func (m *MockStore) UpdateUserProfile(ctx context.Context, arg db.UpdateUserProfileParams) (db.UpdateUserProfileRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserProfile", ctx, arg)
	ret0, _ := ret[0].(db.UpdateUserProfileRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserProfile indicates an expected call of UpdateUserProfile.
func (mr *MockStoreMockRecorder) UpdateUserProfile(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserProfile", reflect.TypeOf((*MockStore)(nil).UpdateUserProfile), ctx, arg)
}

// UpdateUserTrust mocks base method.
func (m *MockStore) UpdateUserTrust(ctx context.Context, arg db.UpdateUserTrustParams) (db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserTrust", ctx, arg)
	ret0, _ := ret[0].(db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserTrust indicates an expected call of UpdateUserTrust.
func (mr *MockStoreMockRecorder) UpdateUserTrust(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserTrust", reflect.TypeOf((*MockStore)(nil).UpdateUserTrust), ctx, arg)
}

// UpsertPrivacySettings mocks base method.
func (m *MockStore) UpsertPrivacySettings(ctx context.Context, arg db.UpsertPrivacySettingsParams) (db.PrivacySetting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertPrivacySettings", ctx, arg)
	ret0, _ := ret[0].(db.PrivacySetting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertPrivacySettings indicates an expected call of UpsertPrivacySettings.
func (mr *MockStoreMockRecorder) UpsertPrivacySettings(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertPrivacySettings", reflect.TypeOf((*MockStore)(nil).UpsertPrivacySettings), ctx, arg)
}
