// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activity.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createActivityLog = `-- name: CreateActivityLog :one
INSERT INTO activity_logs (
    user_id,
    action_type,
    target_id,
    target_type,
    details
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, user_id, action_type, target_id, target_type, details, created_at
`

type CreateActivityLogParams struct {
	UserID     uuid.UUID             `json:"user_id"`
	ActionType string                `json:"action_type"`
	TargetID   uuid.NullUUID         `json:"target_id"`
	TargetType sql.NullString        `json:"target_type"`
	Details    pqtype.NullRawMessage `json:"details"`
}

func (q *Queries) CreateActivityLog(ctx context.Context, arg CreateActivityLogParams) (ActivityLog, error) {
	row := q.db.QueryRowContext(ctx, createActivityLog,
		arg.UserID,
		arg.ActionType,
		arg.TargetID,
		arg.TargetType,
		arg.Details,
	)
	var i ActivityLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ActionType,
		&i.TargetID,
		&i.TargetType,
		&i.Details,
		&i.CreatedAt,
	)
	return i, err
}

const deleteActivityLog = `-- name: DeleteActivityLog :exec
DELETE FROM activity_logs
WHERE id = $1
`

func (q *Queries) DeleteActivityLog(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteActivityLog, id)
	return err
}

const listActivityLogs = `-- name: ListActivityLogs :many
SELECT al.id, al.user_id, al.action_type, al.target_id, al.target_type, al.details, al.created_at, u.username, u.avatar_url
FROM activity_logs al
JOIN users u ON al.user_id = u.id
ORDER BY al.created_at DESC
LIMIT $1 OFFSET $2
`

type ListActivityLogsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListActivityLogsRow struct {
	ID         uuid.UUID             `json:"id"`
	UserID     uuid.UUID             `json:"user_id"`
	ActionType string                `json:"action_type"`
	TargetID   uuid.NullUUID         `json:"target_id"`
	TargetType sql.NullString        `json:"target_type"`
	Details    pqtype.NullRawMessage `json:"details"`
	CreatedAt  time.Time             `json:"created_at"`
	Username   string                `json:"username"`
	AvatarUrl  sql.NullString        `json:"avatar_url"`
}

func (q *Queries) ListActivityLogs(ctx context.Context, arg ListActivityLogsParams) ([]ListActivityLogsRow, error) {
	rows, err := q.db.QueryContext(ctx, listActivityLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActivityLogsRow
	for rows.Next() {
		var i ListActivityLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ActionType,
			&i.TargetID,
			&i.TargetType,
			&i.Details,
			&i.CreatedAt,
			&i.Username,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
