// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analytics.sql

package db

import (
	"context"
)

const getConversionStats = `-- name: GetConversionStats :one
WITH crossing_stats AS (
    SELECT COUNT(*) as total_crossings FROM crossings
),
connection_stats AS (
    SELECT COUNT(*) as total_connections FROM connections WHERE status = 'accepted'
)
SELECT 
    (SELECT total_connections FROM connection_stats) as total_connections,
    (SELECT total_crossings FROM crossing_stats) as total_crossings,
    -- Simple Ratio for now (Crossings -> Connections)
    ((SELECT total_connections FROM connection_stats)::float / NULLIF((SELECT total_crossings FROM crossing_stats), 0)::float) * 100 as crossing_conversion_rate
FROM crossing_stats, connection_stats
`

type GetConversionStatsRow struct {
	TotalConnections       int64 `json:"total_connections"`
	TotalCrossings         int64 `json:"total_crossings"`
	CrossingConversionRate int32 `json:"crossing_conversion_rate"`
}

func (q *Queries) GetConversionStats(ctx context.Context) (GetConversionStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getConversionStats)
	var i GetConversionStatsRow
	err := row.Scan(&i.TotalConnections, &i.TotalCrossings, &i.CrossingConversionRate)
	return i, err
}

const getEngagementStats = `-- name: GetEngagementStats :one
SELECT 
    COUNT(*) FILTER (WHERE created_at > NOW() - INTERVAL '7 days') as stories_last_7d,
    (COUNT(*) FILTER (WHERE created_at > NOW() - INTERVAL '7 days')::float / NULLIF((SELECT COUNT(*) FROM users), 0)::float) as avg_stories_per_user_weekly
FROM stories
`

type GetEngagementStatsRow struct {
	StoriesLast7d           int64 `json:"stories_last_7d"`
	AvgStoriesPerUserWeekly int32 `json:"avg_stories_per_user_weekly"`
}

func (q *Queries) GetEngagementStats(ctx context.Context) (GetEngagementStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getEngagementStats)
	var i GetEngagementStatsRow
	err := row.Scan(&i.StoriesLast7d, &i.AvgStoriesPerUserWeekly)
	return i, err
}

const getStreakRetentionStats = `-- name: GetStreakRetentionStats :one
SELECT 
    COUNT(*) FILTER (WHERE activity_streak >= 3) as retained_users_count,
    COUNT(*) as total_users_count,
    (COUNT(*) FILTER (WHERE activity_streak >= 3)::float / NULLIF(COUNT(*), 0)::float) * 100 as retention_rate
FROM users
`

type GetStreakRetentionStatsRow struct {
	RetainedUsersCount int64 `json:"retained_users_count"`
	TotalUsersCount    int64 `json:"total_users_count"`
	RetentionRate      int32 `json:"retention_rate"`
}

func (q *Queries) GetStreakRetentionStats(ctx context.Context) (GetStreakRetentionStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getStreakRetentionStats)
	var i GetStreakRetentionStatsRow
	err := row.Scan(&i.RetainedUsersCount, &i.TotalUsersCount, &i.RetentionRate)
	return i, err
}
