// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: archived_stories.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const archiveStory = `-- name: ArchiveStory :one
INSERT INTO archived_stories (
    user_id, story_id, media_url, media_type, caption,
    geohash, geom, is_anonymous, show_location, original_created_at
)
SELECT 
    s.user_id, s.id, s.media_url, s.media_type, s.caption,
    s.geohash, s.geom, s.is_anonymous, s.show_location, s.created_at
FROM stories s
WHERE s.id = $1 AND s.user_id = $2
ON CONFLICT (user_id, story_id) DO NOTHING
RETURNING id, user_id, story_id, media_url, media_type, caption, geohash, geom, is_anonymous, show_location, original_created_at, archived_at, created_at
`

type ArchiveStoryParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) ArchiveStory(ctx context.Context, arg ArchiveStoryParams) (ArchivedStory, error) {
	row := q.db.QueryRowContext(ctx, archiveStory, arg.ID, arg.UserID)
	var i ArchivedStory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StoryID,
		&i.MediaUrl,
		&i.MediaType,
		&i.Caption,
		&i.Geohash,
		&i.Geom,
		&i.IsAnonymous,
		&i.ShowLocation,
		&i.OriginalCreatedAt,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const countArchivedStories = `-- name: CountArchivedStories :one
SELECT COUNT(*) FROM archived_stories
WHERE user_id = $1
`

func (q *Queries) CountArchivedStories(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countArchivedStories, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteArchivedStory = `-- name: DeleteArchivedStory :exec
DELETE FROM archived_stories
WHERE id = $1 AND user_id = $2
`

type DeleteArchivedStoryParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteArchivedStory(ctx context.Context, arg DeleteArchivedStoryParams) error {
	_, err := q.db.ExecContext(ctx, deleteArchivedStory, arg.ID, arg.UserID)
	return err
}

const getArchivedStories = `-- name: GetArchivedStories :many
SELECT id, user_id, story_id, media_url, media_type, caption, geohash, geom, is_anonymous, show_location, original_created_at, archived_at, created_at FROM archived_stories
WHERE user_id = $1
ORDER BY archived_at DESC
LIMIT $2 OFFSET $3
`

type GetArchivedStoriesParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) GetArchivedStories(ctx context.Context, arg GetArchivedStoriesParams) ([]ArchivedStory, error) {
	rows, err := q.db.QueryContext(ctx, getArchivedStories, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ArchivedStory
	for rows.Next() {
		var i ArchivedStory
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StoryID,
			&i.MediaUrl,
			&i.MediaType,
			&i.Caption,
			&i.Geohash,
			&i.Geom,
			&i.IsAnonymous,
			&i.ShowLocation,
			&i.OriginalCreatedAt,
			&i.ArchivedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArchivedStory = `-- name: GetArchivedStory :one
SELECT id, user_id, story_id, media_url, media_type, caption, geohash, geom, is_anonymous, show_location, original_created_at, archived_at, created_at FROM archived_stories
WHERE id = $1 AND user_id = $2
`

type GetArchivedStoryParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetArchivedStory(ctx context.Context, arg GetArchivedStoryParams) (ArchivedStory, error) {
	row := q.db.QueryRowContext(ctx, getArchivedStory, arg.ID, arg.UserID)
	var i ArchivedStory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StoryID,
		&i.MediaUrl,
		&i.MediaType,
		&i.Caption,
		&i.Geohash,
		&i.Geom,
		&i.IsAnonymous,
		&i.ShowLocation,
		&i.OriginalCreatedAt,
		&i.ArchivedAt,
		&i.CreatedAt,
	)
	return i, err
}
