// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPasswordReset = `-- name: CreatePasswordReset :one
INSERT INTO password_resets (
    user_id,
    token,
    expires_at
) VALUES (
    $1, $2, $3
) RETURNING id, user_id, token, expires_at, created_at
`

type CreatePasswordResetParams struct {
	UserID    uuid.UUID `json:"user_id"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreatePasswordReset(ctx context.Context, arg CreatePasswordResetParams) (PasswordReset, error) {
	row := q.db.QueryRowContext(ctx, createPasswordReset, arg.UserID, arg.Token, arg.ExpiresAt)
	var i PasswordReset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredPasswordResets = `-- name: DeleteExpiredPasswordResets :exec
DELETE FROM password_resets
WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredPasswordResets(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredPasswordResets)
	return err
}

const deletePasswordResetByToken = `-- name: DeletePasswordResetByToken :exec
DELETE FROM password_resets
WHERE token = $1
`

func (q *Queries) DeletePasswordResetByToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deletePasswordResetByToken, token)
	return err
}

const deleteUserPasswordResets = `-- name: DeleteUserPasswordResets :exec
DELETE FROM password_resets
WHERE user_id = $1
`

func (q *Queries) DeleteUserPasswordResets(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUserPasswordResets, userID)
	return err
}

const getPasswordResetByToken = `-- name: GetPasswordResetByToken :one
SELECT id, user_id, token, expires_at, created_at FROM password_resets
WHERE token = $1 
AND expires_at > now()
LIMIT 1
`

func (q *Queries) GetPasswordResetByToken(ctx context.Context, token string) (PasswordReset, error) {
	row := q.db.QueryRowContext(ctx, getPasswordResetByToken, token)
	var i PasswordReset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
