// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: blocking.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const blockUser = `-- name: BlockUser :one
INSERT INTO blocked_users (blocker_id, blocked_id)
VALUES ($1, $2)
RETURNING id, blocker_id, blocked_id, created_at
`

type BlockUserParams struct {
	BlockerID uuid.UUID `json:"blocker_id"`
	BlockedID uuid.UUID `json:"blocked_id"`
}

func (q *Queries) BlockUser(ctx context.Context, arg BlockUserParams) (BlockedUser, error) {
	row := q.db.QueryRowContext(ctx, blockUser, arg.BlockerID, arg.BlockedID)
	var i BlockedUser
	err := row.Scan(
		&i.ID,
		&i.BlockerID,
		&i.BlockedID,
		&i.CreatedAt,
	)
	return i, err
}

const getBlockedUsers = `-- name: GetBlockedUsers :many
SELECT u.id, u.username, u.full_name, u.avatar_url, b.created_at as blocked_at
FROM blocked_users b
JOIN users u ON b.blocked_id = u.id
WHERE b.blocker_id = $1
ORDER BY b.created_at DESC
`

type GetBlockedUsersRow struct {
	ID        uuid.UUID      `json:"id"`
	Username  string         `json:"username"`
	FullName  string         `json:"full_name"`
	AvatarUrl sql.NullString `json:"avatar_url"`
	BlockedAt sql.NullTime   `json:"blocked_at"`
}

func (q *Queries) GetBlockedUsers(ctx context.Context, blockerID uuid.UUID) ([]GetBlockedUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, getBlockedUsers, blockerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBlockedUsersRow
	for rows.Next() {
		var i GetBlockedUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FullName,
			&i.AvatarUrl,
			&i.BlockedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isUserBlocked = `-- name: IsUserBlocked :one
SELECT EXISTS (
    SELECT 1 FROM blocked_users
    WHERE blocker_id = $1 AND blocked_id = $2
)
`

type IsUserBlockedParams struct {
	BlockerID uuid.UUID `json:"blocker_id"`
	BlockedID uuid.UUID `json:"blocked_id"`
}

func (q *Queries) IsUserBlocked(ctx context.Context, arg IsUserBlockedParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isUserBlocked, arg.BlockerID, arg.BlockedID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const unblockUser = `-- name: UnblockUser :exec
DELETE FROM blocked_users
WHERE blocker_id = $1 AND blocked_id = $2
`

type UnblockUserParams struct {
	BlockerID uuid.UUID `json:"blocker_id"`
	BlockedID uuid.UUID `json:"blocked_id"`
}

func (q *Queries) UnblockUser(ctx context.Context, arg UnblockUserParams) error {
	_, err := q.db.ExecContext(ctx, unblockUser, arg.BlockerID, arg.BlockedID)
	return err
}
