// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: connections.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countConnectionRequestsToday = `-- name: CountConnectionRequestsToday :one
SELECT COUNT(*) FROM connections
WHERE requester_id = $1
AND created_at > NOW() - INTERVAL '24 hours'
AND status = 'pending'
`

func (q *Queries) CountConnectionRequestsToday(ctx context.Context, requesterID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countConnectionRequestsToday, requesterID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createConnectionRequest = `-- name: CreateConnectionRequest :one
INSERT INTO connections (
  requester_id,
  target_id,
  status
) VALUES (
  $1, $2, 'pending'
) RETURNING requester_id, target_id, status, created_at, updated_at
`

type CreateConnectionRequestParams struct {
	RequesterID uuid.UUID `json:"requester_id"`
	TargetID    uuid.UUID `json:"target_id"`
}

func (q *Queries) CreateConnectionRequest(ctx context.Context, arg CreateConnectionRequestParams) (Connection, error) {
	row := q.db.QueryRowContext(ctx, createConnectionRequest, arg.RequesterID, arg.TargetID)
	var i Connection
	err := row.Scan(
		&i.RequesterID,
		&i.TargetID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteConnection = `-- name: DeleteConnection :exec
DELETE FROM connections
WHERE (requester_id = $1 AND target_id = $2)
   OR (requester_id = $2 AND target_id = $1)
`

type DeleteConnectionParams struct {
	RequesterID uuid.UUID `json:"requester_id"`
	TargetID    uuid.UUID `json:"target_id"`
}

func (q *Queries) DeleteConnection(ctx context.Context, arg DeleteConnectionParams) error {
	_, err := q.db.ExecContext(ctx, deleteConnection, arg.RequesterID, arg.TargetID)
	return err
}

const getConnection = `-- name: GetConnection :one
SELECT requester_id, target_id, status, created_at, updated_at FROM connections
WHERE (requester_id = $1 AND target_id = $2)
   OR (requester_id = $2 AND target_id = $1)
LIMIT 1
`

type GetConnectionParams struct {
	RequesterID uuid.UUID `json:"requester_id"`
	TargetID    uuid.UUID `json:"target_id"`
}

func (q *Queries) GetConnection(ctx context.Context, arg GetConnectionParams) (Connection, error) {
	row := q.db.QueryRowContext(ctx, getConnection, arg.RequesterID, arg.TargetID)
	var i Connection
	err := row.Scan(
		&i.RequesterID,
		&i.TargetID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSuggestedConnections = `-- name: GetSuggestedConnections :many
WITH my_connections AS (
    SELECT c1.target_id as friend_id FROM connections c1 WHERE c1.requester_id = $1 AND c1.status = 'accepted'
    UNION
    SELECT c2.requester_id as friend_id FROM connections c2 WHERE c2.target_id = $1 AND c2.status = 'accepted'
),
excluded_users AS (
    SELECT c3.target_id as id FROM connections c3 WHERE c3.requester_id = $1
    UNION
    SELECT c4.requester_id as id FROM connections c4 WHERE c4.target_id = $1
    UNION
    SELECT $1::uuid as id
)
SELECT 
    u.id, 
    u.username, 
    u.full_name, 
    u.avatar_url,
    COALESCE((
        SELECT COUNT(*)
        FROM connections c
        WHERE 
            c.status = 'accepted' AND (
                (c.requester_id = u.id AND c.target_id IN (SELECT friend_id FROM my_connections)) OR
                (c.target_id = u.id AND c.requester_id IN (SELECT friend_id FROM my_connections))
            )
    ), 0)::bigint as mutual_count
FROM users u
WHERE u.id NOT IN (SELECT id FROM excluded_users)
AND u.is_shadow_banned = false
ORDER BY mutual_count DESC, u.created_at DESC
LIMIT $2
`

type GetSuggestedConnectionsParams struct {
	RequesterID uuid.UUID `json:"requester_id"`
	Limit       int32     `json:"limit"`
}

type GetSuggestedConnectionsRow struct {
	ID          uuid.UUID      `json:"id"`
	Username    string         `json:"username"`
	FullName    string         `json:"full_name"`
	AvatarUrl   sql.NullString `json:"avatar_url"`
	MutualCount int64          `json:"mutual_count"`
}

func (q *Queries) GetSuggestedConnections(ctx context.Context, arg GetSuggestedConnectionsParams) ([]GetSuggestedConnectionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getSuggestedConnections, arg.RequesterID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSuggestedConnectionsRow
	for rows.Next() {
		var i GetSuggestedConnectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FullName,
			&i.AvatarUrl,
			&i.MutualCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConnections = `-- name: ListConnections :many
SELECT 
    u.id, 
    u.username, 
    u.full_name, 
    u.avatar_url,
    u.last_active_at
FROM connections c
JOIN users u ON (u.id = c.requester_id OR u.id = c.target_id)
WHERE (c.requester_id = $1 OR c.target_id = $1)
  AND u.id != $1
  AND c.status = 'accepted'
`

type ListConnectionsRow struct {
	ID           uuid.UUID      `json:"id"`
	Username     string         `json:"username"`
	FullName     string         `json:"full_name"`
	AvatarUrl    sql.NullString `json:"avatar_url"`
	LastActiveAt sql.NullTime   `json:"last_active_at"`
}

func (q *Queries) ListConnections(ctx context.Context, requesterID uuid.UUID) ([]ListConnectionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listConnections, requesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConnectionsRow
	for rows.Next() {
		var i ListConnectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FullName,
			&i.AvatarUrl,
			&i.LastActiveAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingRequests = `-- name: ListPendingRequests :many
SELECT 
    c.requester_id, 
    c.target_id, 
    c.status, 
    c.created_at,
    u.username,
    u.full_name,
    u.avatar_url
FROM connections c
JOIN users u ON c.requester_id = u.id
WHERE c.target_id = $1 
  AND c.status = 'pending'
ORDER BY c.created_at DESC
`

type ListPendingRequestsRow struct {
	RequesterID uuid.UUID        `json:"requester_id"`
	TargetID    uuid.UUID        `json:"target_id"`
	Status      ConnectionStatus `json:"status"`
	CreatedAt   time.Time        `json:"created_at"`
	Username    string           `json:"username"`
	FullName    string           `json:"full_name"`
	AvatarUrl   sql.NullString   `json:"avatar_url"`
}

func (q *Queries) ListPendingRequests(ctx context.Context, targetID uuid.UUID) ([]ListPendingRequestsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingRequests, targetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingRequestsRow
	for rows.Next() {
		var i ListPendingRequestsRow
		if err := rows.Scan(
			&i.RequesterID,
			&i.TargetID,
			&i.Status,
			&i.CreatedAt,
			&i.Username,
			&i.FullName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSentConnectionRequests = `-- name: ListSentConnectionRequests :many
SELECT 
    c.requester_id, 
    c.target_id, 
    c.status, 
    c.created_at,
    u.username,
    u.full_name,
    u.avatar_url
FROM connections c
JOIN users u ON c.target_id = u.id
WHERE c.requester_id = $1 
  AND c.status = 'pending'
ORDER BY c.created_at DESC
`

type ListSentConnectionRequestsRow struct {
	RequesterID uuid.UUID        `json:"requester_id"`
	TargetID    uuid.UUID        `json:"target_id"`
	Status      ConnectionStatus `json:"status"`
	CreatedAt   time.Time        `json:"created_at"`
	Username    string           `json:"username"`
	FullName    string           `json:"full_name"`
	AvatarUrl   sql.NullString   `json:"avatar_url"`
}

func (q *Queries) ListSentConnectionRequests(ctx context.Context, requesterID uuid.UUID) ([]ListSentConnectionRequestsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSentConnectionRequests, requesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSentConnectionRequestsRow
	for rows.Next() {
		var i ListSentConnectionRequestsRow
		if err := rows.Scan(
			&i.RequesterID,
			&i.TargetID,
			&i.Status,
			&i.CreatedAt,
			&i.Username,
			&i.FullName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConnectionStatus = `-- name: UpdateConnectionStatus :one
UPDATE connections
SET status = $3, updated_at = now()
WHERE requester_id = $1 AND target_id = $2
RETURNING requester_id, target_id, status, created_at, updated_at
`

type UpdateConnectionStatusParams struct {
	RequesterID uuid.UUID        `json:"requester_id"`
	TargetID    uuid.UUID        `json:"target_id"`
	Status      ConnectionStatus `json:"status"`
}

func (q *Queries) UpdateConnectionStatus(ctx context.Context, arg UpdateConnectionStatusParams) (Connection, error) {
	row := q.db.QueryRowContext(ctx, updateConnectionStatus, arg.RequesterID, arg.TargetID, arg.Status)
	var i Connection
	err := row.Scan(
		&i.RequesterID,
		&i.TargetID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
