// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: crossings.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countAdminCrossings = `-- name: CountAdminCrossings :one
SELECT COUNT(*) FROM crossings
`

func (q *Queries) CountAdminCrossings(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdminCrossings)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCrossingsToday = `-- name: CountCrossingsToday :one
SELECT COUNT(*) FROM crossings
WHERE (user_id_1 = $1 OR user_id_2 = $1)
AND occurred_at >= CURRENT_DATE
`

func (q *Queries) CountCrossingsToday(ctx context.Context, userID1 uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCrossingsToday, userID1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCrossing = `-- name: CreateCrossing :one
INSERT INTO crossings (
  user_id_1,
  user_id_2,
  location_center,
  occurred_at
) VALUES (
  $1, $2, $3, $4
) RETURNING id, user_id_1, user_id_2, location_center, occurred_at, created_at
`

type CreateCrossingParams struct {
	UserID1        uuid.UUID `json:"user_id_1"`
	UserID2        uuid.UUID `json:"user_id_2"`
	LocationCenter string    `json:"location_center"`
	OccurredAt     time.Time `json:"occurred_at"`
}

func (q *Queries) CreateCrossing(ctx context.Context, arg CreateCrossingParams) (Crossing, error) {
	row := q.db.QueryRowContext(ctx, createCrossing,
		arg.UserID1,
		arg.UserID2,
		arg.LocationCenter,
		arg.OccurredAt,
	)
	var i Crossing
	err := row.Scan(
		&i.ID,
		&i.UserID1,
		&i.UserID2,
		&i.LocationCenter,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const findPotentialCrossings = `-- name: FindPotentialCrossings :many
SELECT 
    l1.user_id AS user1, 
    l2.user_id AS user2, 
    l1.geohash AS location, 
    l1.time_bucket
FROM locations l1
JOIN locations l2 ON l1.geohash = l2.geohash AND l1.time_bucket = l2.time_bucket
JOIN users u1 ON l1.user_id = u1.id
JOIN users u2 ON l2.user_id = u2.id
WHERE l1.user_id < l2.user_id
AND l1.time_bucket >= $1::timestamptz
AND l1.time_bucket < $2::timestamptz
AND u1.is_ghost_mode = false
AND u2.is_ghost_mode = false
AND u1.is_shadow_banned = false
AND u2.is_shadow_banned = false
AND NOT EXISTS (
    SELECT 1 FROM blocked_users bu 
    WHERE (bu.blocker_id = l1.user_id AND bu.blocked_id = l2.user_id)
       OR (bu.blocker_id = l2.user_id AND bu.blocked_id = l1.user_id)
)
GROUP BY l1.user_id, l2.user_id, l1.geohash, l1.time_bucket
`

type FindPotentialCrossingsParams struct {
	MinTime time.Time `json:"min_time"`
	MaxTime time.Time `json:"max_time"`
}

type FindPotentialCrossingsRow struct {
	User1      uuid.UUID `json:"user1"`
	User2      uuid.UUID `json:"user2"`
	Location   string    `json:"location"`
	TimeBucket time.Time `json:"time_bucket"`
}

// Block Logic
func (q *Queries) FindPotentialCrossings(ctx context.Context, arg FindPotentialCrossingsParams) ([]FindPotentialCrossingsRow, error) {
	rows, err := q.db.QueryContext(ctx, findPotentialCrossings, arg.MinTime, arg.MaxTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindPotentialCrossingsRow
	for rows.Next() {
		var i FindPotentialCrossingsRow
		if err := rows.Scan(
			&i.User1,
			&i.User2,
			&i.Location,
			&i.TimeBucket,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCrossingCount = `-- name: GetCrossingCount :one
SELECT COUNT(*) FROM crossings 
WHERE (user_id_1 = LEAST($1::uuid,$2::uuid) AND user_id_2 = GREATEST($1::uuid,$2::uuid))
`

type GetCrossingCountParams struct {
	Column1 uuid.UUID `json:"column_1"`
	Column2 uuid.UUID `json:"column_2"`
}

func (q *Queries) GetCrossingCount(ctx context.Context, arg GetCrossingCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCrossingCount, arg.Column1, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCrossingsForUser = `-- name: GetCrossingsForUser :many
SELECT c.id, c.user_id_1, c.user_id_2, c.location_center, c.occurred_at, c.created_at FROM crossings c
JOIN users u1 ON c.user_id_1 = u1.id
JOIN users u2 ON c.user_id_2 = u2.id
WHERE 
  (c.user_id_1 = $1 OR c.user_id_2 = $1)
  -- Filter out ghost mode users (other user)
  AND (
    (c.user_id_1 = $1 AND u2.is_ghost_mode = false) OR
    (c.user_id_2 = $1 AND u1.is_ghost_mode = false)
  )
  -- (strict streak visibility rule removed for testing/discovery)
  -- Shadow Ban Filter
  AND (
    (c.user_id_1 = $1 AND u2.is_shadow_banned = false) OR
    (c.user_id_2 = $1 AND u1.is_shadow_banned = false)
  )
  -- Block Logic
  AND NOT EXISTS (
    SELECT 1 FROM blocked_users bu 
    WHERE (bu.blocker_id = $1 AND bu.blocked_id = CASE WHEN c.user_id_1 = $1 THEN c.user_id_2 ELSE c.user_id_1 END)
       OR (bu.blocker_id = CASE WHEN c.user_id_1 = $1 THEN c.user_id_2 ELSE c.user_id_1 END AND bu.blocked_id = $1)
  )
ORDER BY c.occurred_at DESC
`

func (q *Queries) GetCrossingsForUser(ctx context.Context, userID1 uuid.UUID) ([]Crossing, error) {
	rows, err := q.db.QueryContext(ctx, getCrossingsForUser, userID1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Crossing
	for rows.Next() {
		var i Crossing
		if err := rows.Scan(
			&i.ID,
			&i.UserID1,
			&i.UserID2,
			&i.LocationCenter,
			&i.OccurredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalCrossingsCountToday = `-- name: GetTotalCrossingsCountToday :one
SELECT COUNT(*) FROM crossings
WHERE occurred_at >= CURRENT_DATE
`

func (q *Queries) GetTotalCrossingsCountToday(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalCrossingsCountToday)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listAdminCrossings = `-- name: ListAdminCrossings :many
SELECT 
    c.id, 
    c.location_center, 
    c.occurred_at, 
    u1.id as u1_id, u1.username as u1_username, u1.full_name as u1_full_name, u1.avatar_url as u1_avatar_url,
    u2.id as u2_id, u2.username as u2_username, u2.full_name as u2_full_name, u2.avatar_url as u2_avatar_url,
    ST_Y(c.location_center::geometry) as lat,
    ST_X(c.location_center::geometry) as lng
FROM crossings c
JOIN users u1 ON c.user_id_1 = u1.id
JOIN users u2 ON c.user_id_2 = u2.id
ORDER BY c.occurred_at DESC
LIMIT CAST($1 AS int) OFFSET CAST($2 AS int)
`

type ListAdminCrossingsParams struct {
	Column1 int32 `json:"column_1"`
	Column2 int32 `json:"column_2"`
}

type ListAdminCrossingsRow struct {
	ID             uuid.UUID      `json:"id"`
	LocationCenter string         `json:"location_center"`
	OccurredAt     time.Time      `json:"occurred_at"`
	U1ID           uuid.UUID      `json:"u1_id"`
	U1Username     string         `json:"u1_username"`
	U1FullName     string         `json:"u1_full_name"`
	U1AvatarUrl    sql.NullString `json:"u1_avatar_url"`
	U2ID           uuid.UUID      `json:"u2_id"`
	U2Username     string         `json:"u2_username"`
	U2FullName     string         `json:"u2_full_name"`
	U2AvatarUrl    sql.NullString `json:"u2_avatar_url"`
	Lat            interface{}    `json:"lat"`
	Lng            interface{}    `json:"lng"`
}

func (q *Queries) ListAdminCrossings(ctx context.Context, arg ListAdminCrossingsParams) ([]ListAdminCrossingsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAdminCrossings, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminCrossingsRow
	for rows.Next() {
		var i ListAdminCrossingsRow
		if err := rows.Scan(
			&i.ID,
			&i.LocationCenter,
			&i.OccurredAt,
			&i.U1ID,
			&i.U1Username,
			&i.U1FullName,
			&i.U1AvatarUrl,
			&i.U2ID,
			&i.U2Username,
			&i.U2FullName,
			&i.U2AvatarUrl,
			&i.Lat,
			&i.Lng,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
