// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: highlight.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const addStoryToHighlight = `-- name: AddStoryToHighlight :one
INSERT INTO highlight_stories (highlight_id, archived_story_id)
VALUES ($1, $2)
ON CONFLICT (highlight_id, archived_story_id) DO NOTHING
RETURNING id, highlight_id, archived_story_id, added_at
`

type AddStoryToHighlightParams struct {
	HighlightID     uuid.UUID `json:"highlight_id"`
	ArchivedStoryID uuid.UUID `json:"archived_story_id"`
}

func (q *Queries) AddStoryToHighlight(ctx context.Context, arg AddStoryToHighlightParams) (HighlightStory, error) {
	row := q.db.QueryRowContext(ctx, addStoryToHighlight, arg.HighlightID, arg.ArchivedStoryID)
	var i HighlightStory
	err := row.Scan(
		&i.ID,
		&i.HighlightID,
		&i.ArchivedStoryID,
		&i.AddedAt,
	)
	return i, err
}

const createHighlight = `-- name: CreateHighlight :one
INSERT INTO highlight_groups (user_id, title, cover_url)
VALUES ($1, $2, $3)
RETURNING id, user_id, title, cover_url, created_at, updated_at
`

type CreateHighlightParams struct {
	UserID   uuid.UUID      `json:"user_id"`
	Title    string         `json:"title"`
	CoverUrl sql.NullString `json:"cover_url"`
}

func (q *Queries) CreateHighlight(ctx context.Context, arg CreateHighlightParams) (HighlightGroup, error) {
	row := q.db.QueryRowContext(ctx, createHighlight, arg.UserID, arg.Title, arg.CoverUrl)
	var i HighlightGroup
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.CoverUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteHighlight = `-- name: DeleteHighlight :exec
DELETE FROM highlight_groups WHERE id = $1 AND user_id = $2
`

type DeleteHighlightParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteHighlight(ctx context.Context, arg DeleteHighlightParams) error {
	_, err := q.db.ExecContext(ctx, deleteHighlight, arg.ID, arg.UserID)
	return err
}

const getHighlightDetails = `-- name: GetHighlightDetails :many
SELECT a.id, a.user_id, a.story_id, a.media_url, a.media_type, a.caption, a.geohash, a.geom, a.is_anonymous, a.show_location, a.original_created_at, a.archived_at, a.created_at, hs.added_at
FROM highlight_stories hs
JOIN archived_stories a ON hs.archived_story_id = a.id
WHERE hs.highlight_id = $1
ORDER BY hs.added_at ASC
`

type GetHighlightDetailsRow struct {
	ID                uuid.UUID      `json:"id"`
	UserID            uuid.UUID      `json:"user_id"`
	StoryID           uuid.UUID      `json:"story_id"`
	MediaUrl          string         `json:"media_url"`
	MediaType         string         `json:"media_type"`
	Caption           sql.NullString `json:"caption"`
	Geohash           string         `json:"geohash"`
	Geom              interface{}    `json:"geom"`
	IsAnonymous       sql.NullBool   `json:"is_anonymous"`
	ShowLocation      sql.NullBool   `json:"show_location"`
	OriginalCreatedAt time.Time      `json:"original_created_at"`
	ArchivedAt        sql.NullTime   `json:"archived_at"`
	CreatedAt         sql.NullTime   `json:"created_at"`
	AddedAt           time.Time      `json:"added_at"`
}

// Returns all archived stories belonging to a highlight
func (q *Queries) GetHighlightDetails(ctx context.Context, highlightID uuid.UUID) ([]GetHighlightDetailsRow, error) {
	rows, err := q.db.QueryContext(ctx, getHighlightDetails, highlightID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHighlightDetailsRow
	for rows.Next() {
		var i GetHighlightDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StoryID,
			&i.MediaUrl,
			&i.MediaType,
			&i.Caption,
			&i.Geohash,
			&i.Geom,
			&i.IsAnonymous,
			&i.ShowLocation,
			&i.OriginalCreatedAt,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHighlightsByUserID = `-- name: ListHighlightsByUserID :many
SELECT hg.id, hg.user_id, hg.title, hg.cover_url, hg.created_at, hg.updated_at,
    (SELECT COUNT(*) FROM highlight_stories WHERE highlight_id = hg.id) as story_count
FROM highlight_groups hg
WHERE hg.user_id = $1
ORDER BY hg.created_at ASC
`

type ListHighlightsByUserIDRow struct {
	ID         uuid.UUID      `json:"id"`
	UserID     uuid.UUID      `json:"user_id"`
	Title      string         `json:"title"`
	CoverUrl   sql.NullString `json:"cover_url"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
	StoryCount int64          `json:"story_count"`
}

func (q *Queries) ListHighlightsByUserID(ctx context.Context, userID uuid.UUID) ([]ListHighlightsByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listHighlightsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListHighlightsByUserIDRow
	for rows.Next() {
		var i ListHighlightsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.CoverUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StoryCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeStoryFromHighlight = `-- name: RemoveStoryFromHighlight :exec
DELETE FROM highlight_stories WHERE highlight_id = $1 AND archived_story_id = $2
`

type RemoveStoryFromHighlightParams struct {
	HighlightID     uuid.UUID `json:"highlight_id"`
	ArchivedStoryID uuid.UUID `json:"archived_story_id"`
}

func (q *Queries) RemoveStoryFromHighlight(ctx context.Context, arg RemoveStoryFromHighlightParams) error {
	_, err := q.db.ExecContext(ctx, removeStoryFromHighlight, arg.HighlightID, arg.ArchivedStoryID)
	return err
}

const updateHighlightCover = `-- name: UpdateHighlightCover :one
UPDATE highlight_groups SET cover_url = $1, updated_at = now()
WHERE id = $2 AND user_id = $3
RETURNING id, user_id, title, cover_url, created_at, updated_at
`

type UpdateHighlightCoverParams struct {
	CoverUrl sql.NullString `json:"cover_url"`
	ID       uuid.UUID      `json:"id"`
	UserID   uuid.UUID      `json:"user_id"`
}

func (q *Queries) UpdateHighlightCover(ctx context.Context, arg UpdateHighlightCoverParams) (HighlightGroup, error) {
	row := q.db.QueryRowContext(ctx, updateHighlightCover, arg.CoverUrl, arg.ID, arg.UserID)
	var i HighlightGroup
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.CoverUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
