// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: locations.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createLocation = `-- name: CreateLocation :one
INSERT INTO locations (
  user_id,
  geohash,
  geom,
  time_bucket,
  expires_at
) VALUES (
  $1, $2, ST_SetSRID(ST_MakePoint($3::float8, $4::float8), 4326), $5, $6
) RETURNING id, user_id, geohash, geom, time_bucket, created_at, expires_at
`

type CreateLocationParams struct {
	UserID     uuid.UUID `json:"user_id"`
	Geohash    string    `json:"geohash"`
	Lng        float64   `json:"lng"`
	Lat        float64   `json:"lat"`
	TimeBucket time.Time `json:"time_bucket"`
	ExpiresAt  time.Time `json:"expires_at"`
}

func (q *Queries) CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error) {
	row := q.db.QueryRowContext(ctx, createLocation,
		arg.UserID,
		arg.Geohash,
		arg.Lng,
		arg.Lat,
		arg.TimeBucket,
		arg.ExpiresAt,
	)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Geohash,
		&i.Geom,
		&i.TimeBucket,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExpiredLocations = `-- name: DeleteExpiredLocations :exec
DELETE FROM locations
WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredLocations(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredLocations)
	return err
}

const getHeatmapData = `-- name: GetHeatmapData :many
SELECT 
  ST_X(ST_SnapToGrid(geom, 0.001)) as longitude,
  ST_Y(ST_SnapToGrid(geom, 0.001)) as latitude,
  COUNT(*) as weight
FROM locations
WHERE time_bucket > NOW() - INTERVAL '1 hour'
GROUP BY ST_SnapToGrid(geom, 0.001)
`

type GetHeatmapDataRow struct {
	Longitude interface{} `json:"longitude"`
	Latitude  interface{} `json:"latitude"`
	Weight    int64       `json:"weight"`
}

func (q *Queries) GetHeatmapData(ctx context.Context) ([]GetHeatmapDataRow, error) {
	rows, err := q.db.QueryContext(ctx, getHeatmapData)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetHeatmapDataRow
	for rows.Next() {
		var i GetHeatmapDataRow
		if err := rows.Scan(&i.Longitude, &i.Latitude, &i.Weight); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
