// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (
  sender_id,
  receiver_id,
  group_id,
  content,
  media_url,
  media_type,
  expires_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
) RETURNING id, sender_id, receiver_id, content, is_read, created_at, read_at, expires_at, media_url, media_type, group_id
`

type CreateMessageParams struct {
	SenderID   uuid.UUID      `json:"sender_id"`
	ReceiverID uuid.NullUUID  `json:"receiver_id"`
	GroupID    uuid.NullUUID  `json:"group_id"`
	Content    string         `json:"content"`
	MediaUrl   sql.NullString `json:"media_url"`
	MediaType  sql.NullString `json:"media_type"`
	ExpiresAt  sql.NullTime   `json:"expires_at"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage,
		arg.SenderID,
		arg.ReceiverID,
		arg.GroupID,
		arg.Content,
		arg.MediaUrl,
		arg.MediaType,
		arg.ExpiresAt,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.ReceiverID,
		&i.Content,
		&i.IsRead,
		&i.CreatedAt,
		&i.ReadAt,
		&i.ExpiresAt,
		&i.MediaUrl,
		&i.MediaType,
		&i.GroupID,
	)
	return i, err
}

const createMessageReaction = `-- name: CreateMessageReaction :one
INSERT INTO message_reactions (message_id, user_id, emoji)
VALUES ($1, $2, $3)
ON CONFLICT (message_id, user_id, emoji) DO NOTHING
RETURNING id, message_id, user_id, emoji, created_at
`

type CreateMessageReactionParams struct {
	MessageID uuid.UUID `json:"message_id"`
	UserID    uuid.UUID `json:"user_id"`
	Emoji     string    `json:"emoji"`
}

func (q *Queries) CreateMessageReaction(ctx context.Context, arg CreateMessageReactionParams) (MessageReaction, error) {
	row := q.db.QueryRowContext(ctx, createMessageReaction, arg.MessageID, arg.UserID, arg.Emoji)
	var i MessageReaction
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.UserID,
		&i.Emoji,
		&i.CreatedAt,
	)
	return i, err
}

const deleteConversation = `-- name: DeleteConversation :exec
DELETE FROM messages
WHERE (sender_id = $1 AND receiver_id = $2)
   OR (sender_id = $2 AND receiver_id = $1)
`

type DeleteConversationParams struct {
	SenderID   uuid.UUID     `json:"sender_id"`
	ReceiverID uuid.NullUUID `json:"receiver_id"`
}

func (q *Queries) DeleteConversation(ctx context.Context, arg DeleteConversationParams) error {
	_, err := q.db.ExecContext(ctx, deleteConversation, arg.SenderID, arg.ReceiverID)
	return err
}

const deleteExpiredMessages = `-- name: DeleteExpiredMessages :exec
DELETE FROM messages
WHERE expires_at IS NOT NULL AND expires_at < NOW()
`

func (q *Queries) DeleteExpiredMessages(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredMessages)
	return err
}

const deleteMessage = `-- name: DeleteMessage :exec
DELETE FROM messages
WHERE id = $1 AND sender_id = $2
`

type DeleteMessageParams struct {
	ID       uuid.UUID `json:"id"`
	SenderID uuid.UUID `json:"sender_id"`
}

func (q *Queries) DeleteMessage(ctx context.Context, arg DeleteMessageParams) error {
	_, err := q.db.ExecContext(ctx, deleteMessage, arg.ID, arg.SenderID)
	return err
}

const deleteMessageReaction = `-- name: DeleteMessageReaction :exec
DELETE FROM message_reactions
WHERE message_id = $1 AND user_id = $2 AND emoji = $3
`

type DeleteMessageReactionParams struct {
	MessageID uuid.UUID `json:"message_id"`
	UserID    uuid.UUID `json:"user_id"`
	Emoji     string    `json:"emoji"`
}

func (q *Queries) DeleteMessageReaction(ctx context.Context, arg DeleteMessageReactionParams) error {
	_, err := q.db.ExecContext(ctx, deleteMessageReaction, arg.MessageID, arg.UserID, arg.Emoji)
	return err
}

const deleteOldMessages = `-- name: DeleteOldMessages :exec
DELETE FROM messages
WHERE created_at < NOW() - INTERVAL '30 days'
`

// Delete messages older than specified days (default: 30 days)
func (q *Queries) DeleteOldMessages(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteOldMessages)
	return err
}

const getConversationList = `-- name: GetConversationList :many
WITH conversation_partners AS (
  SELECT DISTINCT
    CASE 
      WHEN sender_id = $1 THEN receiver_id
      ELSE sender_id
    END as partner_id
  FROM messages
  WHERE sender_id = $1 OR receiver_id = $1
),
latest_messages AS (
  SELECT DISTINCT ON (
    CASE 
      WHEN m.sender_id = $1 THEN m.receiver_id
      ELSE m.sender_id
    END
  )
    CASE 
      WHEN m.sender_id = $1 THEN m.receiver_id
      ELSE m.sender_id
    END as partner_id,
    m.id as message_id,
    m.content as last_message,
    m.created_at as last_message_at,
    m.sender_id as last_sender_id
  FROM messages m
  WHERE (m.sender_id = $1 OR m.receiver_id = $1)
    AND (m.expires_at IS NULL OR m.expires_at > NOW())
  ORDER BY 
    CASE 
      WHEN m.sender_id = $1 THEN m.receiver_id
      ELSE m.sender_id
    END,
    m.created_at DESC
)
SELECT 
  u.id,
  u.username,
  u.full_name,
  u.avatar_url,
  lm.last_message,
  lm.last_message_at,
  lm.last_sender_id,
  COALESCE(
    (SELECT COUNT(*) 
     FROM messages m2
     WHERE m2.sender_id = u.id 
       AND m2.receiver_id = $1 
       AND m2.read_at IS NULL
       AND (m2.expires_at IS NULL OR m2.expires_at > NOW())
    ), 0
  ) as unread_count
FROM conversation_partners cp
JOIN users u ON u.id = cp.partner_id
JOIN latest_messages lm ON lm.partner_id = cp.partner_id
ORDER BY lm.last_message_at DESC
`

type GetConversationListRow struct {
	ID            uuid.UUID      `json:"id"`
	Username      string         `json:"username"`
	FullName      string         `json:"full_name"`
	AvatarUrl     sql.NullString `json:"avatar_url"`
	LastMessage   string         `json:"last_message"`
	LastMessageAt time.Time      `json:"last_message_at"`
	LastSenderID  uuid.UUID      `json:"last_sender_id"`
	UnreadCount   interface{}    `json:"unread_count"`
}

func (q *Queries) GetConversationList(ctx context.Context, receiverID uuid.NullUUID) ([]GetConversationListRow, error) {
	rows, err := q.db.QueryContext(ctx, getConversationList, receiverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetConversationListRow
	for rows.Next() {
		var i GetConversationListRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FullName,
			&i.AvatarUrl,
			&i.LastMessage,
			&i.LastMessageAt,
			&i.LastSenderID,
			&i.UnreadCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupMessages = `-- name: GetGroupMessages :many
SELECT m.id, m.sender_id, m.receiver_id, m.content, m.is_read, m.created_at, m.read_at, m.expires_at, m.media_url, m.media_type, m.group_id, 
       u.username, 
       u.avatar_url,
       COALESCE(
           (SELECT json_agg(json_build_object(
               'id', mr.id,
               'emoji', mr.emoji,
               'user_id', mr.user_id,
               'username', reaction_user.username,
               'avatar_url', reaction_user.avatar_url,
               'created_at', mr.created_at
           ) ORDER BY mr.created_at ASC)
            FROM message_reactions mr
            JOIN users reaction_user ON mr.user_id = reaction_user.id
            WHERE mr.message_id = m.id),
           '[]'::json
       ) as reactions
FROM messages m
JOIN users u ON m.sender_id = u.id
WHERE m.group_id = $1
ORDER BY m.created_at ASC
`

type GetGroupMessagesRow struct {
	ID         uuid.UUID      `json:"id"`
	SenderID   uuid.UUID      `json:"sender_id"`
	ReceiverID uuid.NullUUID  `json:"receiver_id"`
	Content    string         `json:"content"`
	IsRead     bool           `json:"is_read"`
	CreatedAt  time.Time      `json:"created_at"`
	ReadAt     sql.NullTime   `json:"read_at"`
	ExpiresAt  sql.NullTime   `json:"expires_at"`
	MediaUrl   sql.NullString `json:"media_url"`
	MediaType  sql.NullString `json:"media_type"`
	GroupID    uuid.NullUUID  `json:"group_id"`
	Username   string         `json:"username"`
	AvatarUrl  sql.NullString `json:"avatar_url"`
	Reactions  interface{}    `json:"reactions"`
}

func (q *Queries) GetGroupMessages(ctx context.Context, groupID uuid.NullUUID) ([]GetGroupMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, getGroupMessages, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGroupMessagesRow
	for rows.Next() {
		var i GetGroupMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.ReceiverID,
			&i.Content,
			&i.IsRead,
			&i.CreatedAt,
			&i.ReadAt,
			&i.ExpiresAt,
			&i.MediaUrl,
			&i.MediaType,
			&i.GroupID,
			&i.Username,
			&i.AvatarUrl,
			&i.Reactions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessage = `-- name: GetMessage :one
SELECT id, sender_id, receiver_id, content, is_read, created_at, read_at, expires_at, media_url, media_type, group_id FROM messages WHERE id = $1
`

func (q *Queries) GetMessage(ctx context.Context, id uuid.UUID) (Message, error) {
	row := q.db.QueryRowContext(ctx, getMessage, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.ReceiverID,
		&i.Content,
		&i.IsRead,
		&i.CreatedAt,
		&i.ReadAt,
		&i.ExpiresAt,
		&i.MediaUrl,
		&i.MediaType,
		&i.GroupID,
	)
	return i, err
}

const getMessageReactions = `-- name: GetMessageReactions :many
SELECT mr.id, mr.message_id, mr.user_id, mr.emoji, mr.created_at, u.username, u.avatar_url
FROM message_reactions mr
JOIN users u ON mr.user_id = u.id
WHERE mr.message_id = $1

ORDER BY mr.created_at ASC
`

type GetMessageReactionsRow struct {
	ID        uuid.UUID      `json:"id"`
	MessageID uuid.UUID      `json:"message_id"`
	UserID    uuid.UUID      `json:"user_id"`
	Emoji     string         `json:"emoji"`
	CreatedAt time.Time      `json:"created_at"`
	Username  string         `json:"username"`
	AvatarUrl sql.NullString `json:"avatar_url"`
}

func (q *Queries) GetMessageReactions(ctx context.Context, messageID uuid.UUID) ([]GetMessageReactionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getMessageReactions, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMessageReactionsRow
	for rows.Next() {
		var i GetMessageReactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.UserID,
			&i.Emoji,
			&i.CreatedAt,
			&i.Username,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnreadMessageCount = `-- name: GetUnreadMessageCount :one
SELECT COUNT(*) FROM messages
WHERE receiver_id = $1 AND read_at IS NULL
`

func (q *Queries) GetUnreadMessageCount(ctx context.Context, receiverID uuid.NullUUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUnreadMessageCount, receiverID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listMessages = `-- name: ListMessages :many
SELECT m.id, m.sender_id, m.receiver_id, m.content, m.is_read, m.created_at, m.read_at, m.expires_at, m.media_url, m.media_type, m.group_id,
       COALESCE(
           (SELECT json_agg(json_build_object(
               'id', mr.id,
               'emoji', mr.emoji,
               'user_id', mr.user_id,
               'username', u.username,
               'avatar_url', u.avatar_url,
               'created_at', mr.created_at
           ) ORDER BY mr.created_at ASC)
            FROM message_reactions mr
            JOIN users u ON mr.user_id = u.id
            WHERE mr.message_id = m.id),
           '[]'::json
       ) as reactions
FROM messages m
WHERE ((m.sender_id = $1 AND m.receiver_id = $2)
   OR (m.sender_id = $2 AND m.receiver_id = $1))
   AND m.group_id IS NULL
   AND (m.expires_at IS NULL OR m.expires_at > NOW())
ORDER BY m.created_at ASC
`

type ListMessagesParams struct {
	SenderID   uuid.UUID     `json:"sender_id"`
	ReceiverID uuid.NullUUID `json:"receiver_id"`
}

type ListMessagesRow struct {
	ID         uuid.UUID      `json:"id"`
	SenderID   uuid.UUID      `json:"sender_id"`
	ReceiverID uuid.NullUUID  `json:"receiver_id"`
	Content    string         `json:"content"`
	IsRead     bool           `json:"is_read"`
	CreatedAt  time.Time      `json:"created_at"`
	ReadAt     sql.NullTime   `json:"read_at"`
	ExpiresAt  sql.NullTime   `json:"expires_at"`
	MediaUrl   sql.NullString `json:"media_url"`
	MediaType  sql.NullString `json:"media_type"`
	GroupID    uuid.NullUUID  `json:"group_id"`
	Reactions  interface{}    `json:"reactions"`
}

func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]ListMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listMessages, arg.SenderID, arg.ReceiverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesRow
	for rows.Next() {
		var i ListMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.ReceiverID,
			&i.Content,
			&i.IsRead,
			&i.CreatedAt,
			&i.ReadAt,
			&i.ExpiresAt,
			&i.MediaUrl,
			&i.MediaType,
			&i.GroupID,
			&i.Reactions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markConversationRead = `-- name: MarkConversationRead :exec
UPDATE messages
SET read_at = NOW()
WHERE receiver_id = $1 AND sender_id = $2 AND read_at IS NULL
`

type MarkConversationReadParams struct {
	ReceiverID uuid.NullUUID `json:"receiver_id"`
	SenderID   uuid.UUID     `json:"sender_id"`
}

func (q *Queries) MarkConversationRead(ctx context.Context, arg MarkConversationReadParams) error {
	_, err := q.db.ExecContext(ctx, markConversationRead, arg.ReceiverID, arg.SenderID)
	return err
}

const markMessageRead = `-- name: MarkMessageRead :one
UPDATE messages
SET read_at = NOW()
WHERE id = $1 AND receiver_id = $2 AND read_at IS NULL
RETURNING id, sender_id, receiver_id, content, is_read, created_at, read_at, expires_at, media_url, media_type, group_id
`

type MarkMessageReadParams struct {
	ID         uuid.UUID     `json:"id"`
	ReceiverID uuid.NullUUID `json:"receiver_id"`
}

func (q *Queries) MarkMessageRead(ctx context.Context, arg MarkMessageReadParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, markMessageRead, arg.ID, arg.ReceiverID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.ReceiverID,
		&i.Content,
		&i.IsRead,
		&i.CreatedAt,
		&i.ReadAt,
		&i.ExpiresAt,
		&i.MediaUrl,
		&i.MediaType,
		&i.GroupID,
	)
	return i, err
}

const saveMessage = `-- name: SaveMessage :one
UPDATE messages
SET expires_at = NULL
WHERE id = $1
RETURNING id, sender_id, receiver_id, content, is_read, created_at, read_at, expires_at, media_url, media_type, group_id
`

func (q *Queries) SaveMessage(ctx context.Context, id uuid.UUID) (Message, error) {
	row := q.db.QueryRowContext(ctx, saveMessage, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.ReceiverID,
		&i.Content,
		&i.IsRead,
		&i.CreatedAt,
		&i.ReadAt,
		&i.ExpiresAt,
		&i.MediaUrl,
		&i.MediaType,
		&i.GroupID,
	)
	return i, err
}

const updateMessage = `-- name: UpdateMessage :one
UPDATE messages
SET content = $3, media_url = $4, media_type = $5
WHERE id = $1 AND sender_id = $2
RETURNING id, sender_id, receiver_id, content, is_read, created_at, read_at, expires_at, media_url, media_type, group_id
`

type UpdateMessageParams struct {
	ID        uuid.UUID      `json:"id"`
	SenderID  uuid.UUID      `json:"sender_id"`
	Content   string         `json:"content"`
	MediaUrl  sql.NullString `json:"media_url"`
	MediaType sql.NullString `json:"media_type"`
}

func (q *Queries) UpdateMessage(ctx context.Context, arg UpdateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, updateMessage,
		arg.ID,
		arg.SenderID,
		arg.Content,
		arg.MediaUrl,
		arg.MediaType,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.ReceiverID,
		&i.Content,
		&i.IsRead,
		&i.CreatedAt,
		&i.ReadAt,
		&i.ExpiresAt,
		&i.MediaUrl,
		&i.MediaType,
		&i.GroupID,
	)
	return i, err
}
