// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: moderation.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getUserTrustScore = `-- name: GetUserTrustScore :one
SELECT trust_score FROM users WHERE id = $1
`

func (q *Queries) GetUserTrustScore(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, getUserTrustScore, id)
	var trust_score int32
	err := row.Scan(&trust_score)
	return trust_score, err
}

const listAllComments = `-- name: ListAllComments :many
SELECT 
    'post' as source,
    pc.id,
    pc.post_id as target_id,
    pc.user_id,
    u.username,
    pc.content,
    pc.is_flagged,
    pc.created_at
FROM post_comments pc
JOIN users u ON pc.user_id = u.id
UNION ALL
SELECT 
    'reel' as source,
    rc.id,
    rc.reel_id as target_id,
    rc.user_id,
    u.username,
    rc.content,
    rc.is_flagged,
    rc.created_at
FROM reel_comments rc
JOIN users u ON rc.user_id = u.id
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAllCommentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAllCommentsRow struct {
	Source    string    `json:"source"`
	ID        uuid.UUID `json:"id"`
	TargetID  uuid.UUID `json:"target_id"`
	UserID    uuid.UUID `json:"user_id"`
	Username  string    `json:"username"`
	Content   string    `json:"content"`
	IsFlagged bool      `json:"is_flagged"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) ListAllComments(ctx context.Context, arg ListAllCommentsParams) ([]ListAllCommentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllComments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllCommentsRow
	for rows.Next() {
		var i ListAllCommentsRow
		if err := rows.Scan(
			&i.Source,
			&i.ID,
			&i.TargetID,
			&i.UserID,
			&i.Username,
			&i.Content,
			&i.IsFlagged,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePostCommentFlag = `-- name: UpdatePostCommentFlag :exec
UPDATE post_comments SET is_flagged = $2 WHERE id = $1
`

type UpdatePostCommentFlagParams struct {
	ID        uuid.UUID `json:"id"`
	IsFlagged bool      `json:"is_flagged"`
}

func (q *Queries) UpdatePostCommentFlag(ctx context.Context, arg UpdatePostCommentFlagParams) error {
	_, err := q.db.ExecContext(ctx, updatePostCommentFlag, arg.ID, arg.IsFlagged)
	return err
}

const updateReelCommentFlag = `-- name: UpdateReelCommentFlag :exec
UPDATE reel_comments SET is_flagged = $2 WHERE id = $1
`

type UpdateReelCommentFlagParams struct {
	ID        uuid.UUID `json:"id"`
	IsFlagged bool      `json:"is_flagged"`
}

func (q *Queries) UpdateReelCommentFlag(ctx context.Context, arg UpdateReelCommentFlagParams) error {
	_, err := q.db.ExecContext(ctx, updateReelCommentFlag, arg.ID, arg.IsFlagged)
	return err
}

const updateUserTrustScore = `-- name: UpdateUserTrustScore :exec
UPDATE users SET trust_score = trust_score + $2 WHERE id = $1
`

type UpdateUserTrustScoreParams struct {
	ID         uuid.UUID `json:"id"`
	TrustScore int32     `json:"trust_score"`
}

func (q *Queries) UpdateUserTrustScore(ctx context.Context, arg UpdateUserTrustScoreParams) error {
	_, err := q.db.ExecContext(ctx, updateUserTrustScore, arg.ID, arg.TrustScore)
	return err
}
