// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type ConnectionStatus string

const (
	ConnectionStatusPending  ConnectionStatus = "pending"
	ConnectionStatusAccepted ConnectionStatus = "accepted"
	ConnectionStatusBlocked  ConnectionStatus = "blocked"
)

func (e *ConnectionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ConnectionStatus(s)
	case string:
		*e = ConnectionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ConnectionStatus: %T", src)
	}
	return nil
}

type NullConnectionStatus struct {
	ConnectionStatus ConnectionStatus `json:"connection_status"`
	Valid            bool             `json:"valid"` // Valid is true if ConnectionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullConnectionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ConnectionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ConnectionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullConnectionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ConnectionStatus), nil
}

type NotificationType string

const (
	NotificationTypeConnectionRequest  NotificationType = "connection_request"
	NotificationTypeConnectionAccepted NotificationType = "connection_accepted"
	NotificationTypeCrossingDetected   NotificationType = "crossing_detected"
	NotificationTypeMessageReceived    NotificationType = "message_received"
	NotificationTypeStoryReaction      NotificationType = "story_reaction"
)

func (e *NotificationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationType(s)
	case string:
		*e = NotificationType(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationType: %T", src)
	}
	return nil
}

type NullNotificationType struct {
	NotificationType NotificationType `json:"notification_type"`
	Valid            bool             `json:"valid"` // Valid is true if NotificationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationType) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationType), nil
}

type ReportReason string

const (
	ReportReasonSpam          ReportReason = "spam"
	ReportReasonAbuse         ReportReason = "abuse"
	ReportReasonInappropriate ReportReason = "inappropriate"
	ReportReasonOther         ReportReason = "other"
)

func (e *ReportReason) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReportReason(s)
	case string:
		*e = ReportReason(s)
	default:
		return fmt.Errorf("unsupported scan type for ReportReason: %T", src)
	}
	return nil
}

type NullReportReason struct {
	ReportReason ReportReason `json:"report_reason"`
	Valid        bool         `json:"valid"` // Valid is true if ReportReason is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReportReason) Scan(value interface{}) error {
	if value == nil {
		ns.ReportReason, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReportReason.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReportReason) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReportReason), nil
}

type StoryAvailability string

const (
	StoryAvailabilityPublic       StoryAvailability = "public"
	StoryAvailabilityConnections  StoryAvailability = "connections"
	StoryAvailabilityCloseFriends StoryAvailability = "close_friends"
)

func (e *StoryAvailability) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StoryAvailability(s)
	case string:
		*e = StoryAvailability(s)
	default:
		return fmt.Errorf("unsupported scan type for StoryAvailability: %T", src)
	}
	return nil
}

type NullStoryAvailability struct {
	StoryAvailability StoryAvailability `json:"story_availability"`
	Valid             bool              `json:"valid"` // Valid is true if StoryAvailability is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStoryAvailability) Scan(value interface{}) error {
	if value == nil {
		ns.StoryAvailability, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StoryAvailability.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStoryAvailability) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StoryAvailability), nil
}

type UserRole string

const (
	UserRoleUser      UserRole = "user"
	UserRoleModerator UserRole = "moderator"
	UserRoleAdmin     UserRole = "admin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type ArchivedStory struct {
	ID                uuid.UUID      `json:"id"`
	UserID            uuid.UUID      `json:"user_id"`
	StoryID           uuid.UUID      `json:"story_id"`
	MediaUrl          string         `json:"media_url"`
	MediaType         string         `json:"media_type"`
	Caption           sql.NullString `json:"caption"`
	Geohash           string         `json:"geohash"`
	Geom              interface{}    `json:"geom"`
	IsAnonymous       sql.NullBool   `json:"is_anonymous"`
	ShowLocation      sql.NullBool   `json:"show_location"`
	OriginalCreatedAt time.Time      `json:"original_created_at"`
	ArchivedAt        sql.NullTime   `json:"archived_at"`
	CreatedAt         sql.NullTime   `json:"created_at"`
}

type BlockedUser struct {
	ID        uuid.UUID    `json:"id"`
	BlockerID uuid.UUID    `json:"blocker_id"`
	BlockedID uuid.UUID    `json:"blocked_id"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Connection struct {
	RequesterID uuid.UUID        `json:"requester_id"`
	TargetID    uuid.UUID        `json:"target_id"`
	Status      ConnectionStatus `json:"status"`
	CreatedAt   time.Time        `json:"created_at"`
	UpdatedAt   time.Time        `json:"updated_at"`
}

type Crossing struct {
	ID             uuid.UUID `json:"id"`
	UserID1        uuid.UUID `json:"user_id_1"`
	UserID2        uuid.UUID `json:"user_id_2"`
	LocationCenter string    `json:"location_center"`
	OccurredAt     time.Time `json:"occurred_at"`
	CreatedAt      time.Time `json:"created_at"`
}

type Group struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedBy   uuid.UUID      `json:"created_by"`
	CreatedAt   time.Time      `json:"created_at"`
	ImageUrl    sql.NullString `json:"image_url"`
}

type GroupMember struct {
	GroupID  uuid.UUID `json:"group_id"`
	UserID   uuid.UUID `json:"user_id"`
	Role     string    `json:"role"`
	JoinedAt time.Time `json:"joined_at"`
}

type Location struct {
	ID         uuid.UUID   `json:"id"`
	UserID     uuid.UUID   `json:"user_id"`
	Geohash    string      `json:"geohash"`
	Geom       interface{} `json:"geom"`
	TimeBucket time.Time   `json:"time_bucket"`
	CreatedAt  time.Time   `json:"created_at"`
	ExpiresAt  time.Time   `json:"expires_at"`
}

type Message struct {
	ID         uuid.UUID      `json:"id"`
	SenderID   uuid.UUID      `json:"sender_id"`
	ReceiverID uuid.NullUUID  `json:"receiver_id"`
	Content    string         `json:"content"`
	IsRead     bool           `json:"is_read"`
	CreatedAt  time.Time      `json:"created_at"`
	ReadAt     sql.NullTime   `json:"read_at"`
	ExpiresAt  sql.NullTime   `json:"expires_at"`
	MediaUrl   sql.NullString `json:"media_url"`
	MediaType  sql.NullString `json:"media_type"`
	GroupID    uuid.NullUUID  `json:"group_id"`
}

type MessageReaction struct {
	ID        uuid.UUID `json:"id"`
	MessageID uuid.UUID `json:"message_id"`
	UserID    uuid.UUID `json:"user_id"`
	Emoji     string    `json:"emoji"`
	CreatedAt time.Time `json:"created_at"`
}

type Notification struct {
	ID                uuid.UUID        `json:"id"`
	UserID            uuid.UUID        `json:"user_id"`
	Type              NotificationType `json:"type"`
	Title             string           `json:"title"`
	Message           string           `json:"message"`
	RelatedUserID     uuid.NullUUID    `json:"related_user_id"`
	RelatedStoryID    uuid.NullUUID    `json:"related_story_id"`
	RelatedCrossingID uuid.NullUUID    `json:"related_crossing_id"`
	IsRead            bool             `json:"is_read"`
	CreatedAt         time.Time        `json:"created_at"`
}

type PrivacySetting struct {
	UserID           uuid.UUID      `json:"user_id"`
	WhoCanMessage    sql.NullString `json:"who_can_message"`
	WhoCanSeeStories sql.NullString `json:"who_can_see_stories"`
	ShowLocation     sql.NullBool   `json:"show_location"`
	CreatedAt        sql.NullTime   `json:"created_at"`
	UpdatedAt        sql.NullTime   `json:"updated_at"`
}

type ProfileView struct {
	ID           uuid.UUID `json:"id"`
	ViewerID     uuid.UUID `json:"viewer_id"`
	ViewedUserID uuid.UUID `json:"viewed_user_id"`
	ViewedAt     time.Time `json:"viewed_at"`
}

type Report struct {
	ID            uuid.UUID      `json:"id"`
	ReporterID    uuid.UUID      `json:"reporter_id"`
	TargetUserID  uuid.NullUUID  `json:"target_user_id"`
	TargetStoryID uuid.NullUUID  `json:"target_story_id"`
	Reason        ReportReason   `json:"reason"`
	Description   sql.NullString `json:"description"`
	IsResolved    bool           `json:"is_resolved"`
	CreatedAt     time.Time      `json:"created_at"`
}

type Session struct {
	ID           uuid.UUID `json:"id"`
	UserID       uuid.UUID `json:"user_id"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type Story struct {
	ID           uuid.UUID         `json:"id"`
	UserID       uuid.UUID         `json:"user_id"`
	MediaUrl     string            `json:"media_url"`
	MediaType    string            `json:"media_type"`
	ThumbnailUrl sql.NullString    `json:"thumbnail_url"`
	Caption      sql.NullString    `json:"caption"`
	Geohash      string            `json:"geohash"`
	Geom         interface{}       `json:"geom"`
	Visibility   StoryAvailability `json:"visibility"`
	ExpiresAt    time.Time         `json:"expires_at"`
	CreatedAt    time.Time         `json:"created_at"`
	IsAnonymous  bool              `json:"is_anonymous"`
	IsPremium    sql.NullBool      `json:"is_premium"`
	ShowLocation bool              `json:"show_location"`
}

type StoryMention struct {
	ID              uuid.UUID `json:"id"`
	StoryID         uuid.UUID `json:"story_id"`
	MentionedUserID uuid.UUID `json:"mentioned_user_id"`
	CreatedAt       time.Time `json:"created_at"`
}

type StoryReaction struct {
	ID        uuid.UUID `json:"id"`
	StoryID   uuid.UUID `json:"story_id"`
	UserID    uuid.UUID `json:"user_id"`
	Emoji     string    `json:"emoji"`
	CreatedAt time.Time `json:"created_at"`
}

type StoryView struct {
	ID        uuid.UUID `json:"id"`
	StoryID   uuid.UUID `json:"story_id"`
	UserID    uuid.UUID `json:"user_id"`
	ViewedAt  time.Time `json:"viewed_at"`
	ViewCount int32     `json:"view_count"`
}

type User struct {
	ID                     uuid.UUID       `json:"id"`
	Phone                  string          `json:"phone"`
	PasswordHash           string          `json:"password_hash"`
	Username               string          `json:"username"`
	FullName               string          `json:"full_name"`
	AvatarUrl              sql.NullString  `json:"avatar_url"`
	Bio                    sql.NullString  `json:"bio"`
	Role                   UserRole        `json:"role"`
	TrustLevel             int32           `json:"trust_level"`
	IsVerified             bool            `json:"is_verified"`
	IsShadowBanned         bool            `json:"is_shadow_banned"`
	LastActiveAt           sql.NullTime    `json:"last_active_at"`
	CreatedAt              time.Time       `json:"created_at"`
	IsGhostMode            bool            `json:"is_ghost_mode"`
	ActivityStreak         sql.NullInt32   `json:"activity_streak"`
	StreakUpdatedAt        sql.NullTime    `json:"streak_updated_at"`
	IsPremium              sql.NullBool    `json:"is_premium"`
	StreakFreezesRemaining int32           `json:"streak_freezes_remaining"`
	BoostExpiresAt         sql.NullTime    `json:"boost_expires_at"`
	BannerUrl              sql.NullString  `json:"banner_url"`
	Theme                  sql.NullString  `json:"theme"`
	ProfileVisibility      sql.NullString  `json:"profile_visibility"`
	Email                  sql.NullString  `json:"email"`
	WebsiteUrl             sql.NullString  `json:"website_url"`
	Links                  json.RawMessage `json:"links"`
	GoogleID               sql.NullString  `json:"google_id"`
	PasswordResetToken     sql.NullString  `json:"password_reset_token"`
	PasswordResetExpiresAt sql.NullTime    `json:"password_reset_expires_at"`
	GhostModeExpiresAt     sql.NullTime    `json:"ghost_mode_expires_at"`
}
