// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT COUNT(*) FROM notifications
WHERE user_id = $1 AND is_read = false
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnreadNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (
  user_id,
  type,
  title,
  message,
  related_user_id,
  related_story_id,
  related_crossing_id
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
) RETURNING id, user_id, type, title, message, related_user_id, related_story_id, related_crossing_id, is_read, created_at
`

type CreateNotificationParams struct {
	UserID            uuid.UUID        `json:"user_id"`
	Type              NotificationType `json:"type"`
	Title             string           `json:"title"`
	Message           string           `json:"message"`
	RelatedUserID     uuid.NullUUID    `json:"related_user_id"`
	RelatedStoryID    uuid.NullUUID    `json:"related_story_id"`
	RelatedCrossingID uuid.NullUUID    `json:"related_crossing_id"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, createNotification,
		arg.UserID,
		arg.Type,
		arg.Title,
		arg.Message,
		arg.RelatedUserID,
		arg.RelatedStoryID,
		arg.RelatedCrossingID,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Message,
		&i.RelatedUserID,
		&i.RelatedStoryID,
		&i.RelatedCrossingID,
		&i.IsRead,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOldNotifications = `-- name: DeleteOldNotifications :exec
DELETE FROM notifications
WHERE created_at < NOW() - INTERVAL '30 days'
`

// Delete notifications older than 30 days
func (q *Queries) DeleteOldNotifications(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteOldNotifications)
	return err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, user_id, type, title, message, related_user_id, related_story_id, related_crossing_id, is_read, created_at FROM notifications
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListNotificationsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, listNotifications, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Message,
			&i.RelatedUserID,
			&i.RelatedStoryID,
			&i.RelatedCrossingID,
			&i.IsRead,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsAsRead = `-- name: MarkAllNotificationsAsRead :exec
UPDATE notifications
SET is_read = true
WHERE user_id = $1 AND is_read = false
`

func (q *Queries) MarkAllNotificationsAsRead(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markAllNotificationsAsRead, userID)
	return err
}

const markNotificationAsRead = `-- name: MarkNotificationAsRead :one
UPDATE notifications
SET is_read = true
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, type, title, message, related_user_id, related_story_id, related_crossing_id, is_read, created_at
`

type MarkNotificationAsReadParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) MarkNotificationAsRead(ctx context.Context, arg MarkNotificationAsReadParams) (Notification, error) {
	row := q.db.QueryRowContext(ctx, markNotificationAsRead, arg.ID, arg.UserID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Message,
		&i.RelatedUserID,
		&i.RelatedStoryID,
		&i.RelatedCrossingID,
		&i.IsRead,
		&i.CreatedAt,
	)
	return i, err
}
