// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: post.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const adminDeletePostComment = `-- name: AdminDeletePostComment :one
DELETE FROM post_comments WHERE id = $1
RETURNING post_id
`

func (q *Queries) AdminDeletePostComment(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, adminDeletePostComment, id)
	var post_id uuid.UUID
	err := row.Scan(&post_id)
	return post_id, err
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (user_id, media_url, media_type, caption, body_text, location_name, geohash, geom)
VALUES (
    $1, $2, $3,
    $4, $5, $6, $7,

    CASE WHEN $8::boolean
         THEN ST_SetSRID(ST_MakePoint($9::float8, $10::float8), 4326)
         ELSE NULL END
)
RETURNING id, user_id, media_url, media_type, caption, location_name, geohash, geom, likes_count, comments_count, created_at, updated_at, body_text, shares_count,
    CASE WHEN geom IS NOT NULL THEN ST_Y(geom::geometry) ELSE NULL END as lat_out,
    CASE WHEN geom IS NOT NULL THEN ST_X(geom::geometry) ELSE NULL END as lng_out
`

type CreatePostParams struct {
	UserID       uuid.UUID      `json:"user_id"`
	MediaUrl     string         `json:"media_url"`
	MediaType    string         `json:"media_type"`
	Caption      sql.NullString `json:"caption"`
	BodyText     sql.NullString `json:"body_text"`
	LocationName sql.NullString `json:"location_name"`
	Geohash      sql.NullString `json:"geohash"`
	HasLocation  bool           `json:"has_location"`
	Lng          float64        `json:"lng"`
	Lat          float64        `json:"lat"`
}

type CreatePostRow struct {
	ID            uuid.UUID      `json:"id"`
	UserID        uuid.UUID      `json:"user_id"`
	MediaUrl      string         `json:"media_url"`
	MediaType     string         `json:"media_type"`
	Caption       sql.NullString `json:"caption"`
	LocationName  sql.NullString `json:"location_name"`
	Geohash       sql.NullString `json:"geohash"`
	Geom          interface{}    `json:"geom"`
	LikesCount    int32          `json:"likes_count"`
	CommentsCount int32          `json:"comments_count"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
	BodyText      sql.NullString `json:"body_text"`
	SharesCount   int32          `json:"shares_count"`
	LatOut        interface{}    `json:"lat_out"`
	LngOut        interface{}    `json:"lng_out"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (CreatePostRow, error) {
	row := q.db.QueryRowContext(ctx, createPost,
		arg.UserID,
		arg.MediaUrl,
		arg.MediaType,
		arg.Caption,
		arg.BodyText,
		arg.LocationName,
		arg.Geohash,
		arg.HasLocation,
		arg.Lng,
		arg.Lat,
	)
	var i CreatePostRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MediaUrl,
		&i.MediaType,
		&i.Caption,
		&i.LocationName,
		&i.Geohash,
		&i.Geom,
		&i.LikesCount,
		&i.CommentsCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BodyText,
		&i.SharesCount,
		&i.LatOut,
		&i.LngOut,
	)
	return i, err
}

const createPostComment = `-- name: CreatePostComment :one
INSERT INTO post_comments (post_id, user_id, content, is_flagged)
VALUES ($1, $2, $3, $4)
RETURNING id, post_id, user_id, content, created_at, is_flagged
`

type CreatePostCommentParams struct {
	PostID    uuid.UUID `json:"post_id"`
	UserID    uuid.UUID `json:"user_id"`
	Content   string    `json:"content"`
	IsFlagged bool      `json:"is_flagged"`
}

func (q *Queries) CreatePostComment(ctx context.Context, arg CreatePostCommentParams) (PostComment, error) {
	row := q.db.QueryRowContext(ctx, createPostComment,
		arg.PostID,
		arg.UserID,
		arg.Content,
		arg.IsFlagged,
	)
	var i PostComment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
		&i.IsFlagged,
	)
	return i, err
}

const decrementPostComments = `-- name: DecrementPostComments :exec
UPDATE posts SET comments_count = GREATEST(0, comments_count - 1) WHERE id = $1
`

func (q *Queries) DecrementPostComments(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, decrementPostComments, id)
	return err
}

const decrementPostLikes = `-- name: DecrementPostLikes :exec
UPDATE posts SET likes_count = GREATEST(0, likes_count - 1) WHERE id = $1
`

func (q *Queries) DecrementPostLikes(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, decrementPostLikes, id)
	return err
}

const deletePost = `-- name: DeletePost :exec
DELETE FROM posts WHERE id = $1 AND user_id = $2
`

type DeletePostParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeletePost(ctx context.Context, arg DeletePostParams) error {
	_, err := q.db.ExecContext(ctx, deletePost, arg.ID, arg.UserID)
	return err
}

const deletePostComment = `-- name: DeletePostComment :one
DELETE FROM post_comments WHERE id = $1 AND user_id = $2
RETURNING post_id
`

type DeletePostCommentParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeletePostComment(ctx context.Context, arg DeletePostCommentParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, deletePostComment, arg.ID, arg.UserID)
	var post_id uuid.UUID
	err := row.Scan(&post_id)
	return post_id, err
}

const getPostComment = `-- name: GetPostComment :one
SELECT id, post_id, user_id, content, created_at, is_flagged FROM post_comments WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPostComment(ctx context.Context, id uuid.UUID) (PostComment, error) {
	row := q.db.QueryRowContext(ctx, getPostComment, id)
	var i PostComment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
		&i.IsFlagged,
	)
	return i, err
}

const incrementPostComments = `-- name: IncrementPostComments :exec
UPDATE posts SET comments_count = comments_count + 1 WHERE id = $1
`

func (q *Queries) IncrementPostComments(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, incrementPostComments, id)
	return err
}

const incrementPostLikes = `-- name: IncrementPostLikes :exec
UPDATE posts SET likes_count = likes_count + 1 WHERE id = $1
`

func (q *Queries) IncrementPostLikes(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, incrementPostLikes, id)
	return err
}

const incrementPostShares = `-- name: IncrementPostShares :exec
UPDATE posts SET shares_count = shares_count + 1 WHERE id = $1
`

func (q *Queries) IncrementPostShares(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, incrementPostShares, id)
	return err
}

const likePost = `-- name: LikePost :one
INSERT INTO post_likes (post_id, user_id) VALUES ($1, $2)
ON CONFLICT (post_id, user_id) DO NOTHING
RETURNING id, post_id, user_id, created_at
`

type LikePostParams struct {
	PostID uuid.UUID `json:"post_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) LikePost(ctx context.Context, arg LikePostParams) (PostLike, error) {
	row := q.db.QueryRowContext(ctx, likePost, arg.PostID, arg.UserID)
	var i PostLike
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const listConnectionsPosts = `-- name: ListConnectionsPosts :many
SELECT p.id, p.user_id, p.media_url, p.media_type, p.caption, p.location_name,
       p.likes_count, p.comments_count, p.shares_count, p.created_at, p.updated_at,

       u.username, u.full_name, u.avatar_url,
       CASE WHEN p.geom IS NOT NULL THEN ST_Y(p.geom::geometry) ELSE NULL END as lat_out,
       CASE WHEN p.geom IS NOT NULL THEN ST_X(p.geom::geometry) ELSE NULL END as lng_out,
       EXISTS(SELECT 1 FROM post_likes pl WHERE pl.post_id = p.id AND pl.user_id = $1) as liked_by_viewer
FROM posts p
JOIN users u ON p.user_id = u.id
LEFT JOIN connections c ON
    (c.requester_id = $1 AND c.target_id = p.user_id) OR
    (c.target_id = $1 AND c.requester_id = p.user_id)
WHERE (p.user_id = $1 OR (c.status = 'accepted' AND u.is_shadow_banned = false))
    AND NOT EXISTS (
        SELECT 1 FROM blocked_users bu
        WHERE (bu.blocker_id = $1 AND bu.blocked_id = p.user_id)
           OR (bu.blocker_id = p.user_id AND bu.blocked_id = $1)
    )
ORDER BY p.created_at DESC
LIMIT $3 OFFSET $2
`

type ListConnectionsPostsParams struct {
	ViewerID uuid.UUID `json:"viewer_id"`
	Off      int32     `json:"off"`
	Lim      int32     `json:"lim"`
}

type ListConnectionsPostsRow struct {
	ID            uuid.UUID      `json:"id"`
	UserID        uuid.UUID      `json:"user_id"`
	MediaUrl      string         `json:"media_url"`
	MediaType     string         `json:"media_type"`
	Caption       sql.NullString `json:"caption"`
	LocationName  sql.NullString `json:"location_name"`
	LikesCount    int32          `json:"likes_count"`
	CommentsCount int32          `json:"comments_count"`
	SharesCount   int32          `json:"shares_count"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
	Username      string         `json:"username"`
	FullName      string         `json:"full_name"`
	AvatarUrl     sql.NullString `json:"avatar_url"`
	LatOut        interface{}    `json:"lat_out"`
	LngOut        interface{}    `json:"lng_out"`
	LikedByViewer bool           `json:"liked_by_viewer"`
}

// Get posts from connections AND own posts
func (q *Queries) ListConnectionsPosts(ctx context.Context, arg ListConnectionsPostsParams) ([]ListConnectionsPostsRow, error) {
	rows, err := q.db.QueryContext(ctx, listConnectionsPosts, arg.ViewerID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConnectionsPostsRow
	for rows.Next() {
		var i ListConnectionsPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MediaUrl,
			&i.MediaType,
			&i.Caption,
			&i.LocationName,
			&i.LikesCount,
			&i.CommentsCount,
			&i.SharesCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.FullName,
			&i.AvatarUrl,
			&i.LatOut,
			&i.LngOut,
			&i.LikedByViewer,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostComments = `-- name: ListPostComments :many
SELECT pc.id, pc.post_id, pc.user_id, pc.content, pc.created_at,
       u.username, u.full_name, u.avatar_url
FROM post_comments pc
JOIN users u ON pc.user_id = u.id
WHERE pc.post_id = $1
ORDER BY pc.created_at ASC
LIMIT 20
`

type ListPostCommentsRow struct {
	ID        uuid.UUID      `json:"id"`
	PostID    uuid.UUID      `json:"post_id"`
	UserID    uuid.UUID      `json:"user_id"`
	Content   string         `json:"content"`
	CreatedAt time.Time      `json:"created_at"`
	Username  string         `json:"username"`
	FullName  string         `json:"full_name"`
	AvatarUrl sql.NullString `json:"avatar_url"`
}

func (q *Queries) ListPostComments(ctx context.Context, postID uuid.UUID) ([]ListPostCommentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPostComments, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostCommentsRow
	for rows.Next() {
		var i ListPostCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.UserID,
			&i.Content,
			&i.CreatedAt,
			&i.Username,
			&i.FullName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostsByUserID = `-- name: ListPostsByUserID :many
SELECT p.id, p.user_id, p.media_url, p.media_type, p.caption, p.location_name,
       p.likes_count, p.comments_count, p.shares_count, p.created_at, p.updated_at,

       u.username, u.full_name, u.avatar_url,
       CASE WHEN p.geom IS NOT NULL THEN ST_Y(p.geom::geometry) ELSE NULL END as lat_out,
       CASE WHEN p.geom IS NOT NULL THEN ST_X(p.geom::geometry) ELSE NULL END as lng_out,
       EXISTS(SELECT 1 FROM post_likes pl WHERE pl.post_id = p.id AND pl.user_id = $1) as liked_by_viewer
FROM posts p
JOIN users u ON p.user_id = u.id
WHERE p.user_id = $2
ORDER BY p.created_at DESC
LIMIT $4 OFFSET $3
`

type ListPostsByUserIDParams struct {
	ViewerID uuid.UUID `json:"viewer_id"`
	UserID   uuid.UUID `json:"user_id"`
	Off      int32     `json:"off"`
	Lim      int32     `json:"lim"`
}

type ListPostsByUserIDRow struct {
	ID            uuid.UUID      `json:"id"`
	UserID        uuid.UUID      `json:"user_id"`
	MediaUrl      string         `json:"media_url"`
	MediaType     string         `json:"media_type"`
	Caption       sql.NullString `json:"caption"`
	LocationName  sql.NullString `json:"location_name"`
	LikesCount    int32          `json:"likes_count"`
	CommentsCount int32          `json:"comments_count"`
	SharesCount   int32          `json:"shares_count"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
	Username      string         `json:"username"`
	FullName      string         `json:"full_name"`
	AvatarUrl     sql.NullString `json:"avatar_url"`
	LatOut        interface{}    `json:"lat_out"`
	LngOut        interface{}    `json:"lng_out"`
	LikedByViewer bool           `json:"liked_by_viewer"`
}

func (q *Queries) ListPostsByUserID(ctx context.Context, arg ListPostsByUserIDParams) ([]ListPostsByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listPostsByUserID,
		arg.ViewerID,
		arg.UserID,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostsByUserIDRow
	for rows.Next() {
		var i ListPostsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MediaUrl,
			&i.MediaType,
			&i.Caption,
			&i.LocationName,
			&i.LikesCount,
			&i.CommentsCount,
			&i.SharesCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.FullName,
			&i.AvatarUrl,
			&i.LatOut,
			&i.LngOut,
			&i.LikedByViewer,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlikePost = `-- name: UnlikePost :exec
DELETE FROM post_likes WHERE post_id = $1 AND user_id = $2
`

type UnlikePostParams struct {
	PostID uuid.UUID `json:"post_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) UnlikePost(ctx context.Context, arg UnlikePostParams) error {
	_, err := q.db.ExecContext(ctx, unlikePost, arg.PostID, arg.UserID)
	return err
}
