// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: privacy.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getPrivacySettings = `-- name: GetPrivacySettings :one
SELECT user_id, who_can_message, who_can_see_stories, show_location, created_at, updated_at FROM privacy_settings WHERE user_id = $1
`

func (q *Queries) GetPrivacySettings(ctx context.Context, userID uuid.UUID) (PrivacySetting, error) {
	row := q.db.QueryRowContext(ctx, getPrivacySettings, userID)
	var i PrivacySetting
	err := row.Scan(
		&i.UserID,
		&i.WhoCanMessage,
		&i.WhoCanSeeStories,
		&i.ShowLocation,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPrivacySettings = `-- name: UpsertPrivacySettings :one
INSERT INTO privacy_settings (
    user_id, who_can_message, who_can_see_stories, show_location
) VALUES (
    $1, $2, $3, $4
) ON CONFLICT (user_id) DO UPDATE
SET 
    who_can_message = EXCLUDED.who_can_message,
    who_can_see_stories = EXCLUDED.who_can_see_stories,
    show_location = EXCLUDED.show_location,
    updated_at = NOW()
RETURNING user_id, who_can_message, who_can_see_stories, show_location, created_at, updated_at
`

type UpsertPrivacySettingsParams struct {
	UserID           uuid.UUID      `json:"user_id"`
	WhoCanMessage    sql.NullString `json:"who_can_message"`
	WhoCanSeeStories sql.NullString `json:"who_can_see_stories"`
	ShowLocation     sql.NullBool   `json:"show_location"`
}

func (q *Queries) UpsertPrivacySettings(ctx context.Context, arg UpsertPrivacySettingsParams) (PrivacySetting, error) {
	row := q.db.QueryRowContext(ctx, upsertPrivacySettings,
		arg.UserID,
		arg.WhoCanMessage,
		arg.WhoCanSeeStories,
		arg.ShowLocation,
	)
	var i PrivacySetting
	err := row.Scan(
		&i.UserID,
		&i.WhoCanMessage,
		&i.WhoCanSeeStories,
		&i.ShowLocation,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
