// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profile_views.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const getMyProfileViews = `-- name: GetMyProfileViews :many
SELECT 
    u.id,
    u.username,
    u.full_name,
    u.avatar_url,
    pv.viewed_at
FROM profile_views pv
JOIN users u ON u.id = pv.viewed_user_id
WHERE pv.viewer_id = $1
ORDER BY pv.viewed_at DESC
LIMIT 50
`

type GetMyProfileViewsRow struct {
	ID        uuid.UUID      `json:"id"`
	Username  string         `json:"username"`
	FullName  string         `json:"full_name"`
	AvatarUrl sql.NullString `json:"avatar_url"`
	ViewedAt  time.Time      `json:"viewed_at"`
}

func (q *Queries) GetMyProfileViews(ctx context.Context, viewerID uuid.UUID) ([]GetMyProfileViewsRow, error) {
	rows, err := q.db.QueryContext(ctx, getMyProfileViews, viewerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMyProfileViewsRow
	for rows.Next() {
		var i GetMyProfileViewsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FullName,
			&i.AvatarUrl,
			&i.ViewedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProfileViewCount = `-- name: GetProfileViewCount :one
SELECT COUNT(DISTINCT viewer_id) as total_views
FROM profile_views
WHERE viewed_user_id = $1
  AND viewed_at >= NOW() - INTERVAL '30 days'
`

func (q *Queries) GetProfileViewCount(ctx context.Context, viewedUserID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getProfileViewCount, viewedUserID)
	var total_views int64
	err := row.Scan(&total_views)
	return total_views, err
}

const getRecentProfileVisitors = `-- name: GetRecentProfileVisitors :many
SELECT 
    u.id,
    u.username,
    u.full_name,
    u.avatar_url,
    pv.viewed_at
FROM profile_views pv
JOIN users u ON u.id = pv.viewer_id
WHERE pv.viewed_user_id = $1
  AND pv.viewed_at >= NOW() - INTERVAL '24 hours'
ORDER BY pv.viewed_at DESC
LIMIT 50
`

type GetRecentProfileVisitorsRow struct {
	ID        uuid.UUID      `json:"id"`
	Username  string         `json:"username"`
	FullName  string         `json:"full_name"`
	AvatarUrl sql.NullString `json:"avatar_url"`
	ViewedAt  time.Time      `json:"viewed_at"`
}

func (q *Queries) GetRecentProfileVisitors(ctx context.Context, viewedUserID uuid.UUID) ([]GetRecentProfileVisitorsRow, error) {
	rows, err := q.db.QueryContext(ctx, getRecentProfileVisitors, viewedUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentProfileVisitorsRow
	for rows.Next() {
		var i GetRecentProfileVisitorsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FullName,
			&i.AvatarUrl,
			&i.ViewedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trackProfileView = `-- name: TrackProfileView :one
INSERT INTO profile_views (viewer_id, viewed_user_id, viewed_at)
VALUES ($1, $2, NOW())
ON CONFLICT (viewer_id, viewed_user_id) DO UPDATE
SET viewed_at = NOW()
RETURNING id, viewer_id, viewed_user_id, viewed_at
`

type TrackProfileViewParams struct {
	ViewerID     uuid.UUID `json:"viewer_id"`
	ViewedUserID uuid.UUID `json:"viewed_user_id"`
}

func (q *Queries) TrackProfileView(ctx context.Context, arg TrackProfileViewParams) (ProfileView, error) {
	row := q.db.QueryRowContext(ctx, trackProfileView, arg.ViewerID, arg.ViewedUserID)
	var i ProfileView
	err := row.Scan(
		&i.ID,
		&i.ViewerID,
		&i.ViewedUserID,
		&i.ViewedAt,
	)
	return i, err
}
