// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	AddGroupMember(ctx context.Context, arg AddGroupMemberParams) (GroupMember, error)
	ArchiveStory(ctx context.Context, arg ArchiveStoryParams) (ArchivedStory, error)
	BanUser(ctx context.Context, arg BanUserParams) (User, error)
	BlockUser(ctx context.Context, arg BlockUserParams) (BlockedUser, error)
	BoostUser(ctx context.Context, arg BoostUserParams) (User, error)
	CheckGroupMembership(ctx context.Context, arg CheckGroupMembershipParams) (bool, error)
	ClearPasswordResetToken(ctx context.Context, id uuid.UUID) error
	CountArchivedStories(ctx context.Context, userID uuid.UUID) (int64, error)
	CountConnectionRequestsToday(ctx context.Context, requesterID uuid.UUID) (int64, error)
	CountCrossingsToday(ctx context.Context, userID1 uuid.UUID) (int64, error)
	CountStoryReactions(ctx context.Context, storyID uuid.UUID) (int64, error)
	CountStoryViews(ctx context.Context, storyID uuid.UUID) (int64, error)
	CountUnreadNotifications(ctx context.Context, userID uuid.UUID) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateConnectionRequest(ctx context.Context, arg CreateConnectionRequestParams) (Connection, error)
	CreateCrossing(ctx context.Context, arg CreateCrossingParams) (Crossing, error)
	CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error)
	CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateMessageReaction(ctx context.Context, arg CreateMessageReactionParams) (MessageReaction, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreateReport(ctx context.Context, arg CreateReportParams) (Report, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateStory(ctx context.Context, arg CreateStoryParams) (CreateStoryRow, error)
	CreateStoryMention(ctx context.Context, arg CreateStoryMentionParams) (StoryMention, error)
	// Story Reactions
	CreateStoryReaction(ctx context.Context, arg CreateStoryReactionParams) (StoryReaction, error)
	// Story Views
	CreateStoryView(ctx context.Context, arg CreateStoryViewParams) (StoryView, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Used for panic mode - deletes all user data
	DeleteAllUserData(ctx context.Context, id uuid.UUID) error
	DeleteArchivedStory(ctx context.Context, arg DeleteArchivedStoryParams) error
	DeleteConnection(ctx context.Context, arg DeleteConnectionParams) error
	DeleteConversation(ctx context.Context, arg DeleteConversationParams) error
	DeleteExpiredLocations(ctx context.Context) error
	DeleteExpiredMessages(ctx context.Context) error
	DeleteExpiredStories(ctx context.Context) error
	DeleteMessage(ctx context.Context, arg DeleteMessageParams) error
	DeleteMessageReaction(ctx context.Context, arg DeleteMessageReactionParams) error
	// Delete messages older than specified days (default: 30 days)
	DeleteOldMessages(ctx context.Context) error
	// Delete notifications older than 30 days
	DeleteOldNotifications(ctx context.Context) error
	// Admin: Delete story
	DeleteStory(ctx context.Context, id uuid.UUID) error
	DeleteStoryMentions(ctx context.Context, storyID uuid.UUID) error
	DeleteStoryReaction(ctx context.Context, arg DeleteStoryReactionParams) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	// Block Logic
	FindPotentialCrossings(ctx context.Context, arg FindPotentialCrossingsParams) ([]FindPotentialCrossingsRow, error)
	GetArchivedStories(ctx context.Context, arg GetArchivedStoriesParams) ([]ArchivedStory, error)
	GetArchivedStory(ctx context.Context, arg GetArchivedStoryParams) (ArchivedStory, error)
	GetBlockedUsers(ctx context.Context, blockerID uuid.UUID) ([]GetBlockedUsersRow, error)
	GetConnection(ctx context.Context, arg GetConnectionParams) (Connection, error)
	// Get stories from connected users (not limited by radius)
	GetConnectionStories(ctx context.Context, userID uuid.UUID) ([]GetConnectionStoriesRow, error)
	GetConversationList(ctx context.Context, receiverID uuid.NullUUID) ([]GetConversationListRow, error)
	GetConversionStats(ctx context.Context) (GetConversionStatsRow, error)
	GetCrossingsForUser(ctx context.Context, userID1 uuid.UUID) ([]Crossing, error)
	GetEngagementStats(ctx context.Context) (GetEngagementStatsRow, error)
	GetGroupByID(ctx context.Context, id uuid.UUID) (Group, error)
	GetGroupMembers(ctx context.Context, groupID uuid.UUID) ([]GetGroupMembersRow, error)
	GetGroupMessages(ctx context.Context, groupID uuid.NullUUID) ([]GetGroupMessagesRow, error)
	GetHeatmapData(ctx context.Context) ([]GetHeatmapDataRow, error)
	GetMessage(ctx context.Context, id uuid.UUID) (Message, error)
	GetMessageReactions(ctx context.Context, messageID uuid.UUID) ([]GetMessageReactionsRow, error)
	GetMyProfileViews(ctx context.Context, viewerID uuid.UUID) ([]GetMyProfileViewsRow, error)
	GetPrivacySettings(ctx context.Context, userID uuid.UUID) (PrivacySetting, error)
	GetProfileViewCount(ctx context.Context, viewedUserID uuid.UUID) (int64, error)
	GetRecentProfileVisitors(ctx context.Context, viewedUserID uuid.UUID) ([]GetRecentProfileVisitorsRow, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	// Get stories within a bounding box for map view
	// AND DATE(u.last_active_at) >= CURRENT_DATE - INTERVAL '1 day'
	GetStoriesInBounds(ctx context.Context, arg GetStoriesInBoundsParams) ([]GetStoriesInBoundsRow, error)
	GetStoriesWithinRadius(ctx context.Context, arg GetStoriesWithinRadiusParams) ([]GetStoriesWithinRadiusRow, error)
	GetStoryByID(ctx context.Context, id uuid.UUID) (GetStoryByIDRow, error)
	GetStoryMentions(ctx context.Context, storyID uuid.UUID) ([]GetStoryMentionsRow, error)
	GetStoryReactions(ctx context.Context, storyID uuid.UUID) ([]GetStoryReactionsRow, error)
	// Admin: Story stats
	GetStoryStats(ctx context.Context) (GetStoryStatsRow, error)
	// Only accessible by story owner
	GetStoryViewers(ctx context.Context, storyID uuid.UUID) ([]GetStoryViewersRow, error)
	GetStreakRetentionStats(ctx context.Context) (GetStreakRetentionStatsRow, error)
	GetSuggestedConnections(ctx context.Context, arg GetSuggestedConnectionsParams) ([]GetSuggestedConnectionsRow, error)
	GetSystemStats(ctx context.Context) (GetSystemStatsRow, error)
	GetUnreadMessageCount(ctx context.Context, receiverID uuid.NullUUID) (int64, error)
	// Get user's activity status and visibility
	GetUserActivityStatus(ctx context.Context, id uuid.UUID) (GetUserActivityStatusRow, error)
	GetUserByEmail(ctx context.Context, email sql.NullString) (User, error)
	GetUserByGoogleID(ctx context.Context, googleID sql.NullString) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByPhone(ctx context.Context, phone string) (User, error)
	GetUserByResetToken(ctx context.Context, passwordResetToken sql.NullString) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserEngagementStats(ctx context.Context, userID uuid.UUID) (GetUserEngagementStatsRow, error)
	GetUserGroups(ctx context.Context, userID uuid.UUID) ([]Group, error)
	GetUserMentions(ctx context.Context, arg GetUserMentionsParams) ([]GetUserMentionsRow, error)
	GetUserProfile(ctx context.Context, id uuid.UUID) (GetUserProfileRow, error)
	HasValidStory(ctx context.Context, userID uuid.UUID) (bool, error)
	IsUserBlocked(ctx context.Context, arg IsUserBlockedParams) (bool, error)
	// Admin: List all stories
	ListAllStories(ctx context.Context, arg ListAllStoriesParams) ([]ListAllStoriesRow, error)
	ListConnections(ctx context.Context, requesterID uuid.UUID) ([]ListConnectionsRow, error)
	ListMessages(ctx context.Context, arg ListMessagesParams) ([]ListMessagesRow, error)
	ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error)
	ListPendingRequests(ctx context.Context, targetID uuid.UUID) ([]ListPendingRequestsRow, error)
	// Admin: List all reports
	ListReports(ctx context.Context, arg ListReportsParams) ([]ListReportsRow, error)
	ListSentConnectionRequests(ctx context.Context, requesterID uuid.UUID) ([]ListSentConnectionRequestsRow, error)
	// Admin Queries
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	MarkAllNotificationsAsRead(ctx context.Context, userID uuid.UUID) error
	MarkConversationRead(ctx context.Context, arg MarkConversationReadParams) error
	MarkMessageRead(ctx context.Context, arg MarkMessageReadParams) (Message, error)
	MarkNotificationAsRead(ctx context.Context, arg MarkNotificationAsReadParams) (Notification, error)
	RemoveGroupMember(ctx context.Context, arg RemoveGroupMemberParams) error
	// Admin: Resolve report
	ResolveReport(ctx context.Context, id uuid.UUID) (Report, error)
	SaveMessage(ctx context.Context, id uuid.UUID) (Message, error)
	SearchUsers(ctx context.Context, query string) ([]SearchUsersRow, error)
	SetPasswordResetToken(ctx context.Context, arg SetPasswordResetTokenParams) (User, error)
	// Privacy Features
	ToggleGhostMode(ctx context.Context, arg ToggleGhostModeParams) (User, error)
	TrackProfileView(ctx context.Context, arg TrackProfileViewParams) (ProfileView, error)
	UnblockUser(ctx context.Context, arg UnblockUserParams) error
	UpdateConnectionStatus(ctx context.Context, arg UpdateConnectionStatusParams) (Connection, error)
	UpdateMessage(ctx context.Context, arg UpdateMessageParams) (Message, error)
	UpdateStory(ctx context.Context, arg UpdateStoryParams) (UpdateStoryRow, error)
	// Updates last_active_at and calculates activity streak
	UpdateUserActivity(ctx context.Context, id uuid.UUID) (User, error)
	UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) (UpdateUserEmailRow, error)
	UpdateUserGoogleID(ctx context.Context, arg UpdateUserGoogleIDParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UpdateUserProfileRow, error)
	UpdateUserTrust(ctx context.Context, arg UpdateUserTrustParams) (User, error)
	UpsertPrivacySettings(ctx context.Context, arg UpsertPrivacySettingsParams) (PrivacySetting, error)
}

var _ Querier = (*Queries)(nil)
