// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reels.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createReel = `-- name: CreateReel :one
INSERT INTO reels (
    user_id, video_url, caption, is_ai_generated, location_name, geohash, geom
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, user_id, video_url, caption, is_ai_generated, location_name, geohash, 
    COALESCE(ST_Y(geom::geometry)::float8, 0.0)::float8 AS lat, COALESCE(ST_X(geom::geometry)::float8, 0.0)::float8 AS lng,
    likes_count, comments_count, shares_count, saves_count, created_at, updated_at
`

type CreateReelParams struct {
	UserID        uuid.UUID      `json:"user_id"`
	VideoUrl      string         `json:"video_url"`
	Caption       sql.NullString `json:"caption"`
	IsAiGenerated bool           `json:"is_ai_generated"`
	LocationName  sql.NullString `json:"location_name"`
	Geohash       sql.NullString `json:"geohash"`
	Geom          interface{}    `json:"geom"`
}

type CreateReelRow struct {
	ID            uuid.UUID      `json:"id"`
	UserID        uuid.UUID      `json:"user_id"`
	VideoUrl      string         `json:"video_url"`
	Caption       sql.NullString `json:"caption"`
	IsAiGenerated bool           `json:"is_ai_generated"`
	LocationName  sql.NullString `json:"location_name"`
	Geohash       sql.NullString `json:"geohash"`
	Lat           float64        `json:"lat"`
	Lng           float64        `json:"lng"`
	LikesCount    int32          `json:"likes_count"`
	CommentsCount int32          `json:"comments_count"`
	SharesCount   int32          `json:"shares_count"`
	SavesCount    int32          `json:"saves_count"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

func (q *Queries) CreateReel(ctx context.Context, arg CreateReelParams) (CreateReelRow, error) {
	row := q.db.QueryRowContext(ctx, createReel,
		arg.UserID,
		arg.VideoUrl,
		arg.Caption,
		arg.IsAiGenerated,
		arg.LocationName,
		arg.Geohash,
		arg.Geom,
	)
	var i CreateReelRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VideoUrl,
		&i.Caption,
		&i.IsAiGenerated,
		&i.LocationName,
		&i.Geohash,
		&i.Lat,
		&i.Lng,
		&i.LikesCount,
		&i.CommentsCount,
		&i.SharesCount,
		&i.SavesCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createReelComment = `-- name: CreateReelComment :one
INSERT INTO reel_comments (reel_id, user_id, content)
VALUES ($1, $2, $3)
RETURNING id, reel_id, user_id, content, created_at
`

type CreateReelCommentParams struct {
	ReelID  uuid.UUID `json:"reel_id"`
	UserID  uuid.UUID `json:"user_id"`
	Content string    `json:"content"`
}

func (q *Queries) CreateReelComment(ctx context.Context, arg CreateReelCommentParams) (ReelComment, error) {
	row := q.db.QueryRowContext(ctx, createReelComment, arg.ReelID, arg.UserID, arg.Content)
	var i ReelComment
	err := row.Scan(
		&i.ID,
		&i.ReelID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const decrementReelLikes = `-- name: DecrementReelLikes :exec
UPDATE reels SET likes_count = likes_count - 1 WHERE id = $1
`

func (q *Queries) DecrementReelLikes(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, decrementReelLikes, id)
	return err
}

const decrementReelSaves = `-- name: DecrementReelSaves :exec
UPDATE reels SET saves_count = saves_count - 1 WHERE id = $1
`

func (q *Queries) DecrementReelSaves(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, decrementReelSaves, id)
	return err
}

const getReel = `-- name: GetReel :one
SELECT id, user_id, video_url, caption, is_ai_generated, location_name, geohash, 
    COALESCE(ST_Y(geom::geometry)::float8, 0.0)::float8 AS lat, COALESCE(ST_X(geom::geometry)::float8, 0.0)::float8 AS lng,
    likes_count, comments_count, shares_count, saves_count, created_at, updated_at 
FROM reels WHERE id = $1 LIMIT 1
`

type GetReelRow struct {
	ID            uuid.UUID      `json:"id"`
	UserID        uuid.UUID      `json:"user_id"`
	VideoUrl      string         `json:"video_url"`
	Caption       sql.NullString `json:"caption"`
	IsAiGenerated bool           `json:"is_ai_generated"`
	LocationName  sql.NullString `json:"location_name"`
	Geohash       sql.NullString `json:"geohash"`
	Lat           float64        `json:"lat"`
	Lng           float64        `json:"lng"`
	LikesCount    int32          `json:"likes_count"`
	CommentsCount int32          `json:"comments_count"`
	SharesCount   int32          `json:"shares_count"`
	SavesCount    int32          `json:"saves_count"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
}

func (q *Queries) GetReel(ctx context.Context, id uuid.UUID) (GetReelRow, error) {
	row := q.db.QueryRowContext(ctx, getReel, id)
	var i GetReelRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VideoUrl,
		&i.Caption,
		&i.IsAiGenerated,
		&i.LocationName,
		&i.Geohash,
		&i.Lat,
		&i.Lng,
		&i.LikesCount,
		&i.CommentsCount,
		&i.SharesCount,
		&i.SavesCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTotalReelsCountToday = `-- name: GetTotalReelsCountToday :one
SELECT COUNT(*) FROM reels WHERE created_at >= CURRENT_DATE
`

func (q *Queries) GetTotalReelsCountToday(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalReelsCountToday)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const incrementReelComments = `-- name: IncrementReelComments :exec
UPDATE reels SET comments_count = comments_count + 1 WHERE id = $1
`

func (q *Queries) IncrementReelComments(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, incrementReelComments, id)
	return err
}

const incrementReelLikes = `-- name: IncrementReelLikes :exec
UPDATE reels SET likes_count = likes_count + 1 WHERE id = $1
`

func (q *Queries) IncrementReelLikes(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, incrementReelLikes, id)
	return err
}

const incrementReelSaves = `-- name: IncrementReelSaves :exec
UPDATE reels SET saves_count = saves_count + 1 WHERE id = $1
`

func (q *Queries) IncrementReelSaves(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, incrementReelSaves, id)
	return err
}

const incrementReelShares = `-- name: IncrementReelShares :exec
UPDATE reels SET shares_count = shares_count + 1 WHERE id = $1
`

func (q *Queries) IncrementReelShares(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, incrementReelShares, id)
	return err
}

const likeReel = `-- name: LikeReel :one
INSERT INTO reel_likes (reel_id, user_id)
VALUES ($1, $2)
ON CONFLICT (reel_id, user_id) DO NOTHING
RETURNING id, reel_id, user_id, created_at
`

type LikeReelParams struct {
	ReelID uuid.UUID `json:"reel_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) LikeReel(ctx context.Context, arg LikeReelParams) (ReelLike, error) {
	row := q.db.QueryRowContext(ctx, likeReel, arg.ReelID, arg.UserID)
	var i ReelLike
	err := row.Scan(
		&i.ID,
		&i.ReelID,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const listNearbyReels = `-- name: ListNearbyReels :many
SELECT 
    r.id, r.user_id, r.video_url, r.caption, r.is_ai_generated, r.location_name, r.geohash,
    COALESCE(ST_Y(r.geom::geometry)::float8, 0.0)::float8 AS lat, COALESCE(ST_X(r.geom::geometry)::float8, 0.0)::float8 AS lng,
    r.likes_count, r.comments_count, r.shares_count, r.saves_count, r.created_at, r.updated_at,
    u.username,
    u.avatar_url,
    ST_Distance(r.geom, ST_SetSRID(ST_MakePoint($3::float, $4::float), 4326)::geography) AS distance_meters,
    EXISTS (SELECT 1 FROM reel_likes rl WHERE rl.reel_id = r.id AND rl.user_id = $5) AS is_liked,
    EXISTS (SELECT 1 FROM reel_saves rs WHERE rs.reel_id = r.id AND rs.user_id = $5) AS is_saved
FROM reels r
JOIN users u ON r.user_id = u.id
WHERE ST_DWithin(r.geom, ST_SetSRID(ST_MakePoint($3::float, $4::float), 4326)::geography, $6::float)
ORDER BY distance_meters ASC
LIMIT $1 OFFSET $2
`

type ListNearbyReelsParams struct {
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
	Lng      float64   `json:"lng"`
	Lat      float64   `json:"lat"`
	ViewerID uuid.UUID `json:"viewer_id"`
	Radius   float64   `json:"radius"`
}

type ListNearbyReelsRow struct {
	ID             uuid.UUID      `json:"id"`
	UserID         uuid.UUID      `json:"user_id"`
	VideoUrl       string         `json:"video_url"`
	Caption        sql.NullString `json:"caption"`
	IsAiGenerated  bool           `json:"is_ai_generated"`
	LocationName   sql.NullString `json:"location_name"`
	Geohash        sql.NullString `json:"geohash"`
	Lat            float64        `json:"lat"`
	Lng            float64        `json:"lng"`
	LikesCount     int32          `json:"likes_count"`
	CommentsCount  int32          `json:"comments_count"`
	SharesCount    int32          `json:"shares_count"`
	SavesCount     int32          `json:"saves_count"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	Username       string         `json:"username"`
	AvatarUrl      sql.NullString `json:"avatar_url"`
	DistanceMeters interface{}    `json:"distance_meters"`
	IsLiked        bool           `json:"is_liked"`
	IsSaved        bool           `json:"is_saved"`
}

func (q *Queries) ListNearbyReels(ctx context.Context, arg ListNearbyReelsParams) ([]ListNearbyReelsRow, error) {
	rows, err := q.db.QueryContext(ctx, listNearbyReels,
		arg.Limit,
		arg.Offset,
		arg.Lng,
		arg.Lat,
		arg.ViewerID,
		arg.Radius,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNearbyReelsRow
	for rows.Next() {
		var i ListNearbyReelsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VideoUrl,
			&i.Caption,
			&i.IsAiGenerated,
			&i.LocationName,
			&i.Geohash,
			&i.Lat,
			&i.Lng,
			&i.LikesCount,
			&i.CommentsCount,
			&i.SharesCount,
			&i.SavesCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.AvatarUrl,
			&i.DistanceMeters,
			&i.IsLiked,
			&i.IsSaved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReelComments = `-- name: ListReelComments :many
SELECT 
    rc.id, rc.reel_id, rc.user_id, rc.content, rc.created_at,
    u.username,
    u.avatar_url
FROM reel_comments rc
JOIN users u ON rc.user_id = u.id
WHERE rc.reel_id = $1
ORDER BY rc.created_at DESC
`

type ListReelCommentsRow struct {
	ID        uuid.UUID      `json:"id"`
	ReelID    uuid.UUID      `json:"reel_id"`
	UserID    uuid.UUID      `json:"user_id"`
	Content   string         `json:"content"`
	CreatedAt time.Time      `json:"created_at"`
	Username  string         `json:"username"`
	AvatarUrl sql.NullString `json:"avatar_url"`
}

func (q *Queries) ListReelComments(ctx context.Context, reelID uuid.UUID) ([]ListReelCommentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listReelComments, reelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReelCommentsRow
	for rows.Next() {
		var i ListReelCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ReelID,
			&i.UserID,
			&i.Content,
			&i.CreatedAt,
			&i.Username,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReelsFeed = `-- name: ListReelsFeed :many
SELECT 
    r.id, r.user_id, r.video_url, r.caption, r.is_ai_generated, r.location_name, r.geohash,
    COALESCE(ST_Y(r.geom::geometry)::float8, 0.0)::float8 AS lat, COALESCE(ST_X(r.geom::geometry)::float8, 0.0)::float8 AS lng,
    r.likes_count, r.comments_count, r.shares_count, r.saves_count, r.created_at, r.updated_at,
    u.username,
    u.avatar_url,
    EXISTS (SELECT 1 FROM reel_likes rl WHERE rl.reel_id = r.id AND rl.user_id = $1) AS is_liked,
    EXISTS (SELECT 1 FROM reel_saves rs WHERE rs.reel_id = r.id AND rs.user_id = $1) AS is_saved
FROM reels r
JOIN users u ON r.user_id = u.id
ORDER BY r.created_at DESC
LIMIT $2 OFFSET $3
`

type ListReelsFeedParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type ListReelsFeedRow struct {
	ID            uuid.UUID      `json:"id"`
	UserID        uuid.UUID      `json:"user_id"`
	VideoUrl      string         `json:"video_url"`
	Caption       sql.NullString `json:"caption"`
	IsAiGenerated bool           `json:"is_ai_generated"`
	LocationName  sql.NullString `json:"location_name"`
	Geohash       sql.NullString `json:"geohash"`
	Lat           float64        `json:"lat"`
	Lng           float64        `json:"lng"`
	LikesCount    int32          `json:"likes_count"`
	CommentsCount int32          `json:"comments_count"`
	SharesCount   int32          `json:"shares_count"`
	SavesCount    int32          `json:"saves_count"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
	Username      string         `json:"username"`
	AvatarUrl     sql.NullString `json:"avatar_url"`
	IsLiked       bool           `json:"is_liked"`
	IsSaved       bool           `json:"is_saved"`
}

func (q *Queries) ListReelsFeed(ctx context.Context, arg ListReelsFeedParams) ([]ListReelsFeedRow, error) {
	rows, err := q.db.QueryContext(ctx, listReelsFeed, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReelsFeedRow
	for rows.Next() {
		var i ListReelsFeedRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VideoUrl,
			&i.Caption,
			&i.IsAiGenerated,
			&i.LocationName,
			&i.Geohash,
			&i.Lat,
			&i.Lng,
			&i.LikesCount,
			&i.CommentsCount,
			&i.SharesCount,
			&i.SavesCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.AvatarUrl,
			&i.IsLiked,
			&i.IsSaved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserReels = `-- name: ListUserReels :many
SELECT 
    r.id, r.user_id, r.video_url, r.caption, r.is_ai_generated, r.location_name, r.geohash,
    COALESCE(ST_Y(r.geom::geometry)::float8, 0.0)::float8 AS lat, COALESCE(ST_X(r.geom::geometry)::float8, 0.0)::float8 AS lng,
    r.likes_count, r.comments_count, r.shares_count, r.saves_count, r.created_at, r.updated_at,
    u.username,
    u.avatar_url,
    EXISTS (SELECT 1 FROM reel_likes rl WHERE rl.reel_id = r.id AND rl.user_id = $3) AS is_liked,
    EXISTS (SELECT 1 FROM reel_saves rs WHERE rs.reel_id = r.id AND rs.user_id = $3) AS is_saved
FROM reels r
JOIN users u ON r.user_id = u.id
WHERE r.user_id = $4
ORDER BY r.created_at DESC
LIMIT $1 OFFSET $2
`

type ListUserReelsParams struct {
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
	ViewerID uuid.UUID `json:"viewer_id"`
	UserID   uuid.UUID `json:"user_id"`
}

type ListUserReelsRow struct {
	ID            uuid.UUID      `json:"id"`
	UserID        uuid.UUID      `json:"user_id"`
	VideoUrl      string         `json:"video_url"`
	Caption       sql.NullString `json:"caption"`
	IsAiGenerated bool           `json:"is_ai_generated"`
	LocationName  sql.NullString `json:"location_name"`
	Geohash       sql.NullString `json:"geohash"`
	Lat           float64        `json:"lat"`
	Lng           float64        `json:"lng"`
	LikesCount    int32          `json:"likes_count"`
	CommentsCount int32          `json:"comments_count"`
	SharesCount   int32          `json:"shares_count"`
	SavesCount    int32          `json:"saves_count"`
	CreatedAt     time.Time      `json:"created_at"`
	UpdatedAt     time.Time      `json:"updated_at"`
	Username      string         `json:"username"`
	AvatarUrl     sql.NullString `json:"avatar_url"`
	IsLiked       bool           `json:"is_liked"`
	IsSaved       bool           `json:"is_saved"`
}

func (q *Queries) ListUserReels(ctx context.Context, arg ListUserReelsParams) ([]ListUserReelsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserReels,
		arg.Limit,
		arg.Offset,
		arg.ViewerID,
		arg.UserID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserReelsRow
	for rows.Next() {
		var i ListUserReelsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VideoUrl,
			&i.Caption,
			&i.IsAiGenerated,
			&i.LocationName,
			&i.Geohash,
			&i.Lat,
			&i.Lng,
			&i.LikesCount,
			&i.CommentsCount,
			&i.SharesCount,
			&i.SavesCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.AvatarUrl,
			&i.IsLiked,
			&i.IsSaved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveReel = `-- name: SaveReel :one
INSERT INTO reel_saves (reel_id, user_id)
VALUES ($1, $2)
ON CONFLICT (reel_id, user_id) DO NOTHING
RETURNING id, reel_id, user_id, created_at
`

type SaveReelParams struct {
	ReelID uuid.UUID `json:"reel_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) SaveReel(ctx context.Context, arg SaveReelParams) (ReelSafe, error) {
	row := q.db.QueryRowContext(ctx, saveReel, arg.ReelID, arg.UserID)
	var i ReelSafe
	err := row.Scan(
		&i.ID,
		&i.ReelID,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const unlikeReel = `-- name: UnlikeReel :exec
DELETE FROM reel_likes WHERE reel_id = $1 AND user_id = $2
`

type UnlikeReelParams struct {
	ReelID uuid.UUID `json:"reel_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) UnlikeReel(ctx context.Context, arg UnlikeReelParams) error {
	_, err := q.db.ExecContext(ctx, unlikeReel, arg.ReelID, arg.UserID)
	return err
}

const unsaveReel = `-- name: UnsaveReel :exec
DELETE FROM reel_saves WHERE reel_id = $1 AND user_id = $2
`

type UnsaveReelParams struct {
	ReelID uuid.UUID `json:"reel_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) UnsaveReel(ctx context.Context, arg UnsaveReelParams) error {
	_, err := q.db.ExecContext(ctx, unsaveReel, arg.ReelID, arg.UserID)
	return err
}
