// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: story_engagement.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countStoryReactions = `-- name: CountStoryReactions :one
SELECT COUNT(*) FROM story_reactions
WHERE story_id = $1
`

func (q *Queries) CountStoryReactions(ctx context.Context, storyID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countStoryReactions, storyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countStoryViews = `-- name: CountStoryViews :one
SELECT COUNT(sv.*) 
FROM story_views sv
JOIN stories s ON sv.story_id = s.id
WHERE sv.story_id = $1 AND sv.user_id != s.user_id
`

func (q *Queries) CountStoryViews(ctx context.Context, storyID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countStoryViews, storyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createStoryReaction = `-- name: CreateStoryReaction :one

INSERT INTO story_reactions (
  story_id,
  user_id,
  emoji
) VALUES (
  $1, $2, $3
) ON CONFLICT (story_id, user_id) DO UPDATE
SET emoji = EXCLUDED.emoji, created_at = now()
RETURNING id, story_id, user_id, emoji, created_at
`

type CreateStoryReactionParams struct {
	StoryID uuid.UUID `json:"story_id"`
	UserID  uuid.UUID `json:"user_id"`
	Emoji   string    `json:"emoji"`
}

// Story Reactions
func (q *Queries) CreateStoryReaction(ctx context.Context, arg CreateStoryReactionParams) (StoryReaction, error) {
	row := q.db.QueryRowContext(ctx, createStoryReaction, arg.StoryID, arg.UserID, arg.Emoji)
	var i StoryReaction
	err := row.Scan(
		&i.ID,
		&i.StoryID,
		&i.UserID,
		&i.Emoji,
		&i.CreatedAt,
	)
	return i, err
}

const createStoryView = `-- name: CreateStoryView :one

INSERT INTO story_views (
  story_id,
  user_id
) VALUES (
  $1, $2
) ON CONFLICT (story_id, user_id) DO UPDATE
SET viewed_at = story_views.viewed_at
RETURNING id, story_id, user_id, viewed_at, view_count
`

type CreateStoryViewParams struct {
	StoryID uuid.UUID `json:"story_id"`
	UserID  uuid.UUID `json:"user_id"`
}

// Story Views
func (q *Queries) CreateStoryView(ctx context.Context, arg CreateStoryViewParams) (StoryView, error) {
	row := q.db.QueryRowContext(ctx, createStoryView, arg.StoryID, arg.UserID)
	var i StoryView
	err := row.Scan(
		&i.ID,
		&i.StoryID,
		&i.UserID,
		&i.ViewedAt,
		&i.ViewCount,
	)
	return i, err
}

const deleteStoryReaction = `-- name: DeleteStoryReaction :exec
DELETE FROM story_reactions
WHERE story_id = $1 AND user_id = $2
`

type DeleteStoryReactionParams struct {
	StoryID uuid.UUID `json:"story_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteStoryReaction(ctx context.Context, arg DeleteStoryReactionParams) error {
	_, err := q.db.ExecContext(ctx, deleteStoryReaction, arg.StoryID, arg.UserID)
	return err
}

const getStoryReactions = `-- name: GetStoryReactions :many
SELECT sr.id, sr.story_id, sr.user_id, sr.emoji, sr.created_at, u.username, u.avatar_url
FROM story_reactions sr
JOIN users u ON sr.user_id = u.id
WHERE sr.story_id = $1
ORDER BY sr.created_at DESC
`

type GetStoryReactionsRow struct {
	ID        uuid.UUID      `json:"id"`
	StoryID   uuid.UUID      `json:"story_id"`
	UserID    uuid.UUID      `json:"user_id"`
	Emoji     string         `json:"emoji"`
	CreatedAt time.Time      `json:"created_at"`
	Username  string         `json:"username"`
	AvatarUrl sql.NullString `json:"avatar_url"`
}

func (q *Queries) GetStoryReactions(ctx context.Context, storyID uuid.UUID) ([]GetStoryReactionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getStoryReactions, storyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStoryReactionsRow
	for rows.Next() {
		var i GetStoryReactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.StoryID,
			&i.UserID,
			&i.Emoji,
			&i.CreatedAt,
			&i.Username,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStoryViewers = `-- name: GetStoryViewers :many
SELECT sv.id, sv.story_id, sv.user_id, sv.viewed_at, sv.view_count, u.username, u.avatar_url
FROM story_views sv
JOIN users u ON sv.user_id = u.id
JOIN stories s ON sv.story_id = s.id
WHERE sv.story_id = $1 AND sv.user_id != s.user_id
ORDER BY sv.viewed_at DESC
`

type GetStoryViewersRow struct {
	ID        uuid.UUID      `json:"id"`
	StoryID   uuid.UUID      `json:"story_id"`
	UserID    uuid.UUID      `json:"user_id"`
	ViewedAt  time.Time      `json:"viewed_at"`
	ViewCount int32          `json:"view_count"`
	Username  string         `json:"username"`
	AvatarUrl sql.NullString `json:"avatar_url"`
}

// Only accessible by story owner
func (q *Queries) GetStoryViewers(ctx context.Context, storyID uuid.UUID) ([]GetStoryViewersRow, error) {
	rows, err := q.db.QueryContext(ctx, getStoryViewers, storyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStoryViewersRow
	for rows.Next() {
		var i GetStoryViewersRow
		if err := rows.Scan(
			&i.ID,
			&i.StoryID,
			&i.UserID,
			&i.ViewedAt,
			&i.ViewCount,
			&i.Username,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
