// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const banUser = `-- name: BanUser :one
UPDATE users
SET is_shadow_banned = $2
WHERE id = $1
RETURNING id, phone, password_hash, username, full_name, avatar_url, bio, role, trust_level, is_verified, is_shadow_banned, last_active_at, created_at, is_ghost_mode, activity_streak, streak_updated_at, is_premium, streak_freezes_remaining, boost_expires_at, banner_url, theme, profile_visibility, email, website_url, links, google_id, password_reset_token, password_reset_expires_at, ghost_mode_expires_at
`

type BanUserParams struct {
	ID             uuid.UUID `json:"id"`
	IsShadowBanned bool      `json:"is_shadow_banned"`
}

func (q *Queries) BanUser(ctx context.Context, arg BanUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, banUser, arg.ID, arg.IsShadowBanned)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.PasswordHash,
		&i.Username,
		&i.FullName,
		&i.AvatarUrl,
		&i.Bio,
		&i.Role,
		&i.TrustLevel,
		&i.IsVerified,
		&i.IsShadowBanned,
		&i.LastActiveAt,
		&i.CreatedAt,
		&i.IsGhostMode,
		&i.ActivityStreak,
		&i.StreakUpdatedAt,
		&i.IsPremium,
		&i.StreakFreezesRemaining,
		&i.BoostExpiresAt,
		&i.BannerUrl,
		&i.Theme,
		&i.ProfileVisibility,
		&i.Email,
		&i.WebsiteUrl,
		&i.Links,
		&i.GoogleID,
		&i.PasswordResetToken,
		&i.PasswordResetExpiresAt,
		&i.GhostModeExpiresAt,
	)
	return i, err
}

const boostUser = `-- name: BoostUser :one
UPDATE users
SET boost_expires_at = $2
WHERE id = $1
RETURNING id, phone, password_hash, username, full_name, avatar_url, bio, role, trust_level, is_verified, is_shadow_banned, last_active_at, created_at, is_ghost_mode, activity_streak, streak_updated_at, is_premium, streak_freezes_remaining, boost_expires_at, banner_url, theme, profile_visibility, email, website_url, links, google_id, password_reset_token, password_reset_expires_at, ghost_mode_expires_at
`

type BoostUserParams struct {
	ID             uuid.UUID    `json:"id"`
	BoostExpiresAt sql.NullTime `json:"boost_expires_at"`
}

func (q *Queries) BoostUser(ctx context.Context, arg BoostUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, boostUser, arg.ID, arg.BoostExpiresAt)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.PasswordHash,
		&i.Username,
		&i.FullName,
		&i.AvatarUrl,
		&i.Bio,
		&i.Role,
		&i.TrustLevel,
		&i.IsVerified,
		&i.IsShadowBanned,
		&i.LastActiveAt,
		&i.CreatedAt,
		&i.IsGhostMode,
		&i.ActivityStreak,
		&i.StreakUpdatedAt,
		&i.IsPremium,
		&i.StreakFreezesRemaining,
		&i.BoostExpiresAt,
		&i.BannerUrl,
		&i.Theme,
		&i.ProfileVisibility,
		&i.Email,
		&i.WebsiteUrl,
		&i.Links,
		&i.GoogleID,
		&i.PasswordResetToken,
		&i.PasswordResetExpiresAt,
		&i.GhostModeExpiresAt,
	)
	return i, err
}

const clearPasswordResetToken = `-- name: ClearPasswordResetToken :exec
UPDATE users
SET 
    password_reset_token = NULL,
    password_reset_expires_at = NULL
WHERE id = $1
`

func (q *Queries) ClearPasswordResetToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, clearPasswordResetToken, id)
	return err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  phone,
  password_hash,
  username,
  full_name
) VALUES (
  $1, $2, $3, $4
) RETURNING id, phone, password_hash, username, full_name, avatar_url, bio, role, trust_level, is_verified, is_shadow_banned, last_active_at, created_at, is_ghost_mode, activity_streak, streak_updated_at, is_premium, streak_freezes_remaining, boost_expires_at, banner_url, theme, profile_visibility, email, website_url, links, google_id, password_reset_token, password_reset_expires_at, ghost_mode_expires_at
`

type CreateUserParams struct {
	Phone        string `json:"phone"`
	PasswordHash string `json:"password_hash"`
	Username     string `json:"username"`
	FullName     string `json:"full_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Phone,
		arg.PasswordHash,
		arg.Username,
		arg.FullName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.PasswordHash,
		&i.Username,
		&i.FullName,
		&i.AvatarUrl,
		&i.Bio,
		&i.Role,
		&i.TrustLevel,
		&i.IsVerified,
		&i.IsShadowBanned,
		&i.LastActiveAt,
		&i.CreatedAt,
		&i.IsGhostMode,
		&i.ActivityStreak,
		&i.StreakUpdatedAt,
		&i.IsPremium,
		&i.StreakFreezesRemaining,
		&i.BoostExpiresAt,
		&i.BannerUrl,
		&i.Theme,
		&i.ProfileVisibility,
		&i.Email,
		&i.WebsiteUrl,
		&i.Links,
		&i.GoogleID,
		&i.PasswordResetToken,
		&i.PasswordResetExpiresAt,
		&i.GhostModeExpiresAt,
	)
	return i, err
}

const deleteAllUserData = `-- name: DeleteAllUserData :exec
DELETE FROM users
WHERE id = $1
`

// Used for panic mode - deletes all user data
func (q *Queries) DeleteAllUserData(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAllUserData, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getSystemStats = `-- name: GetSystemStats :one
SELECT 
  COUNT(*) as total_users,
  COUNT(*) FILTER (WHERE created_at > NOW() - INTERVAL '24 hours') as new_users_24h,
  COUNT(*) FILTER (WHERE last_active_at > NOW() - INTERVAL '1 hour') as active_users_1h
FROM users
`

type GetSystemStatsRow struct {
	TotalUsers    int64 `json:"total_users"`
	NewUsers24h   int64 `json:"new_users_24h"`
	ActiveUsers1h int64 `json:"active_users_1h"`
}

func (q *Queries) GetSystemStats(ctx context.Context) (GetSystemStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getSystemStats)
	var i GetSystemStatsRow
	err := row.Scan(&i.TotalUsers, &i.NewUsers24h, &i.ActiveUsers1h)
	return i, err
}

const getUserActivityStatus = `-- name: GetUserActivityStatus :one
SELECT 
  id,
  username,
  last_active_at,
  CASE
    WHEN DATE(last_active_at) < CURRENT_DATE - INTERVAL '1 day' THEN 0
    ELSE activity_streak
  END as activity_streak,
  CASE
    WHEN DATE(last_active_at) >= CURRENT_DATE - INTERVAL '1 day' THEN 'active'
    ELSE 'hidden'
  END as visibility_status,
  CASE
    WHEN DATE(last_active_at) >= CURRENT_DATE - INTERVAL '1 day' THEN true
    ELSE false
  END as is_visible
FROM users
WHERE id = $1
`

type GetUserActivityStatusRow struct {
	ID               uuid.UUID    `json:"id"`
	Username         string       `json:"username"`
	LastActiveAt     sql.NullTime `json:"last_active_at"`
	ActivityStreak   interface{}  `json:"activity_streak"`
	VisibilityStatus string       `json:"visibility_status"`
	IsVisible        bool         `json:"is_visible"`
}

// Get user's activity status and visibility
func (q *Queries) GetUserActivityStatus(ctx context.Context, id uuid.UUID) (GetUserActivityStatusRow, error) {
	row := q.db.QueryRowContext(ctx, getUserActivityStatus, id)
	var i GetUserActivityStatusRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.LastActiveAt,
		&i.ActivityStreak,
		&i.VisibilityStatus,
		&i.IsVisible,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, phone, password_hash, username, full_name, avatar_url, bio, role, trust_level, is_verified, is_shadow_banned, last_active_at, created_at, is_ghost_mode, activity_streak, streak_updated_at, is_premium, streak_freezes_remaining, boost_expires_at, banner_url, theme, profile_visibility, email, website_url, links, google_id, password_reset_token, password_reset_expires_at, ghost_mode_expires_at FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.PasswordHash,
		&i.Username,
		&i.FullName,
		&i.AvatarUrl,
		&i.Bio,
		&i.Role,
		&i.TrustLevel,
		&i.IsVerified,
		&i.IsShadowBanned,
		&i.LastActiveAt,
		&i.CreatedAt,
		&i.IsGhostMode,
		&i.ActivityStreak,
		&i.StreakUpdatedAt,
		&i.IsPremium,
		&i.StreakFreezesRemaining,
		&i.BoostExpiresAt,
		&i.BannerUrl,
		&i.Theme,
		&i.ProfileVisibility,
		&i.Email,
		&i.WebsiteUrl,
		&i.Links,
		&i.GoogleID,
		&i.PasswordResetToken,
		&i.PasswordResetExpiresAt,
		&i.GhostModeExpiresAt,
	)
	return i, err
}

const getUserByGoogleID = `-- name: GetUserByGoogleID :one
SELECT id, phone, password_hash, username, full_name, avatar_url, bio, role, trust_level, is_verified, is_shadow_banned, last_active_at, created_at, is_ghost_mode, activity_streak, streak_updated_at, is_premium, streak_freezes_remaining, boost_expires_at, banner_url, theme, profile_visibility, email, website_url, links, google_id, password_reset_token, password_reset_expires_at, ghost_mode_expires_at FROM users
WHERE google_id = $1 LIMIT 1
`

func (q *Queries) GetUserByGoogleID(ctx context.Context, googleID sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByGoogleID, googleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.PasswordHash,
		&i.Username,
		&i.FullName,
		&i.AvatarUrl,
		&i.Bio,
		&i.Role,
		&i.TrustLevel,
		&i.IsVerified,
		&i.IsShadowBanned,
		&i.LastActiveAt,
		&i.CreatedAt,
		&i.IsGhostMode,
		&i.ActivityStreak,
		&i.StreakUpdatedAt,
		&i.IsPremium,
		&i.StreakFreezesRemaining,
		&i.BoostExpiresAt,
		&i.BannerUrl,
		&i.Theme,
		&i.ProfileVisibility,
		&i.Email,
		&i.WebsiteUrl,
		&i.Links,
		&i.GoogleID,
		&i.PasswordResetToken,
		&i.PasswordResetExpiresAt,
		&i.GhostModeExpiresAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, phone, password_hash, username, full_name, avatar_url, bio, role, trust_level, is_verified, is_shadow_banned, last_active_at, created_at, is_ghost_mode, activity_streak, streak_updated_at, is_premium, streak_freezes_remaining, boost_expires_at, banner_url, theme, profile_visibility, email, website_url, links, google_id, password_reset_token, password_reset_expires_at, ghost_mode_expires_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.PasswordHash,
		&i.Username,
		&i.FullName,
		&i.AvatarUrl,
		&i.Bio,
		&i.Role,
		&i.TrustLevel,
		&i.IsVerified,
		&i.IsShadowBanned,
		&i.LastActiveAt,
		&i.CreatedAt,
		&i.IsGhostMode,
		&i.ActivityStreak,
		&i.StreakUpdatedAt,
		&i.IsPremium,
		&i.StreakFreezesRemaining,
		&i.BoostExpiresAt,
		&i.BannerUrl,
		&i.Theme,
		&i.ProfileVisibility,
		&i.Email,
		&i.WebsiteUrl,
		&i.Links,
		&i.GoogleID,
		&i.PasswordResetToken,
		&i.PasswordResetExpiresAt,
		&i.GhostModeExpiresAt,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, phone, password_hash, username, full_name, avatar_url, bio, role, trust_level, is_verified, is_shadow_banned, last_active_at, created_at, is_ghost_mode, activity_streak, streak_updated_at, is_premium, streak_freezes_remaining, boost_expires_at, banner_url, theme, profile_visibility, email, website_url, links, google_id, password_reset_token, password_reset_expires_at, ghost_mode_expires_at FROM users
WHERE phone = $1 LIMIT 1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phone string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByPhone, phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.PasswordHash,
		&i.Username,
		&i.FullName,
		&i.AvatarUrl,
		&i.Bio,
		&i.Role,
		&i.TrustLevel,
		&i.IsVerified,
		&i.IsShadowBanned,
		&i.LastActiveAt,
		&i.CreatedAt,
		&i.IsGhostMode,
		&i.ActivityStreak,
		&i.StreakUpdatedAt,
		&i.IsPremium,
		&i.StreakFreezesRemaining,
		&i.BoostExpiresAt,
		&i.BannerUrl,
		&i.Theme,
		&i.ProfileVisibility,
		&i.Email,
		&i.WebsiteUrl,
		&i.Links,
		&i.GoogleID,
		&i.PasswordResetToken,
		&i.PasswordResetExpiresAt,
		&i.GhostModeExpiresAt,
	)
	return i, err
}

const getUserByResetToken = `-- name: GetUserByResetToken :one
SELECT id, phone, password_hash, username, full_name, avatar_url, bio, role, trust_level, is_verified, is_shadow_banned, last_active_at, created_at, is_ghost_mode, activity_streak, streak_updated_at, is_premium, streak_freezes_remaining, boost_expires_at, banner_url, theme, profile_visibility, email, website_url, links, google_id, password_reset_token, password_reset_expires_at, ghost_mode_expires_at FROM users
WHERE password_reset_token = $1 
AND password_reset_expires_at > now()
LIMIT 1
`

func (q *Queries) GetUserByResetToken(ctx context.Context, passwordResetToken sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByResetToken, passwordResetToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.PasswordHash,
		&i.Username,
		&i.FullName,
		&i.AvatarUrl,
		&i.Bio,
		&i.Role,
		&i.TrustLevel,
		&i.IsVerified,
		&i.IsShadowBanned,
		&i.LastActiveAt,
		&i.CreatedAt,
		&i.IsGhostMode,
		&i.ActivityStreak,
		&i.StreakUpdatedAt,
		&i.IsPremium,
		&i.StreakFreezesRemaining,
		&i.BoostExpiresAt,
		&i.BannerUrl,
		&i.Theme,
		&i.ProfileVisibility,
		&i.Email,
		&i.WebsiteUrl,
		&i.Links,
		&i.GoogleID,
		&i.PasswordResetToken,
		&i.PasswordResetExpiresAt,
		&i.GhostModeExpiresAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, phone, password_hash, username, full_name, avatar_url, bio, role, trust_level, is_verified, is_shadow_banned, last_active_at, created_at, is_ghost_mode, activity_streak, streak_updated_at, is_premium, streak_freezes_remaining, boost_expires_at, banner_url, theme, profile_visibility, email, website_url, links, google_id, password_reset_token, password_reset_expires_at, ghost_mode_expires_at FROM users
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.PasswordHash,
		&i.Username,
		&i.FullName,
		&i.AvatarUrl,
		&i.Bio,
		&i.Role,
		&i.TrustLevel,
		&i.IsVerified,
		&i.IsShadowBanned,
		&i.LastActiveAt,
		&i.CreatedAt,
		&i.IsGhostMode,
		&i.ActivityStreak,
		&i.StreakUpdatedAt,
		&i.IsPremium,
		&i.StreakFreezesRemaining,
		&i.BoostExpiresAt,
		&i.BannerUrl,
		&i.Theme,
		&i.ProfileVisibility,
		&i.Email,
		&i.WebsiteUrl,
		&i.Links,
		&i.GoogleID,
		&i.PasswordResetToken,
		&i.PasswordResetExpiresAt,
		&i.GhostModeExpiresAt,
	)
	return i, err
}

const getUserEngagementStats = `-- name: GetUserEngagementStats :one
SELECT 
    (SELECT COUNT(*) FROM stories WHERE stories.user_id = $1) as story_count,
    (SELECT COUNT(*) FROM connections WHERE (connections.requester_id = $1 OR connections.target_id = $1) AND status = 'accepted') as connection_count,
    (SELECT COUNT(*) FROM story_views v JOIN stories s ON v.story_id = s.id WHERE s.user_id = $1) as total_views,
    (SELECT COUNT(*) FROM story_reactions r JOIN stories s ON r.story_id = s.id WHERE s.user_id = $1) as total_reactions
`

type GetUserEngagementStatsRow struct {
	StoryCount      int64 `json:"story_count"`
	ConnectionCount int64 `json:"connection_count"`
	TotalViews      int64 `json:"total_views"`
	TotalReactions  int64 `json:"total_reactions"`
}

func (q *Queries) GetUserEngagementStats(ctx context.Context, userID uuid.UUID) (GetUserEngagementStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getUserEngagementStats, userID)
	var i GetUserEngagementStatsRow
	err := row.Scan(
		&i.StoryCount,
		&i.ConnectionCount,
		&i.TotalViews,
		&i.TotalReactions,
	)
	return i, err
}

const getUserProfile = `-- name: GetUserProfile :one
SELECT 
  u.id, u.username, u.full_name, u.avatar_url, u.bio, u.banner_url, u.theme, u.profile_visibility, u.email, u.is_ghost_mode, u.website_url, u.links, u.created_at, u.is_premium, u.last_active_at,
  (SELECT COUNT(*) FROM stories WHERE stories.user_id = u.id) as story_count,
  (SELECT COUNT(*) FROM connections WHERE (connections.requester_id = u.id OR connections.target_id = u.id) AND status = 'accepted') as connection_count,
  CASE
    WHEN DATE(u.last_active_at) < CURRENT_DATE - INTERVAL '1 day' THEN 0
    ELSE u.activity_streak
  END as activity_streak,
  CASE
    WHEN DATE(u.last_active_at) >= CURRENT_DATE - INTERVAL '1 day' THEN 'active'
    ELSE 'hidden'
  END as visibility_status
FROM users u
WHERE u.id = $1
`

type GetUserProfileRow struct {
	ID                uuid.UUID       `json:"id"`
	Username          string          `json:"username"`
	FullName          string          `json:"full_name"`
	AvatarUrl         sql.NullString  `json:"avatar_url"`
	Bio               sql.NullString  `json:"bio"`
	BannerUrl         sql.NullString  `json:"banner_url"`
	Theme             sql.NullString  `json:"theme"`
	ProfileVisibility sql.NullString  `json:"profile_visibility"`
	Email             sql.NullString  `json:"email"`
	IsGhostMode       bool            `json:"is_ghost_mode"`
	WebsiteUrl        sql.NullString  `json:"website_url"`
	Links             json.RawMessage `json:"links"`
	CreatedAt         time.Time       `json:"created_at"`
	IsPremium         sql.NullBool    `json:"is_premium"`
	LastActiveAt      sql.NullTime    `json:"last_active_at"`
	StoryCount        int64           `json:"story_count"`
	ConnectionCount   int64           `json:"connection_count"`
	ActivityStreak    interface{}     `json:"activity_streak"`
	VisibilityStatus  string          `json:"visibility_status"`
}

func (q *Queries) GetUserProfile(ctx context.Context, id uuid.UUID) (GetUserProfileRow, error) {
	row := q.db.QueryRowContext(ctx, getUserProfile, id)
	var i GetUserProfileRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FullName,
		&i.AvatarUrl,
		&i.Bio,
		&i.BannerUrl,
		&i.Theme,
		&i.ProfileVisibility,
		&i.Email,
		&i.IsGhostMode,
		&i.WebsiteUrl,
		&i.Links,
		&i.CreatedAt,
		&i.IsPremium,
		&i.LastActiveAt,
		&i.StoryCount,
		&i.ConnectionCount,
		&i.ActivityStreak,
		&i.VisibilityStatus,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many

SELECT id, phone, password_hash, username, full_name, avatar_url, bio, role, trust_level, is_verified, is_shadow_banned, last_active_at, created_at, is_ghost_mode, activity_streak, streak_updated_at, is_premium, streak_freezes_remaining, boost_expires_at, banner_url, theme, profile_visibility, email, website_url, links, google_id, password_reset_token, password_reset_expires_at, ghost_mode_expires_at FROM users
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// Admin Queries
func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Phone,
			&i.PasswordHash,
			&i.Username,
			&i.FullName,
			&i.AvatarUrl,
			&i.Bio,
			&i.Role,
			&i.TrustLevel,
			&i.IsVerified,
			&i.IsShadowBanned,
			&i.LastActiveAt,
			&i.CreatedAt,
			&i.IsGhostMode,
			&i.ActivityStreak,
			&i.StreakUpdatedAt,
			&i.IsPremium,
			&i.StreakFreezesRemaining,
			&i.BoostExpiresAt,
			&i.BannerUrl,
			&i.Theme,
			&i.ProfileVisibility,
			&i.Email,
			&i.WebsiteUrl,
			&i.Links,
			&i.GoogleID,
			&i.PasswordResetToken,
			&i.PasswordResetExpiresAt,
			&i.GhostModeExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsers = `-- name: SearchUsers :many
SELECT 
  id,
  username,
  full_name,
  avatar_url,
  bio,
  is_verified,
  created_at
FROM users
WHERE 
  (username ILIKE '%' || $1::text || '%' OR full_name ILIKE '%' || $1::text || '%')
  AND is_shadow_banned = false
LIMIT 20
`

type SearchUsersRow struct {
	ID         uuid.UUID      `json:"id"`
	Username   string         `json:"username"`
	FullName   string         `json:"full_name"`
	AvatarUrl  sql.NullString `json:"avatar_url"`
	Bio        sql.NullString `json:"bio"`
	IsVerified bool           `json:"is_verified"`
	CreatedAt  time.Time      `json:"created_at"`
}

func (q *Queries) SearchUsers(ctx context.Context, query string) ([]SearchUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, searchUsers, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchUsersRow
	for rows.Next() {
		var i SearchUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FullName,
			&i.AvatarUrl,
			&i.Bio,
			&i.IsVerified,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPasswordResetToken = `-- name: SetPasswordResetToken :one
UPDATE users
SET 
    password_reset_token = $2,
    password_reset_expires_at = $3
WHERE email = $1
RETURNING id, phone, password_hash, username, full_name, avatar_url, bio, role, trust_level, is_verified, is_shadow_banned, last_active_at, created_at, is_ghost_mode, activity_streak, streak_updated_at, is_premium, streak_freezes_remaining, boost_expires_at, banner_url, theme, profile_visibility, email, website_url, links, google_id, password_reset_token, password_reset_expires_at, ghost_mode_expires_at
`

type SetPasswordResetTokenParams struct {
	Email                  sql.NullString `json:"email"`
	PasswordResetToken     sql.NullString `json:"password_reset_token"`
	PasswordResetExpiresAt sql.NullTime   `json:"password_reset_expires_at"`
}

func (q *Queries) SetPasswordResetToken(ctx context.Context, arg SetPasswordResetTokenParams) (User, error) {
	row := q.db.QueryRowContext(ctx, setPasswordResetToken, arg.Email, arg.PasswordResetToken, arg.PasswordResetExpiresAt)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.PasswordHash,
		&i.Username,
		&i.FullName,
		&i.AvatarUrl,
		&i.Bio,
		&i.Role,
		&i.TrustLevel,
		&i.IsVerified,
		&i.IsShadowBanned,
		&i.LastActiveAt,
		&i.CreatedAt,
		&i.IsGhostMode,
		&i.ActivityStreak,
		&i.StreakUpdatedAt,
		&i.IsPremium,
		&i.StreakFreezesRemaining,
		&i.BoostExpiresAt,
		&i.BannerUrl,
		&i.Theme,
		&i.ProfileVisibility,
		&i.Email,
		&i.WebsiteUrl,
		&i.Links,
		&i.GoogleID,
		&i.PasswordResetToken,
		&i.PasswordResetExpiresAt,
		&i.GhostModeExpiresAt,
	)
	return i, err
}

const toggleGhostMode = `-- name: ToggleGhostMode :one

UPDATE users
SET is_ghost_mode = $2,
    ghost_mode_expires_at = $3
WHERE id = $1
RETURNING id, phone, password_hash, username, full_name, avatar_url, bio, role, trust_level, is_verified, is_shadow_banned, last_active_at, created_at, is_ghost_mode, activity_streak, streak_updated_at, is_premium, streak_freezes_remaining, boost_expires_at, banner_url, theme, profile_visibility, email, website_url, links, google_id, password_reset_token, password_reset_expires_at, ghost_mode_expires_at
`

type ToggleGhostModeParams struct {
	ID                 uuid.UUID    `json:"id"`
	IsGhostMode        bool         `json:"is_ghost_mode"`
	GhostModeExpiresAt sql.NullTime `json:"ghost_mode_expires_at"`
}

// Privacy Features
func (q *Queries) ToggleGhostMode(ctx context.Context, arg ToggleGhostModeParams) (User, error) {
	row := q.db.QueryRowContext(ctx, toggleGhostMode, arg.ID, arg.IsGhostMode, arg.GhostModeExpiresAt)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.PasswordHash,
		&i.Username,
		&i.FullName,
		&i.AvatarUrl,
		&i.Bio,
		&i.Role,
		&i.TrustLevel,
		&i.IsVerified,
		&i.IsShadowBanned,
		&i.LastActiveAt,
		&i.CreatedAt,
		&i.IsGhostMode,
		&i.ActivityStreak,
		&i.StreakUpdatedAt,
		&i.IsPremium,
		&i.StreakFreezesRemaining,
		&i.BoostExpiresAt,
		&i.BannerUrl,
		&i.Theme,
		&i.ProfileVisibility,
		&i.Email,
		&i.WebsiteUrl,
		&i.Links,
		&i.GoogleID,
		&i.PasswordResetToken,
		&i.PasswordResetExpiresAt,
		&i.GhostModeExpiresAt,
	)
	return i, err
}

const updateUserActivity = `-- name: UpdateUserActivity :one
UPDATE users
SET 
  last_active_at = now(),
  activity_streak = CASE
    -- If last active was yesterday, increment streak
    WHEN DATE(last_active_at) = CURRENT_DATE - INTERVAL '1 day' THEN activity_streak + 1
    -- If last active was today, keep streak
    WHEN DATE(last_active_at) = CURRENT_DATE THEN activity_streak
    -- If missed days but has freezes, keep streak
    WHEN streak_freezes_remaining > 0 THEN activity_streak
    -- Otherwise reset streak to 1
    ELSE 1
  END,
  streak_freezes_remaining = CASE
    -- Consume freeze only if missed days and has freezes
    WHEN DATE(last_active_at) < CURRENT_DATE - INTERVAL '1 day' AND streak_freezes_remaining > 0 THEN streak_freezes_remaining - 1
    ELSE streak_freezes_remaining
  END,
  streak_updated_at = now()
WHERE id = $1
RETURNING id, phone, password_hash, username, full_name, avatar_url, bio, role, trust_level, is_verified, is_shadow_banned, last_active_at, created_at, is_ghost_mode, activity_streak, streak_updated_at, is_premium, streak_freezes_remaining, boost_expires_at, banner_url, theme, profile_visibility, email, website_url, links, google_id, password_reset_token, password_reset_expires_at, ghost_mode_expires_at
`

// Updates last_active_at and calculates activity streak
func (q *Queries) UpdateUserActivity(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserActivity, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.PasswordHash,
		&i.Username,
		&i.FullName,
		&i.AvatarUrl,
		&i.Bio,
		&i.Role,
		&i.TrustLevel,
		&i.IsVerified,
		&i.IsShadowBanned,
		&i.LastActiveAt,
		&i.CreatedAt,
		&i.IsGhostMode,
		&i.ActivityStreak,
		&i.StreakUpdatedAt,
		&i.IsPremium,
		&i.StreakFreezesRemaining,
		&i.BoostExpiresAt,
		&i.BannerUrl,
		&i.Theme,
		&i.ProfileVisibility,
		&i.Email,
		&i.WebsiteUrl,
		&i.Links,
		&i.GoogleID,
		&i.PasswordResetToken,
		&i.PasswordResetExpiresAt,
		&i.GhostModeExpiresAt,
	)
	return i, err
}

const updateUserEmail = `-- name: UpdateUserEmail :one
UPDATE users
SET email = $2
WHERE id = $1
RETURNING id, username, email, full_name
`

type UpdateUserEmailParams struct {
	ID    uuid.UUID      `json:"id"`
	Email sql.NullString `json:"email"`
}

type UpdateUserEmailRow struct {
	ID       uuid.UUID      `json:"id"`
	Username string         `json:"username"`
	Email    sql.NullString `json:"email"`
	FullName string         `json:"full_name"`
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) (UpdateUserEmailRow, error) {
	row := q.db.QueryRowContext(ctx, updateUserEmail, arg.ID, arg.Email)
	var i UpdateUserEmailRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.FullName,
	)
	return i, err
}

const updateUserGoogleID = `-- name: UpdateUserGoogleID :one
UPDATE users
SET google_id = $2
WHERE id = $1
RETURNING id, phone, password_hash, username, full_name, avatar_url, bio, role, trust_level, is_verified, is_shadow_banned, last_active_at, created_at, is_ghost_mode, activity_streak, streak_updated_at, is_premium, streak_freezes_remaining, boost_expires_at, banner_url, theme, profile_visibility, email, website_url, links, google_id, password_reset_token, password_reset_expires_at, ghost_mode_expires_at
`

type UpdateUserGoogleIDParams struct {
	ID       uuid.UUID      `json:"id"`
	GoogleID sql.NullString `json:"google_id"`
}

func (q *Queries) UpdateUserGoogleID(ctx context.Context, arg UpdateUserGoogleIDParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserGoogleID, arg.ID, arg.GoogleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.PasswordHash,
		&i.Username,
		&i.FullName,
		&i.AvatarUrl,
		&i.Bio,
		&i.Role,
		&i.TrustLevel,
		&i.IsVerified,
		&i.IsShadowBanned,
		&i.LastActiveAt,
		&i.CreatedAt,
		&i.IsGhostMode,
		&i.ActivityStreak,
		&i.StreakUpdatedAt,
		&i.IsPremium,
		&i.StreakFreezesRemaining,
		&i.BoostExpiresAt,
		&i.BannerUrl,
		&i.Theme,
		&i.ProfileVisibility,
		&i.Email,
		&i.WebsiteUrl,
		&i.Links,
		&i.GoogleID,
		&i.PasswordResetToken,
		&i.PasswordResetExpiresAt,
		&i.GhostModeExpiresAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $2
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET 
  full_name = COALESCE($2, full_name),
  username = COALESCE($3, username),
  avatar_url = COALESCE($4, avatar_url),
  bio = COALESCE($5, bio),
  banner_url = COALESCE($6, banner_url),
  theme = COALESCE($7, theme),
  profile_visibility = COALESCE($8, profile_visibility),
  website_url = COALESCE($9, website_url),
  links = COALESCE($10, links)
WHERE id = $1
RETURNING id, username, full_name, avatar_url, bio, banner_url, theme, profile_visibility, website_url, links, created_at
`

type UpdateUserProfileParams struct {
	ID                uuid.UUID             `json:"id"`
	FullName          sql.NullString        `json:"full_name"`
	Username          sql.NullString        `json:"username"`
	AvatarUrl         sql.NullString        `json:"avatar_url"`
	Bio               sql.NullString        `json:"bio"`
	BannerUrl         sql.NullString        `json:"banner_url"`
	Theme             sql.NullString        `json:"theme"`
	ProfileVisibility sql.NullString        `json:"profile_visibility"`
	WebsiteUrl        sql.NullString        `json:"website_url"`
	Links             pqtype.NullRawMessage `json:"links"`
}

type UpdateUserProfileRow struct {
	ID                uuid.UUID       `json:"id"`
	Username          string          `json:"username"`
	FullName          string          `json:"full_name"`
	AvatarUrl         sql.NullString  `json:"avatar_url"`
	Bio               sql.NullString  `json:"bio"`
	BannerUrl         sql.NullString  `json:"banner_url"`
	Theme             sql.NullString  `json:"theme"`
	ProfileVisibility sql.NullString  `json:"profile_visibility"`
	WebsiteUrl        sql.NullString  `json:"website_url"`
	Links             json.RawMessage `json:"links"`
	CreatedAt         time.Time       `json:"created_at"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UpdateUserProfileRow, error) {
	row := q.db.QueryRowContext(ctx, updateUserProfile,
		arg.ID,
		arg.FullName,
		arg.Username,
		arg.AvatarUrl,
		arg.Bio,
		arg.BannerUrl,
		arg.Theme,
		arg.ProfileVisibility,
		arg.WebsiteUrl,
		arg.Links,
	)
	var i UpdateUserProfileRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FullName,
		&i.AvatarUrl,
		&i.Bio,
		&i.BannerUrl,
		&i.Theme,
		&i.ProfileVisibility,
		&i.WebsiteUrl,
		&i.Links,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserTrust = `-- name: UpdateUserTrust :one
UPDATE users
SET trust_level = $2
WHERE id = $1
RETURNING id, phone, password_hash, username, full_name, avatar_url, bio, role, trust_level, is_verified, is_shadow_banned, last_active_at, created_at, is_ghost_mode, activity_streak, streak_updated_at, is_premium, streak_freezes_remaining, boost_expires_at, banner_url, theme, profile_visibility, email, website_url, links, google_id, password_reset_token, password_reset_expires_at, ghost_mode_expires_at
`

type UpdateUserTrustParams struct {
	ID         uuid.UUID `json:"id"`
	TrustLevel int32     `json:"trust_level"`
}

func (q *Queries) UpdateUserTrust(ctx context.Context, arg UpdateUserTrustParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserTrust, arg.ID, arg.TrustLevel)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.PasswordHash,
		&i.Username,
		&i.FullName,
		&i.AvatarUrl,
		&i.Bio,
		&i.Role,
		&i.TrustLevel,
		&i.IsVerified,
		&i.IsShadowBanned,
		&i.LastActiveAt,
		&i.CreatedAt,
		&i.IsGhostMode,
		&i.ActivityStreak,
		&i.StreakUpdatedAt,
		&i.IsPremium,
		&i.StreakFreezesRemaining,
		&i.BoostExpiresAt,
		&i.BannerUrl,
		&i.Theme,
		&i.ProfileVisibility,
		&i.Email,
		&i.WebsiteUrl,
		&i.Links,
		&i.GoogleID,
		&i.PasswordResetToken,
		&i.PasswordResetExpiresAt,
		&i.GhostModeExpiresAt,
	)
	return i, err
}
